% V15_perbit_diag: V3 baseline + PerBitErrors block (120 separate error
% counters, one per bit-position in the BIST window). Successor to V7's
% per-byte (15-counter) diagnostic.
%
% Selector: iq_debug_mux (8 LSBs, 0..119)
% Output:   per_bit_errors_out, AXI4-Lite x"11C" (same address as V7)
%
% Hardware-test flow (analogous to HardwarePerBytePositionTest):
%   for bit = 0..119:
%       write iq_debug_mux = bit
%       sleep small
%       read x"11C" -> errors at that bit-position

sys  = 'commhdlQPSKTxRxLoopback';
load_system(sys);
loop = [sys '/TxRxLoopback'];
rx   = [loop '/Receiver'];

% --- V3 scalar patches ---
ic = get_param(sys,'InitFcn');
ic = regexprep(ic,'UpsamplesRx\s*=\s*\d+\s*;','UpsamplesRx = 1;');
ic = regexprep(ic,'UpsamplesTx\s*=\s*\d+\s*;','UpsamplesTx = 1;');
set_param(sys,'InitFcn',ic);
for c = {[sys '/Transmitter/Input Data'], [sys '/TxRxLoopback/Transmitter/Input Data']}
  try, set_param(c{1},'Rsym','3.84e6'); catch, end
end

% HDL Counter safety
for cp = { ...
    [sys '/Receiver/QPSK Rx/Frequency and Time Synchronizer/Symbol Synchronizer/Rate Handle/HDL Counter'], ...
    [sys '/Transmitter/QPSK Tx/Bit Packetizer/Data Bits FIFO/HDL Counter3'], ...
    [sys '/TxRxLoopback/Receiver/QPSK Rx/Frequency and Time Synchronizer/Symbol Synchronizer/Rate Handle/HDL Counter'], ...
    [sys '/TxRxLoopback/Transmitter/QPSK Tx/Bit Packetizer/Data Bits FIFO/HDL Counter3']}
  b = cp{1};
  try
    wl = get_param(b,'CountWordLen');
    if ~startsWith(strtrim(wl),'max(1,'), set_param(b,'CountWordLen', sprintf('max(1,%s)', wl)); end
    cm = get_param(b,'CountMax');
    if ~startsWith(strtrim(cm),'max(1,'), set_param(b,'CountMax', sprintf('max(1,%s)', cm)); end
  catch, end
end

% --- Insert PerBitErrors block ---
if isempty(find_system(rx,'SearchDepth',1,'Name','PerBitErrors'))
    fprintf('Inserting PerBitErrors block...\n');
    pbe = [rx '/PerBitErrors'];
    add_block('simulink/User-Defined Functions/MATLAB Function', pbe);

    pbeLines = { ...
        'function out = perBitErr(valid, datain, dstart, sel)' ...
        '%#codegen' ...
        '% Per-bit-position BIST counter. sel (0..119) selects which bit.' ...
        'persistent count bitErrors' ...
        'if isempty(count)' ...
        '    count = uint32(0);' ...
        '    bitErrors = zeros(1,120,''uint32'');' ...
        'end' ...
        '% 120-bit ADI Hello World ASCII reference' ...
        'msgbits = logical([ ...' ...
        '    0 1 0 0 0 0 0 1   0 1 0 0 0 1 0 0   0 1 0 0 1 0 0 1   ...' ...
        '    0 0 1 0 0 0 0 0   0 1 0 0 1 0 0 0   0 1 1 0 0 1 0 1   ...' ...
        '    0 1 1 0 1 1 0 0   0 1 1 0 1 1 0 0   0 1 1 0 1 1 1 1   ...' ...
        '    0 0 1 0 0 0 0 0   0 1 0 1 0 1 1 1   0 1 1 0 1 1 1 1   ...' ...
        '    0 1 1 1 0 0 1 0   0 1 1 0 1 1 0 0   0 1 1 0 0 1 0 0]);' ...
        'selU = uint32(sel);' ...
        'if valid' ...
        '    if dstart' ...
        '        count = uint32(1);' ...
        '    end' ...
        '    if count >= uint32(1) && count <= uint32(120)' ...
        '        if datain ~= msgbits(count)' ...
        '            bitErrors(count) = bitErrors(count) + uint32(1);' ...
        '        end' ...
        '    end' ...
        '    if count <= uint32(130)' ...
        '        count = count + uint32(1);' ...
        '    end' ...
        'end' ...
        'if selU < uint32(120)' ...
        '    out = bitErrors(selU + uint32(1));' ...
        'else' ...
        '    out = uint32(0);' ...
        'end'};
    pbeScript = strjoin(pbeLines, sprintf('\n'));

    sfRoot = sfroot;
    emCharts = sfRoot.find('-isa','Stateflow.EMChart');
    found = false;
    for k=1:numel(emCharts)
        if strcmp(emCharts(k).Path, pbe), emCharts(k).Script = pbeScript; found = true; break; end
    end
    if ~found, error('PerBitErrors EMChart not found'); end

    cdb = [rx '/Capture Data Bits'];
    phCdb = get_param(cdb,'PortHandles');
    srcDataOut = get_param(get_param(phCdb.Inport(1),'Line'), 'SrcPortHandle');
    srcDataSrt = get_param(get_param(phCdb.Inport(2),'Line'), 'SrcPortHandle');
    srcValid   = get_param(get_param(phCdb.Inport(4),'Line'), 'SrcPortHandle');
    iqMuxBlk   = [rx '/iq_debug_mux'];
    srcSelPh   = get_param(iqMuxBlk,'PortHandles');
    srcSel     = srcSelPh.Outport(1);

    add_line(rx, srcValid,   get_param(pbe,'PortHandles').Inport(1), 'autorouting','on');
    add_line(rx, srcDataOut, get_param(pbe,'PortHandles').Inport(2), 'autorouting','on');
    add_line(rx, srcDataSrt, get_param(pbe,'PortHandles').Inport(3), 'autorouting','on');
    add_line(rx, srcSel,     get_param(pbe,'PortHandles').Inport(4), 'autorouting','on');

    nRxOut = numel(find_system(rx,'SearchDepth',1,'BlockType','Outport'));
    rxNewOut = [rx '/per_bit_errors_out'];
    add_block('built-in/Outport', rxNewOut, 'Port', num2str(nRxOut+1));
    add_line(rx, get_param(pbe,'PortHandles').Outport(1), get_param(rxNewOut,'PortHandles').Inport(1), 'autorouting','on');

    rxPort = numel(find_system(rx,'SearchDepth',1,'BlockType','Outport'));
    phRxLoop = get_param([loop '/Receiver'],'PortHandles');
    loopNewOut = [loop '/per_bit_errors_out'];
    nLoopOut = numel(find_system(loop,'SearchDepth',1,'BlockType','Outport'));
    add_block('built-in/Outport', loopNewOut, 'Port', num2str(nLoopOut+1));
    add_line(loop, phRxLoop.Outport(rxPort), get_param(loopNewOut,'PortHandles').Inport(1), 'autorouting','on');

    hdlset_param(loopNewOut, 'IOInterface', 'AXI4-Lite');
    hdlset_param(loopNewOut, 'IOInterfaceMapping', 'x"11C"');
    fprintf('V15_perbit_diag insertion complete.\n');
end

save_system(sys,[],'OverwriteIfChangedOnDisk',true);
