% variant_pre_composite_bist_edge_start -- composite_bist_edge_start
%
% Per [[qpsk-7pct-is-packet-misalignment]]:
% 7.27% = 0.145 × 50% — ~14.5% of packets are completely misaligned (start
% signal misses or doubles → 50% errors), 85.5% are correct (0 errors).
%
% Hypothesis: the Capture Data Bits BIST counter's `start` signal sometimes
% pulses for 2+ cycles (instead of exactly 1), causing the inner `if start`
% branch to reset count=1 multiple times → first data bits get OVERWRITTEN
% by the reset → off-by-N alignment → ~50% errors in those packets.
%
% Fix: rewrite the BIST counter MATLAB Function to use RISING-EDGE detection
% on start. Only ONE count=1 reset per leading edge, regardless of pulse width.

sys = 'commhdlQPSKTxRxLoopback';
load_system(sys);

cdb = [sys '/TxRxComposite/Receiver/Capture Data Bits/MATLAB Function'];

% Check if MATLAB Function chart exists at this path
sfRoot = sfroot;
emCharts = sfRoot.find('-isa','Stateflow.EMChart');
foundChart = false;
for k = 1:numel(emCharts)
    if strcmp(emCharts(k).Path, cdb)
        chart = emCharts(k);
        foundChart = true;
        break;
    end
end
assert(foundChart, 'Capture Data Bits MATLAB Function chart not found at %s', cdb);

% Idempotency: check if our marker is already in the script
if contains(chart.Script, 'start_prev')
    fprintf('variant_pre_composite_bist_edge_start: already instrumented, skipping.\n');
    return;
end

% New script with rising-edge detection
newScript = sprintf([ ...
    'function [count_out, packets_out, bit_errors_out] = msgdec(valid, datain, start, stop)\n' ...
    '\n' ...
    'persistent count;\n' ...
    'persistent msgbuffer;\n' ...
    'persistent packetsReceived\n' ...
    'persistent errors;\n' ...
    'persistent start_prev;\n' ...
    '\n' ...
    'if isempty(count) || isempty(msgbuffer) || isempty(packetsReceived)\n' ...
    '    count = uint32(0);\n' ...
    '    msgbuffer = zeros(1,120+8)>0;\n' ...
    '    packetsReceived = uint32(0);\n' ...
    '    errors = uint32(0);\n' ...
    '    start_prev = false;\n' ...
    'end\n' ...
    '\n' ...
    '%% Reference message (BIST golden pattern)\n' ...
    'strAscii = dec2bin(''ADI Hello World'',8);\n' ...
    'msgarray = reshape(strAscii'', [1, numel(strAscii)]);\n' ...
    'msgbits = logical(msgarray - 48);\n' ...
    '\n' ...
    '%% Rising-edge detector on start signal (FIX)\n' ...
    'start_edge = start && ~start_prev;\n' ...
    '\n' ...
    'if valid\n' ...
    '    if start_edge\n' ...
    '        count = uint32(1);\n' ...
    '        packetsReceived = packetsReceived + 1;\n' ...
    '    end\n' ...
    '\n' ...
    '    if count >= uint32(1) && count <= uint32(length(msgbuffer) - 8)\n' ...
    '        msgbuffer(count) = datain;\n' ...
    '        if datain ~= msgbits(count)\n' ...
    '            errors = errors + 1;\n' ...
    '        end\n' ...
    '    end\n' ...
    '\n' ...
    '    if count <= uint32(length(msgbuffer) + 2)\n' ...
    '        count = count + 1;\n' ...
    '    end\n' ...
    'end\n' ...
    '\n' ...
    '%% Update edge detector state every clock (regardless of valid)\n' ...
    'start_prev = start;\n' ...
    '\n' ...
    'count_out = count;\n' ...
    'packets_out = packetsReceived;\n' ...
    'bit_errors_out = errors;\n']);

chart.Script = newScript;
fprintf('Patched Capture Data Bits MATLAB Function with rising-edge start detection\n');

% Patch hdlworkflow_loopback.m for IOInterface mappings (so DMA capture works)
wfFile = 'hdlworkflow_loopback.m';
wfTxt  = fileread(wfFile);
if ~contains(wfTxt, 'variant_pre_composite_bist_edge_start')
    patch = sprintf([ ...
        '%% --- variant_pre_composite_bist_edge_start: route taps to DMA ---\n' ...
        'hdlset_param(''%s/TxRxComposite/debugI'',     ''IOInterface'', ''IP Data 0 OUT [0:15]'');\n' ...
        'hdlset_param(''%s/TxRxComposite/debugI'',     ''IOInterfaceMapping'', ''[0:15]'');\n' ...
        'hdlset_param(''%s/TxRxComposite/debugQ'',     ''IOInterface'', ''IP Data 1 OUT [0:15]'');\n' ...
        'hdlset_param(''%s/TxRxComposite/debugQ'',     ''IOInterfaceMapping'', ''[0:15]'');\n' ...
        'hdlset_param(''%s/TxRxComposite/debugValid'', ''IOInterface'', ''IP Data Valid OUT'');\n' ...
        'hdlset_param(''%s/TxRxComposite/debugValid'', ''IOInterfaceMapping'', ''[0]'');\n' ...
        '%% --- end variant_pre_composite_bist_edge_start ---\n'], sys, sys, sys, sys, sys, sys);
    anchor = sprintf('hdlset_param(''%s/TxRxComposite/bit_errors_out'', ''IOInterfaceMapping'', ''x"108"'');', sys);
    idx = strfind(wfTxt, anchor);
    assert(~isempty(idx), 'anchor not found in %s', wfFile);
    insertAt = idx(1) + numel(anchor);
    if insertAt <= numel(wfTxt) && wfTxt(insertAt) == newline, insertAt = insertAt + 1; end
    newTxt = [wfTxt(1:insertAt-1) sprintf('\n') patch wfTxt(insertAt:end)];
    fid = fopen(wfFile, 'w'); fwrite(fid, newTxt); fclose(fid);
    fprintf('Patched %s with IOInterface mappings\n', wfFile);
end

save_system(sys,[],'OverwriteIfChangedOnDisk',true);
