function r = board_variants
% Board plugin registration file
% 1. Any registration file with this name on MATLAB path will be picked up
% 2. Registration file returns a cell array pointing to the location of
%    the board plugins
% 3. Board plugin must be a package folder accessible from MATLAB path,
%    and contains a board definition file

r = { ...
    'AnalogDevices.fmcomms2.zed.plugin_rd_rx', ...
    'AnalogDevices.fmcomms2.zed.plugin_rd_tx', ...
    ...
    'AnalogDevices.fmcomms2.zc702.plugin_rd_rx', ...
    'AnalogDevices.fmcomms2.zc702.plugin_rd_tx', ...
    ...
    'AnalogDevices.fmcomms2.zc706.plugin_rd_rx', ...
    'AnalogDevices.fmcomms2.zc706.plugin_rd_tx', ...
    ...
    'AnalogDevices.adrv9002.zcu102.plugin_rd_tx'
    };
end
% LocalWords:  Zynq ZC
