cd(fileparts((mfilename('fullpath'))));
p = pwd;

version = '22.1.1';
ml = ver('MATLAB');
ml = ml.Release(2:end-1);
app_name = 'LTEPA';

fprintf('Compiling application to create installer for LTE PA app...\n');
res = compiler.build.standaloneApplication('LTEApp.m',...
    'ExecutableName',app_name,'ExecutableVersion','1.0',...
    'ExecutableSplashScreen', fullfile('img','LTEAPP_splash.png'), ...
    'AdditionalFiles',{fullfile('img','play.png'),...
    fullfile('img','stop.png'),fullfile('img','doc.png'),...
    fullfile('img','refresh.png'),fullfile('img','Analog_Devices_Logo.png'),...
    fullfile('img','grid.png'),fullfile('img','step.png'),...
    fullfile('@LTEAppInternals','lte10_filter_rx.mat'),...
    fullfile('@LTEAppInternals','lte10_filter_tx.mat'),...
    fullfile('@LTEAppInternals','lte15_filter_rx.mat'),...
    fullfile('@LTEAppInternals','lte15_filter_tx.mat'),...
    fullfile('@LTEAppInternals','lte20_filter_rx.mat'),...
    fullfile('@LTEAppInternals','lte20_filter_tx.mat'),...
    fullfile('@LTEAppInternals','lte3_filter_rx.mat'),...
    fullfile('@LTEAppInternals','lte3_filter_tx.mat'),...
    fullfile('@LTEAppInternals','lte5_filter_rx.mat'),...
    fullfile('@LTEAppInternals','lte5_filter_tx.mat'),...
    fullfile('@LTEAppInternals','LTEAppInternals.m'),...
    fullfile('@LTEAppInternals','PlutoRadio.m'),...
    fullfile('@LTETestModelWaveform','DemodSymbs.m'),...
    fullfile('@LTETestModelWaveform','EstimateChannel.m'),...
    fullfile('@LTETestModelWaveform','EVMSubframe.m'),...
    fullfile('@LTETestModelWaveform','frequencyOffsetCellRS.m'),...
    fullfile('@LTETestModelWaveform','getEVMWindow.m'),...
    fullfile('@LTETestModelWaveform','LTETestModelWaveform.m'),...
    fullfile('@LTETestModelWaveform','Sync.m')},...
    'AutoDetectDataFiles','on');


compiler.package.installer(res, ...
    'AuthorCompany', 'Analog Devices Inc.', ...
    'InstallerName', 'LTEPAInstaller');


