# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.runs/system_axi_hpm0_lpd_interconnect_0_synth_1/system_axi_hpm0_lpd_interconnect_0.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "system_axi_hpm0_lpd_interconnect_0_synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_msg_config  -id {Vivado 12-1790}  -string {{Evaluation} {features} {should} {NOT} {be} {used} {in} {production} {systems.}}  -new_severity {WARNING} 
set_msg_config  -id {Designutils 20-3303}  -string {{HDPYFinalizeIO}}  -new_severity {INFO} 
set_msg_config  -id {Place 30-73}  -string {{axi_spi}}  -new_severity {WARNING} 
set_msg_config  -string {{PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY}}  -new_severity {WARNING} 
set_msg_config  -id {BD 41-1343}  -new_severity {WARNING} 
set_msg_config  -id {BD 41-1306}  -new_severity {WARNING} 
set_msg_config  -id {BD 41-1276}  -severity {CRITICAL WARNING}  -new_severity {ERROR} 
set_msg_config  -id {IP_Flow 19-3656}  -new_severity {INFO} 
set_msg_config  -id {IP_Flow 19-4623}  -new_severity {INFO} 
set_msg_config  -id {IP_Flow 19-459}  -new_severity {INFO} 
set_msg_config  -id {Synth 8-3331}  -new_severity {INFO} 
set_msg_config  -id {Synth 8-2490}  -new_severity {WARNING} 
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu3eg-sfva625-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.cache/wt [current_project]
set_property parent.project_path /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/ipcore
  /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/library
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/ipcache [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property generic {USE_RX_CLK_FOR_TX1=0 USE_RX_CLK_FOR_TX2=0} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_ip -quiet /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/system_axi_hpm0_lpd_interconnect_0.xci
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_1/bd_e725_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_2/bd_e725_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_3/bd_e725_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_4/bd_e725_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_5/bd_e725_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_6/bd_e725_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_7/bd_e725_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_8/bd_e725_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_9/bd_e725_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_10/bd_e725_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_11/bd_e725_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_12/bd_e725_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_13/bd_e725_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_14/bd_e725_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_15/bd_e725_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_16/bd_e725_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_17/bd_e725_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_18/bd_e725_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_22/bd_e725_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_23/bd_e725_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_24/bd_e725_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_25/bd_e725_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_26/bd_e725_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_27/bd_e725_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_28/bd_e725_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_29/bd_e725_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_30/bd_e725_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_31/bd_e725_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_32/bd_e725_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_33/bd_e725_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_35/bd_e725_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_36/bd_e725_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_37/bd_e725_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_38/bd_e725_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_39/bd_e725_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_40/bd_e725_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_42/bd_e725_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_43/bd_e725_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_44/bd_e725_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_45/bd_e725_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_46/bd_e725_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_47/bd_e725_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_49/bd_e725_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_50/bd_e725_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_51/bd_e725_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_52/bd_e725_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_53/bd_e725_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_54/bd_e725_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_56/bd_e725_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_57/bd_e725_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_58/bd_e725_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_59/bd_e725_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_60/bd_e725_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_61/bd_e725_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_63/bd_e725_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_64/bd_e725_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_65/bd_e725_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_66/bd_e725_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_67/bd_e725_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_68/bd_e725_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_70/bd_e725_m06s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_71/bd_e725_m06arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_72/bd_e725_m06rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_73/bd_e725_m06awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_74/bd_e725_m06wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_75/bd_e725_m06bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_77/bd_e725_m07s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_78/bd_e725_m07arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_79/bd_e725_m07rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_80/bd_e725_m07awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_81/bd_e725_m07wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/bd_0/ip/ip_82/bd_e725_m07bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/smartconnect.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
OPTRACE "Configure IP Cache" START { }

set cacheID [config_ip_cache -export -no_bom  -dir /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.runs/system_axi_hpm0_lpd_interconnect_0_synth_1 -new_name system_axi_hpm0_lpd_interconnect_0 -ip [get_ips system_axi_hpm0_lpd_interconnect_0]]

OPTRACE "Configure IP Cache" END { }
if { $cacheID == "" } {
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top system_axi_hpm0_lpd_interconnect_0 -part xczu3eg-sfva625-2-e -incremental_mode off -mode out_of_context
OPTRACE "synth_design" END { }
OPTRACE "Write IP Cache" START { }

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix system_axi_hpm0_lpd_interconnect_0_ system_axi_hpm0_lpd_interconnect_0.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ system_axi_hpm0_lpd_interconnect_0_stub.v
 lappend ipCachedFiles system_axi_hpm0_lpd_interconnect_0_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ system_axi_hpm0_lpd_interconnect_0_stub.vhdl
 lappend ipCachedFiles system_axi_hpm0_lpd_interconnect_0_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ system_axi_hpm0_lpd_interconnect_0_sim_netlist.v
 lappend ipCachedFiles system_axi_hpm0_lpd_interconnect_0_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ system_axi_hpm0_lpd_interconnect_0_sim_netlist.vhdl
 lappend ipCachedFiles system_axi_hpm0_lpd_interconnect_0_sim_netlist.vhdl
 set TIME_taken [expr [clock seconds] - $TIME_start]

 if { [get_msg_config -count -severity {CRITICAL WARNING}] == 0 } {
  config_ip_cache -add -dcp system_axi_hpm0_lpd_interconnect_0.dcp -move_files $ipCachedFiles   -synth_runtime $TIME_taken  -ip [get_ips system_axi_hpm0_lpd_interconnect_0]
 }
OPTRACE "Write IP Cache" END { }
}
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all system_axi_hpm0_lpd_interconnect_0_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_axi_hpm0_lpd_interconnect_0.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file system_axi_hpm0_lpd_interconnect_0_utilization_synth.rpt -pb system_axi_hpm0_lpd_interconnect_0_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.runs/system_axi_hpm0_lpd_interconnect_0_synth_1/system_axi_hpm0_lpd_interconnect_0.dcp /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/system_axi_hpm0_lpd_interconnect_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/system_axi_hpm0_lpd_interconnect_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/system_axi_hpm0_lpd_interconnect_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/system_axi_hpm0_lpd_interconnect_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/system_axi_hpm0_lpd_interconnect_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.runs/system_axi_hpm0_lpd_interconnect_0_synth_1/system_axi_hpm0_lpd_interconnect_0.dcp /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/system_axi_hpm0_lpd_interconnect_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.runs/system_axi_hpm0_lpd_interconnect_0_synth_1/system_axi_hpm0_lpd_interconnect_0_stub.v /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/system_axi_hpm0_lpd_interconnect_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.runs/system_axi_hpm0_lpd_interconnect_0_synth_1/system_axi_hpm0_lpd_interconnect_0_stub.vhdl /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/system_axi_hpm0_lpd_interconnect_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.runs/system_axi_hpm0_lpd_interconnect_0_synth_1/system_axi_hpm0_lpd_interconnect_0_sim_netlist.v /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/system_axi_hpm0_lpd_interconnect_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.runs/system_axi_hpm0_lpd_interconnect_0_synth_1/system_axi_hpm0_lpd_interconnect_0_sim_netlist.vhdl /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/system_axi_hpm0_lpd_interconnect_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

close [open .end.used_ip_cache.rst w]
}; # end if cacheID 

if {[file isdir /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.ip_user_files/ip/system_axi_hpm0_lpd_interconnect_0]} {
  catch { 
    file copy -force /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/system_axi_hpm0_lpd_interconnect_0_stub.v /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.ip_user_files/ip/system_axi_hpm0_lpd_interconnect_0
  }
}

if {[file isdir /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.ip_user_files/ip/system_axi_hpm0_lpd_interconnect_0]} {
  catch { 
    file copy -force /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_axi_hpm0_lpd_interconnect_0/system_axi_hpm0_lpd_interconnect_0_stub.vhdl /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.ip_user_files/ip/system_axi_hpm0_lpd_interconnect_0
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "system_axi_hpm0_lpd_interconnect_0_synth_1" END { }
