function hRD = plugin_rd(board, design)
% Reference design definition

%   Copyright 2014-2015 The MathWorks, Inc.

% Construct reference design object
hRD = hdlcoder.ReferenceDesign('SynthesisTool', 'Xilinx Vivado');

% Create the reference design for the SOM-only
% This is the base reference design that other RDs can build upon
hRD.ReferenceDesignName = sprintf('ADRV9364 %s (%s)', upper(board), design);

% Determine the board name based on the design
hRD.BoardName = sprintf('AnalogDevices ADRV9364-Z7020 Frequency Hopping');

% Tool information
hRD.SupportedToolVersion = {'2022.2'};

% DMA Configuration
hRD.addParameter( ...
    'ParameterID',   'dma_config', ...
    'DisplayName',   'DMA Config', ...
    'DefaultValue',  'Stream', ...
    'ParameterType',  hdlcoder.ParameterType.Dropdown, ...
    'Choice',       {'Stream', 'Packetized'});

% Get the root directories
rootDirExample = fileparts(strtok(mfilename('fullpath'), '+'));
tmp = strsplit(rootDirExample,filesep);

if isunix
    rootDir = fullfile(filesep,tmp{1:end-3});
else
    rootDir = fullfile(tmp{1:end-3});
end
rootDirBSP = fullfile('hdl','vendor','AnalogDevices','vivado');

% Design files are shared
hRD.SharedRD = true;
hRD.SharedRDFolder = rootDir;

hRD.addParameter( ...
    'ParameterID',   'project', ...
    'DisplayName',   'HDL Project Subfolder', ...
    'DefaultValue',  'adrv9364z7020');

hRD.addParameter( ...
    'ParameterID',   'carrier', ...
    'DisplayName',   'HDL Project Carrier', ...
    'DefaultValue',  'ccbob_lvds');

hRD.addParameter( ...
    'ParameterID',   'ref_design', ...
    'DisplayName',   'Reference Type', ...
    'DefaultValue',  lower(strrep(design, ' & ','')));

Number_of_inputs = '2';
Number_of_valids = '1';
Data_width = '16';

hRD.addParameter( ...
    'ParameterID',   'number_of_inputs', ...
    'DisplayName',   'Number of Inputs', ...
    'DefaultValue',  Number_of_inputs, ...
	'ParameterType', hdlcoder.ParameterType.Dropdown, ...
	'Choice',        {Number_of_inputs});

hRD.addParameter( ...
    'ParameterID',   'number_of_bits', ...
    'DisplayName',   'Data Width', ...
    'DefaultValue',  Data_width, ...
	'ParameterType', hdlcoder.ParameterType.Dropdown, ...
	'Choice',        {Data_width});

hRD.addParameter( ...
    'ParameterID',   'number_of_valids', ...
    'DisplayName',   'Number of Valid Signals', ...
    'DefaultValue',  Number_of_valids, ...
	'ParameterType', hdlcoder.ParameterType.Dropdown, ...
	'Choice',        {Number_of_valids});

hRD.addParameter( ...
    'ParameterID',   'multiple', ...
    'DisplayName',   'Fast-slow clock ratio', ...
    'DefaultValue',  '1');

hRD.addParameter( ...
    'ParameterID',   'preprocess', ...
    'DisplayName',   'Preprocess', ...
    'DefaultValue',  'on');

hRD.addParameter( ...
    'ParameterID',   'preprocess_script', ...
    'DisplayName',   'Preprocess Script', ...
    'DefaultValue',  fullfile('trx_examples', 'targeting', 'frequency-hopping', 'ccbob_lvds_hop','fh_preprocess.tcl'));

hRD.addParameter( ...
    'ParameterID',   'postprocess', ...
    'DisplayName',   'Postprocess', ...
    'DefaultValue',  'off');

%% Add custom design files
% add custom Vivado design
hRD.addCustomVivadoDesign( ...
    'CustomBlockDesignTcl', fullfile('hdl','vendor','AnalogDevices','vivado','projects','scripts', 'system_project_rxtx.tcl'), ...
    'CustomTopLevelHDL',    fullfile('trx_examples', 'targeting', 'frequency-hopping', 'ccbob_lvds_hop', 'system_top.v'));		


%% Standard reference design pieces
hRD.BlockDesignName = 'system';	
	
% custom constraint files
board_type = strsplit(board,'_');
hRD.CustomConstraints = {...
    fullfile(rootDirBSP, 'projects', 'adrv9364z7020', 'common', strcat(board_type{1}, '_constr.xdc')), ...
	fullfile(rootDirBSP, 'projects', 'adrv9364z7020', 'common', 'adrv9364z7020_constr.xdc'), ...
	fullfile(rootDirBSP, 'projects', 'adrv9364z7020', 'common', strcat('adrv9364z7020_constr_', board_type{2}, '.xdc')), ...
    };

% custom source files
hRD.CustomFiles = {...
	fullfile(rootDirBSP, 'scripts')...,
	fullfile(rootDirBSP, 'library')...,
	fullfile(rootDirBSP, 'library','xilinx')...,
	fullfile(rootDirBSP, 'projects','common')...,
	fullfile(rootDirBSP, 'projects','scripts')...,
	fullfile(rootDirBSP, 'projects','fmcomms2')...,
	fullfile(rootDirBSP, 'projects','adrv9364z7020', 'common')...,
    fullfile(rootDirBSP, 'projects','adrv9364z7020', 'ccbob_lvds')...,
    fullfile('trx_examples', 'targeting', 'frequency-hopping', 'ccbob_lvds_hop')...,
    };	
	
%% Add interfaces
% add clock interface
hRD.addClockInterface( ...
    'ClockConnection',   'util_ad9361_divclk/clk_out', ...
    'ResetConnection',   'util_ad9361_divclk_reset/peripheral_aresetn');
	
