# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_pl_sysmon_0/system_pl_sysmon_0.xci
# IP: The module: 'system_pl_sysmon_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_pl_sysmon_0/system_pl_sysmon_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_pl_sysmon_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_pl_sysmon_0/system_pl_sysmon_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_pl_sysmon_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_pl_sysmon_0/system_pl_sysmon_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_pl_sysmon_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_pl_sysmon_0/system_pl_sysmon_0.xci
# IP: The module: 'system_pl_sysmon_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_pl_sysmon_0/system_pl_sysmon_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_pl_sysmon_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_pl_sysmon_0/system_pl_sysmon_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_pl_sysmon_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tcollins/dev/qpsk_ai/TransceiverToolbox/trx_examples/targeting/QPSKTxRxHDLExample/hdl_prj_jupiter_txrx/vivado_ip_prj/vivado_prj.gen/sources_1/bd/system/ip/system_pl_sysmon_0/system_pl_sysmon_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_pl_sysmon_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
