// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_ThresholdLimiter.v
// Created: 2026-05-26 18:50:49
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_ThresholdLimiter
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/Correlator/ThresholdLimiter
// Hierarchy Level: 5
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_ThresholdLimiter
          (x,
           y);


  input   signed [31:0] x;  // sfix32_En28
  output  signed [31:0] y;  // sfix32_En28




  // Apply a lower limit to the threshold.
  // Threshold is computed by summing across 63 samples.
  // Set lower limit to be equivalent of all 63 samples
  // having their LSB set to 1 and all others set to 0. 
  assign y = (x < 32'sb00000000001010001111010111000010 ? 32'sb00000000001010001111010111000010 :
              x);

endmodule  // Receiver_ip_src_ThresholdLimiter

