// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Receiver_tc.v
// Created: 2026-05-26 18:50:47
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Receiver_tc
// Source Path: Receiver_tc
// Hierarchy Level: 1
// 
// Master clock enable input: clk_enable
// 
// enb_1_1_1   : identical to clk_enable
// enb_1_2_0   : 2x slower than clk with last phase
// enb_1_2_1   : 2x slower than clk with phase 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Receiver_tc
          (clk,
           reset,
           clk_enable,
           enb_1_1_1,
           enb_1_2_0,
           enb_1_2_1);


  input   clk;
  input   reset;
  input   clk_enable;
  output  enb_1_1_1;
  output  enb_1_2_0;
  output  enb_1_2_1;


  reg  count2;  // ufix1
  wire comp_0_tmp;
  wire phase_0_tmp;
  reg  phase_0;
  wire enb_1_2_0_1;
  wire comp_1_tmp;
  wire phase_1_tmp;
  reg  phase_1;
  wire enb_1_2_1_1;


  assign enb_1_1_1 = clk_enable;

  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 1
  always @(posedge clk or posedge reset)
    begin : counter_2_process
      if (reset == 1'b1) begin
        count2 <= 1'b1;
      end
      else begin
        if (clk_enable) begin
          count2 <=  ~ count2;
        end
      end
    end

  assign comp_0_tmp = count2 == 1'b1;

  assign phase_0_tmp = comp_0_tmp & clk_enable;

  always @(posedge clk or posedge reset)
    begin : phase_delay_process
      if (reset == 1'b1) begin
        phase_0 <= 1'b0;
      end
      else begin
        if (clk_enable) begin
          phase_0 <= phase_0_tmp;
        end
      end
    end

  assign enb_1_2_0_1 = phase_0 & clk_enable;

  assign enb_1_2_0 = enb_1_2_0_1;

  assign comp_1_tmp = count2 == 1'b0;

  assign phase_1_tmp = comp_1_tmp & clk_enable;

  always @(posedge clk or posedge reset)
    begin : phase_delay_1_process
      if (reset == 1'b1) begin
        phase_1 <= 1'b1;
      end
      else begin
        if (clk_enable) begin
          phase_1 <= phase_1_tmp;
        end
      end
    end

  assign enb_1_2_1_1 = phase_1 & clk_enable;

  assign enb_1_2_1 = enb_1_2_1_1;

endmodule  // Receiver_ip_src_Receiver_tc

