// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Timing_Adjust.v
// Created: 2026-05-26 18:50:49
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Timing_Adjust
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/Timing Adjust
// Hierarchy Level: 4
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Timing_Adjust
          (clk,
           reset,
           enb_1_2_0,
           timingOffset,
           timingOffsetValid,
           dataIn_re,
           dataIn_im,
           validIn,
           dataOut_re,
           dataOut_im,
           validOut,
           SyncPulse);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   [10:0] timingOffset;  // ufix11
  input   timingOffsetValid;
  input   signed [15:0] dataIn_re;  // sfix16_En14
  input   signed [15:0] dataIn_im;  // sfix16_En14
  input   validIn;
  output  signed [15:0] dataOut_re;  // sfix16_En14
  output  signed [15:0] dataOut_im;  // sfix16_En14
  output  validOut;
  output  SyncPulse;


  reg signed [15:0] Delay4_out1_re;  // sfix16_En14
  reg signed [15:0] Delay4_out1_im;  // sfix16_En14
  reg  Delay3_out1;
  wire [10:0] count_step;  // ufix11
  wire [10:0] count_from;  // ufix11
  reg [10:0] timing_Reference_out1;  // ufix11
  wire [10:0] count;  // ufix11
  wire need_to_wrap;
  wire [10:0] count_value;  // ufix11
  wire [10:0] count_1;  // ufix11
  wire Logical_Operator2_out1;
  reg  Delay2_out1;
  wire Logical_Operator_out1;
  reg  State_Register_out1;
  reg  Delay1_out1;
  wire Logical_Operator1_out1;
  reg [10:0] Unit_Delay_Enabled_Synchronous3_out1;  // ufix11
  wire Relational_Operator_out1;
  reg  Delay_out1;


  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1_re <= 16'sb0000000000000000;
        Delay4_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay4_out1_re <= dataIn_re;
          Delay4_out1_im <= dataIn_im;
        end
      end
    end

  assign dataOut_re = Delay4_out1_re;

  assign dataOut_im = Delay4_out1_im;

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay3_out1 <= validIn;
        end
      end
    end

  assign validOut = Delay3_out1;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 1132
  assign count_step = 11'b00000000001;

  assign count_from = 11'b00000000000;

  assign count = timing_Reference_out1 + count_step;

  assign need_to_wrap = timing_Reference_out1 == 11'b10001101100;

  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);

  assign count_1 = (validIn == 1'b0 ? timing_Reference_out1 :
              count_value);

  always @(posedge clk or posedge reset)
    begin : timing_Reference_process
      if (reset == 1'b1) begin
        timing_Reference_out1 <= 11'b00000000000;
      end
      else begin
        if (enb_1_2_0) begin
          timing_Reference_out1 <= count_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay2_out1 <= Logical_Operator2_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : State_Register_process
      if (reset == 1'b1) begin
        State_Register_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          if (Delay2_out1 == 1'b1) begin
            State_Register_out1 <= 1'b0;
          end
          else begin
            if (Logical_Operator_out1) begin
              State_Register_out1 <= Logical_Operator_out1;
            end
          end
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay1_out1 <= State_Register_out1;
        end
      end
    end

  assign Logical_Operator1_out1 =  ~ Delay1_out1;

  assign Logical_Operator_out1 = timingOffsetValid & Logical_Operator1_out1;

  always @(posedge clk or posedge reset)
    begin : Unit_Delay_Enabled_Synchronous3_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Synchronous3_out1 <= 11'b00000000000;
      end
      else begin
        if (enb_1_2_0 && Logical_Operator_out1) begin
          Unit_Delay_Enabled_Synchronous3_out1 <= timingOffset;
        end
      end
    end

  assign Relational_Operator_out1 = timing_Reference_out1 == Unit_Delay_Enabled_Synchronous3_out1;

  assign Logical_Operator2_out1 = State_Register_out1 & (validIn & Relational_Operator_out1);

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay_out1 <= Logical_Operator2_out1;
        end
      end
    end

  assign SyncPulse = Delay_out1;

endmodule  // Receiver_ip_src_Timing_Adjust

