// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_QPSK_Demodulator_Baseband.v
// Created: 2026-05-26 18:50:49
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_QPSK_Demodulator_Baseband
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/QPSK Demodulator/QPSK Demodulator Baseband
// Hierarchy Level: 3
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_QPSK_Demodulator_Baseband
          (in0_re,
           in0_im,
           out0_0,
           out0_1);


  input   signed [15:0] in0_re;  // sfix16_En14
  input   signed [15:0] in0_im;  // sfix16_En14
  output  out0_0;  // boolean
  output  out0_1;  // boolean


  wire inphase_lt_zero;
  wire inphase_eq_zero;
  wire quadrature_lt_zero;
  wire quadrature_eq_zero;
  wire [3:0] decisionLUTaddr;  // ufix4
  wire [1:0] DirectLookupTable_1 [0:15];  // ufix2 [16]
  wire [1:0] hardDecision;  // ufix2
  wire out0_part0;
  wire out0_part1;


  assign inphase_lt_zero = in0_re < 16'sb0000000000000000;

  assign inphase_eq_zero = in0_re == 16'sb0000000000000000;

  assign quadrature_lt_zero = in0_im < 16'sb0000000000000000;

  assign quadrature_eq_zero = in0_im == 16'sb0000000000000000;

  assign decisionLUTaddr = {inphase_lt_zero, inphase_eq_zero, quadrature_lt_zero, quadrature_eq_zero};

  assign DirectLookupTable_1[0] = 2'b00;
  assign DirectLookupTable_1[1] = 2'b00;
  assign DirectLookupTable_1[2] = 2'b10;
  assign DirectLookupTable_1[3] = 2'b00;
  assign DirectLookupTable_1[4] = 2'b01;
  assign DirectLookupTable_1[5] = 2'b00;
  assign DirectLookupTable_1[6] = 2'b10;
  assign DirectLookupTable_1[7] = 2'b00;
  assign DirectLookupTable_1[8] = 2'b01;
  assign DirectLookupTable_1[9] = 2'b11;
  assign DirectLookupTable_1[10] = 2'b11;
  assign DirectLookupTable_1[11] = 2'b00;
  assign DirectLookupTable_1[12] = 2'b00;
  assign DirectLookupTable_1[13] = 2'b00;
  assign DirectLookupTable_1[14] = 2'b00;
  assign DirectLookupTable_1[15] = 2'b00;
  assign hardDecision = DirectLookupTable_1[decisionLUTaddr];

  assign out0_part0 = hardDecision[1];

  assign out0_0 = out0_part0;

  assign out0_part1 = hardDecision[0];

  assign out0_1 = out0_part1;

endmodule  // Receiver_ip_src_QPSK_Demodulator_Baseband

