// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip.v
// Created: 2026-05-26 18:51:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: -1
// Target subsystem base rate: -1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip
// Source Path: Receiver_ip
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip
          (IPCORE_CLK,
           IPCORE_RESETN,
           dut_data_valid_in_rx,
           dut_data_in_0_rx,
           dut_data_in_1_rx,
           AXI4_Lite_ACLK,
           AXI4_Lite_ARESETN,
           AXI4_Lite_AWADDR,
           AXI4_Lite_AWVALID,
           AXI4_Lite_WDATA,
           AXI4_Lite_WSTRB,
           AXI4_Lite_WVALID,
           AXI4_Lite_BREADY,
           AXI4_Lite_ARADDR,
           AXI4_Lite_ARVALID,
           AXI4_Lite_RREADY,
           dut_data_valid_out_rx,
           dut_data_out_0_rx,
           dut_data_out_1_rx,
           dut_data_out_2_rx,
           dut_data_out_3_rx,
           AXI4_Lite_AWREADY,
           AXI4_Lite_WREADY,
           AXI4_Lite_BRESP,
           AXI4_Lite_BVALID,
           AXI4_Lite_ARREADY,
           AXI4_Lite_RDATA,
           AXI4_Lite_RRESP,
           AXI4_Lite_RVALID);


  input   IPCORE_CLK;  // ufix1
  input   IPCORE_RESETN;  // ufix1
  input   dut_data_valid_in_rx;  // ufix1
  input   [15:0] dut_data_in_0_rx;  // ufix16
  input   [15:0] dut_data_in_1_rx;  // ufix16
  input   AXI4_Lite_ACLK;  // ufix1
  input   AXI4_Lite_ARESETN;  // ufix1
  input   [15:0] AXI4_Lite_AWADDR;  // ufix16
  input   AXI4_Lite_AWVALID;  // ufix1
  input   [31:0] AXI4_Lite_WDATA;  // ufix32
  input   [3:0] AXI4_Lite_WSTRB;  // ufix4
  input   AXI4_Lite_WVALID;  // ufix1
  input   AXI4_Lite_BREADY;  // ufix1
  input   [15:0] AXI4_Lite_ARADDR;  // ufix16
  input   AXI4_Lite_ARVALID;  // ufix1
  input   AXI4_Lite_RREADY;  // ufix1
  output  dut_data_valid_out_rx;  // ufix1
  output  [15:0] dut_data_out_0_rx;  // ufix16
  output  [15:0] dut_data_out_1_rx;  // ufix16
  output  [15:0] dut_data_out_2_rx;  // ufix16
  output  [15:0] dut_data_out_3_rx;  // ufix16
  output  AXI4_Lite_AWREADY;  // ufix1
  output  AXI4_Lite_WREADY;  // ufix1
  output  [1:0] AXI4_Lite_BRESP;  // ufix2
  output  AXI4_Lite_BVALID;  // ufix1
  output  AXI4_Lite_ARREADY;  // ufix1
  output  [31:0] AXI4_Lite_RDATA;  // ufix32
  output  [1:0] AXI4_Lite_RRESP;  // ufix2
  output  AXI4_Lite_RVALID;  // ufix1


  wire reset;
  wire [31:0] ip_timestamp;  // ufix32
  wire reset_cm;  // ufix1
  wire signed [15:0] dataInI_sig;  // sfix16
  wire signed [15:0] dataInQ_sig;  // sfix16
  wire reset_internal;  // ufix1
  wire reset_before_sync;  // ufix1
  wire [31:0] count_out_sig;  // ufix32
  wire [31:0] packets_out_sig;  // ufix32
  wire [31:0] bit_errors_out_sig;  // ufix32
  wire write_axi_enable;  // ufix1
  wire [31:0] write_iq_debug_mux;  // ufix32
  wire write_rstCS;  // ufix1
  wire ce_out_sig;  // ufix1
  wire rxDiagBus_nSynced_sig;  // ufix1
  wire signed [20:0] rxDiagBus_normCoarseFreqEst_sig;  // sfix21_En21
  wire signed [15:0] debugI_sig;  // sfix16
  wire signed [15:0] debugQ_sig;  // sfix16
  wire debugValid_sig;  // ufix1
  wire signed [15:0] debugI1_sig;  // sfix16
  wire signed [15:0] debugQ1_sig;  // sfix16


  assign ip_timestamp = 32'b10011011010010010010010000011011;

  assign reset_cm =  ~ IPCORE_RESETN;

  assign dataInI_sig = dut_data_in_0_rx;

  assign dataInQ_sig = dut_data_in_1_rx;

  assign reset_before_sync = reset_cm | reset_internal;

  Receiver_ip_reset_sync u_Receiver_ip_reset_sync_inst (.clk(IPCORE_CLK),  // ufix1
                                                        .reset_in(reset_before_sync),  // ufix1
                                                        .reset_out(reset)
                                                        );

  Receiver_ip_axi_lite u_Receiver_ip_axi_lite_inst (.reset(reset),
                                                    .AXI4_Lite_ACLK(AXI4_Lite_ACLK),  // ufix1
                                                    .AXI4_Lite_ARESETN(AXI4_Lite_ARESETN),  // ufix1
                                                    .AXI4_Lite_AWADDR(AXI4_Lite_AWADDR),  // ufix16
                                                    .AXI4_Lite_AWVALID(AXI4_Lite_AWVALID),  // ufix1
                                                    .AXI4_Lite_WDATA(AXI4_Lite_WDATA),  // ufix32
                                                    .AXI4_Lite_WSTRB(AXI4_Lite_WSTRB),  // ufix4
                                                    .AXI4_Lite_WVALID(AXI4_Lite_WVALID),  // ufix1
                                                    .AXI4_Lite_BREADY(AXI4_Lite_BREADY),  // ufix1
                                                    .AXI4_Lite_ARADDR(AXI4_Lite_ARADDR),  // ufix16
                                                    .AXI4_Lite_ARVALID(AXI4_Lite_ARVALID),  // ufix1
                                                    .AXI4_Lite_RREADY(AXI4_Lite_RREADY),  // ufix1
                                                    .read_ip_timestamp(ip_timestamp),  // ufix32
                                                    .read_count_out(count_out_sig),  // ufix32
                                                    .read_packets_out(packets_out_sig),  // ufix32
                                                    .read_bit_errors_out(bit_errors_out_sig),  // ufix32
                                                    .AXI4_Lite_AWREADY(AXI4_Lite_AWREADY),  // ufix1
                                                    .AXI4_Lite_WREADY(AXI4_Lite_WREADY),  // ufix1
                                                    .AXI4_Lite_BRESP(AXI4_Lite_BRESP),  // ufix2
                                                    .AXI4_Lite_BVALID(AXI4_Lite_BVALID),  // ufix1
                                                    .AXI4_Lite_ARREADY(AXI4_Lite_ARREADY),  // ufix1
                                                    .AXI4_Lite_RDATA(AXI4_Lite_RDATA),  // ufix32
                                                    .AXI4_Lite_RRESP(AXI4_Lite_RRESP),  // ufix2
                                                    .AXI4_Lite_RVALID(AXI4_Lite_RVALID),  // ufix1
                                                    .write_axi_enable(write_axi_enable),  // ufix1
                                                    .write_iq_debug_mux(write_iq_debug_mux),  // ufix32
                                                    .write_rstCS(write_rstCS),  // ufix1
                                                    .reset_internal(reset_internal)  // ufix1
                                                    );

  Receiver_ip_dut u_Receiver_ip_dut_inst (.clk(IPCORE_CLK),  // ufix1
                                          .reset(reset),
                                          .dut_enable(write_axi_enable),  // ufix1
                                          .validIn(dut_data_valid_in_rx),  // ufix1
                                          .dataInI(dataInI_sig),  // sfix16
                                          .dataInQ(dataInQ_sig),  // sfix16
                                          .rstCS(write_rstCS),  // ufix1
                                          .iq_debug_mux(write_iq_debug_mux),  // ufix32
                                          .ce_out(ce_out_sig),  // ufix1
                                          .rxDiagBus_nSynced(rxDiagBus_nSynced_sig),  // ufix1
                                          .rxDiagBus_normCoarseFreqEst(rxDiagBus_normCoarseFreqEst_sig),  // sfix21_En21
                                          .count_out(count_out_sig),  // ufix32
                                          .packets_out(packets_out_sig),  // ufix32
                                          .bit_errors_out(bit_errors_out_sig),  // ufix32
                                          .debugI(debugI_sig),  // sfix16
                                          .debugQ(debugQ_sig),  // sfix16
                                          .debugValid(debugValid_sig),  // ufix1
                                          .debugI1(debugI1_sig),  // sfix16
                                          .debugQ1(debugQ1_sig)  // sfix16
                                          );

  assign dut_data_valid_out_rx = debugValid_sig;

  assign dut_data_out_0_rx = debugI_sig;

  assign dut_data_out_1_rx = debugQ_sig;

  assign dut_data_out_2_rx = debugI1_sig;

  assign dut_data_out_3_rx = debugQ1_sig;

endmodule  // Receiver_ip

