// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Quadrant_Mapper_block.v
// Created: 2026-05-26 18:50:48
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Quadrant_Mapper_block
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Phase Ambiguity Estimation and Correction/Phase 
// Ambiguity Corrector/HDL_CMA_core/Quadrant_Mappe
// Hierarchy Level: 6
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Quadrant_Mapper_block
          (clk,
           reset,
           enb_1_2_0,
           xin,
           yin,
           xout,
           yout);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [12:0] xin;  // sfix13_En10
  input   signed [12:0] yin;  // sfix13_En10
  output  signed [12:0] xout;  // sfix13_En10
  output  signed [12:0] yout;  // sfix13_En10


  wire signed [13:0] abs_y;  // sfix14_En10
  wire signed [13:0] abs_cast;  // sfix14_En10
  wire signed [12:0] xAbs;  // sfix13_En10
  reg signed [12:0] xAbsReg;  // sfix13_En10
  wire signed [13:0] abs_y_1;  // sfix14_En10
  wire signed [13:0] abs_cast_1;  // sfix14_En10
  wire signed [12:0] yAbs;  // sfix13_En10
  reg signed [12:0] yAbsReg;  // sfix13_En10
  wire XGreaterThanY;  // ufix1
  wire signed [12:0] xout_1;  // sfix13_En10
  wire signed [12:0] yout_1;  // sfix13_En10


  assign abs_cast = {xin[12], xin};
  assign abs_y = (xin < 13'sb0000000000000 ?  - (abs_cast) :
              {xin[12], xin});
  assign xAbs = abs_y[12:0];

  always @(posedge clk or posedge reset)
    begin : DelayxAbs_process
      if (reset == 1'b1) begin
        xAbsReg <= 13'sb0000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xAbsReg <= xAbs;
        end
      end
    end

  assign abs_cast_1 = {yin[12], yin};
  assign abs_y_1 = (yin < 13'sb0000000000000 ?  - (abs_cast_1) :
              {yin[12], yin});
  assign yAbs = abs_y_1[12:0];

  always @(posedge clk or posedge reset)
    begin : DelayyAbs_process
      if (reset == 1'b1) begin
        yAbsReg <= 13'sb0000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yAbsReg <= yAbs;
        end
      end
    end

  assign XGreaterThanY = xAbsReg > yAbsReg;

  assign xout_1 = (XGreaterThanY == 1'b0 ? yAbsReg :
              xAbsReg);

  assign xout = xout_1;

  assign yout_1 = (XGreaterThanY == 1'b0 ? xAbsReg :
              yAbsReg);

  assign yout = yout_1;

endmodule  // Receiver_ip_src_Quadrant_Mapper_block

