// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Coarse_Frequency_Compensator.v
// Created: 2026-05-26 18:50:48
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Coarse_Frequency_Compensator
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Coarse Frequency Compensator
// Hierarchy Level: 3
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Coarse_Frequency_Compensator
          (clk,
           reset,
           enb_1_2_0,
           dataIn_re,
           dataIn_im,
           validIn,
           dataOut_re,
           dataOut_im,
           rstCS,
           validOut,
           normalizedFreqEst);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [15:0] dataIn_re;  // sfix16_En14
  input   signed [15:0] dataIn_im;  // sfix16_En14
  input   validIn;
  output  signed [15:0] dataOut_re;  // sfix16_En14
  output  signed [15:0] dataOut_im;  // sfix16_En14
  output  rstCS;
  output  validOut;
  output  signed [20:0] normalizedFreqEst;  // sfix21_En21


  reg signed [15:0] Delay5_out1_re;  // sfix16_En14
  reg signed [15:0] Delay5_out1_im;  // sfix16_En14
  reg signed [15:0] Delay1_reg_re [0:8];  // sfix16_En14 [9]
  reg signed [15:0] Delay1_reg_im [0:8];  // sfix16_En14 [9]
  reg signed [15:0] Delay1_reg_next_re [0:8];  // sfix16_En14 [9]
  reg signed [15:0] Delay1_reg_next_im [0:8];  // sfix16_En14 [9]
  reg signed [15:0] Delay1_out1_re;  // sfix16_En14
  reg signed [15:0] Delay1_out1_im;  // sfix16_En14
  reg signed [15:0] Delay7_reg_re [0:11];  // sfix16_En14 [12]
  reg signed [15:0] Delay7_reg_im [0:11];  // sfix16_En14 [12]
  reg signed [15:0] Delay7_reg_next_re [0:11];  // sfix16_En14 [12]
  reg signed [15:0] Delay7_reg_next_im [0:11];  // sfix16_En14 [12]
  reg signed [15:0] Delay7_out1_re;  // sfix16_En14
  reg signed [15:0] Delay7_out1_im;  // sfix16_En14
  reg signed [15:0] Delay3_reg_re [0:5];  // sfix16_En14 [6]
  reg signed [15:0] Delay3_reg_im [0:5];  // sfix16_En14 [6]
  reg signed [15:0] Delay3_reg_next_re [0:5];  // sfix16_En14 [6]
  reg signed [15:0] Delay3_reg_next_im [0:5];  // sfix16_En14 [6]
  reg signed [15:0] Delay3_out1_re;  // sfix16_En14
  reg signed [15:0] Delay3_out1_im;  // sfix16_En14
  reg signed [15:0] Delay11_reg_re [0:1];  // sfix16_En14 [2]
  reg signed [15:0] Delay11_reg_im [0:1];  // sfix16_En14 [2]
  wire signed [15:0] Delay11_reg_next_re [0:1];  // sfix16_En14 [2]
  wire signed [15:0] Delay11_reg_next_im [0:1];  // sfix16_En14 [2]
  wire signed [15:0] Delay11_out1_re;  // sfix16_En14
  wire signed [15:0] Delay11_out1_im;  // sfix16_En14
  wire signed [15:0] Data_Type_Conversion2_out1_re;  // sfix16_En12
  wire signed [15:0] Data_Type_Conversion2_out1_im;  // sfix16_En12
  reg  Delay6_out1;
  wire signed [15:0] Raise_Power_to_4_dataOut_re;  // sfix16_En12
  wire signed [15:0] Raise_Power_to_4_dataOut_im;  // sfix16_En12
  wire Raise_Power_to_4_validOut;
  wire signed [34:0] Coarse_Frequency_Estimator_normFreqEst;  // sfix35_En34
  wire signed [37:0] Gain_cast;  // sfix38_En36
  wire signed [36:0] Gain_cast_1;  // sfix37_En36
  wire signed [34:0] Gain_out1;  // sfix35_En34
  wire signed [20:0] Data_Type_Conversion3_out1;  // sfix21_En21
  wire signed [20:0] Data_Type_Conversion4_out1;  // sfix21
  reg  [8:0] Delay2_reg;  // ufix1 [9]
  wire Delay2_out1;
  reg  [11:0] Delay8_reg;  // ufix1 [12]
  wire Delay8_out1;
  wire signed [15:0] NCO_out1_re;  // sfix16_En14
  wire signed [15:0] NCO_out1_im;  // sfix16_En14
  wire signed [16:0] conj_cast;  // sfix17_En14
  wire signed [16:0] conj_cast_1;  // sfix17_En14
  wire signed [15:0] Math_Function_out1_re;  // sfix16_En14
  wire signed [15:0] Math_Function_out1_im;  // sfix16_En14
  reg signed [15:0] Delay12_reg_re [0:1];  // sfix16_En14 [2]
  reg signed [15:0] Delay12_reg_im [0:1];  // sfix16_En14 [2]
  wire signed [15:0] Delay12_reg_next_re [0:1];  // sfix16_En14 [2]
  wire signed [15:0] Delay12_reg_next_im [0:1];  // sfix16_En14 [2]
  wire signed [15:0] Delay12_out1_re;  // sfix16_En14
  wire signed [15:0] Delay12_out1_im;  // sfix16_En14
  wire signed [31:0] Product1_mul_temp;  // sfix32_En28
  wire signed [15:0] Product1_sub_cast;  // sfix16_En14
  wire signed [31:0] Product1_mul_temp_1;  // sfix32_En28
  wire signed [15:0] Product1_sub_cast_1;  // sfix16_En14
  wire signed [31:0] Product1_mul_temp_2;  // sfix32_En28
  wire signed [15:0] Product1_add_cast;  // sfix16_En14
  wire signed [31:0] Product1_mul_temp_3;  // sfix32_En28
  wire signed [15:0] Product1_add_cast_1;  // sfix16_En14
  wire signed [15:0] Product1_out1_re;  // sfix16_En14
  wire signed [15:0] Product1_out1_im;  // sfix16_En14
  reg signed [15:0] Delay13_reg_re [0:1];  // sfix16_En14 [2]
  reg signed [15:0] Delay13_reg_im [0:1];  // sfix16_En14 [2]
  wire signed [15:0] Delay13_reg_next_re [0:1];  // sfix16_En14 [2]
  wire signed [15:0] Delay13_reg_next_im [0:1];  // sfix16_En14 [2]
  wire signed [15:0] Delay13_out1_re;  // sfix16_En14
  wire signed [15:0] Delay13_out1_im;  // sfix16_En14
  wire CFO_step_change_detector_Out1;
  reg  [1:0] Delay16_reg;  // ufix1 [2]
  wire Delay16_out1;
  reg  [1:0] Delay17_reg;  // ufix1 [2]
  wire Delay17_out1;
  reg  [5:0] Delay4_reg;  // ufix1 [6]
  wire Delay4_out1;
  reg  [1:0] Delay14_reg;  // ufix1 [2]
  wire Delay14_out1;
  reg  [1:0] Delay15_reg;  // ufix1 [2]
  wire Delay15_out1;
  reg signed [31:0] Delay1_t_0_0;  // int32
  reg signed [31:0] Delay1_t_0_1;  // int32
  reg signed [31:0] Delay1_t_1;  // int32
  reg signed [31:0] Delay7_t_0_0;  // int32
  reg signed [31:0] Delay7_t_0_1;  // int32
  reg signed [31:0] Delay7_t_1;  // int32
  reg signed [31:0] Delay3_t_0_0;  // int32
  reg signed [31:0] Delay3_t_0_1;  // int32
  reg signed [31:0] Delay3_t_1;  // int32
  reg signed [31:0] Delay11_t_0_0;  // int32
  reg signed [31:0] Delay11_t_1;  // int32
  reg signed [31:0] Delay12_t_0_0;  // int32
  reg signed [31:0] Delay12_t_1;  // int32
  reg signed [31:0] Delay13_t_0_0;  // int32
  reg signed [31:0] Delay13_t_1;  // int32


  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1_re <= 16'sb0000000000000000;
        Delay5_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay5_out1_re <= dataIn_re;
          Delay5_out1_im <= dataIn_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        for(Delay1_t_1 = 32'sd0; Delay1_t_1 <= 32'sd8; Delay1_t_1 = Delay1_t_1 + 32'sd1) begin
          Delay1_reg_re[Delay1_t_1] <= 16'sb0000000000000000;
          Delay1_reg_im[Delay1_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay1_t_0_1 = 32'sd0; Delay1_t_0_1 <= 32'sd8; Delay1_t_0_1 = Delay1_t_0_1 + 32'sd1) begin
            Delay1_reg_re[Delay1_t_0_1] <= Delay1_reg_next_re[Delay1_t_0_1];
            Delay1_reg_im[Delay1_t_0_1] <= Delay1_reg_next_im[Delay1_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay1_out1_re = Delay1_reg_re[8];
    Delay1_out1_im = Delay1_reg_im[8];
    Delay1_reg_next_re[0] = Delay5_out1_re;
    Delay1_reg_next_im[0] = Delay5_out1_im;

    for(Delay1_t_0_0 = 32'sd0; Delay1_t_0_0 <= 32'sd7; Delay1_t_0_0 = Delay1_t_0_0 + 32'sd1) begin
      Delay1_reg_next_re[Delay1_t_0_0 + 32'sd1] = Delay1_reg_re[Delay1_t_0_0];
      Delay1_reg_next_im[Delay1_t_0_0 + 32'sd1] = Delay1_reg_im[Delay1_t_0_0];
    end

  end

  always @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        for(Delay7_t_1 = 32'sd0; Delay7_t_1 <= 32'sd11; Delay7_t_1 = Delay7_t_1 + 32'sd1) begin
          Delay7_reg_re[Delay7_t_1] <= 16'sb0000000000000000;
          Delay7_reg_im[Delay7_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay7_t_0_1 = 32'sd0; Delay7_t_0_1 <= 32'sd11; Delay7_t_0_1 = Delay7_t_0_1 + 32'sd1) begin
            Delay7_reg_re[Delay7_t_0_1] <= Delay7_reg_next_re[Delay7_t_0_1];
            Delay7_reg_im[Delay7_t_0_1] <= Delay7_reg_next_im[Delay7_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay7_out1_re = Delay7_reg_re[11];
    Delay7_out1_im = Delay7_reg_im[11];
    Delay7_reg_next_re[0] = Delay1_out1_re;
    Delay7_reg_next_im[0] = Delay1_out1_im;

    for(Delay7_t_0_0 = 32'sd0; Delay7_t_0_0 <= 32'sd10; Delay7_t_0_0 = Delay7_t_0_0 + 32'sd1) begin
      Delay7_reg_next_re[Delay7_t_0_0 + 32'sd1] = Delay7_reg_re[Delay7_t_0_0];
      Delay7_reg_next_im[Delay7_t_0_0 + 32'sd1] = Delay7_reg_im[Delay7_t_0_0];
    end

  end

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        for(Delay3_t_1 = 32'sd0; Delay3_t_1 <= 32'sd5; Delay3_t_1 = Delay3_t_1 + 32'sd1) begin
          Delay3_reg_re[Delay3_t_1] <= 16'sb0000000000000000;
          Delay3_reg_im[Delay3_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay3_t_0_1 = 32'sd0; Delay3_t_0_1 <= 32'sd5; Delay3_t_0_1 = Delay3_t_0_1 + 32'sd1) begin
            Delay3_reg_re[Delay3_t_0_1] <= Delay3_reg_next_re[Delay3_t_0_1];
            Delay3_reg_im[Delay3_t_0_1] <= Delay3_reg_next_im[Delay3_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay3_out1_re = Delay3_reg_re[5];
    Delay3_out1_im = Delay3_reg_im[5];
    Delay3_reg_next_re[0] = Delay7_out1_re;
    Delay3_reg_next_im[0] = Delay7_out1_im;

    for(Delay3_t_0_0 = 32'sd0; Delay3_t_0_0 <= 32'sd4; Delay3_t_0_0 = Delay3_t_0_0 + 32'sd1) begin
      Delay3_reg_next_re[Delay3_t_0_0 + 32'sd1] = Delay3_reg_re[Delay3_t_0_0];
      Delay3_reg_next_im[Delay3_t_0_0 + 32'sd1] = Delay3_reg_im[Delay3_t_0_0];
    end

  end

  always @(posedge clk or posedge reset)
    begin : Delay11_process
      if (reset == 1'b1) begin
        for(Delay11_t_1 = 32'sd0; Delay11_t_1 <= 32'sd1; Delay11_t_1 = Delay11_t_1 + 32'sd1) begin
          Delay11_reg_re[Delay11_t_1] <= 16'sb0000000000000000;
          Delay11_reg_im[Delay11_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay11_t_0_0 = 32'sd0; Delay11_t_0_0 <= 32'sd1; Delay11_t_0_0 = Delay11_t_0_0 + 32'sd1) begin
            Delay11_reg_re[Delay11_t_0_0] <= Delay11_reg_next_re[Delay11_t_0_0];
            Delay11_reg_im[Delay11_t_0_0] <= Delay11_reg_next_im[Delay11_t_0_0];
          end
        end
      end
    end

  assign Delay11_out1_re = Delay11_reg_re[1];
  assign Delay11_out1_im = Delay11_reg_im[1];
  assign Delay11_reg_next_re[0] = Delay3_out1_re;
  assign Delay11_reg_next_im[0] = Delay3_out1_im;
  assign Delay11_reg_next_re[1] = Delay11_reg_re[0];
  assign Delay11_reg_next_im[1] = Delay11_reg_im[0];

  assign Data_Type_Conversion2_out1_re = {{2{Delay5_out1_re[15]}}, Delay5_out1_re[15:2]};
  assign Data_Type_Conversion2_out1_im = {{2{Delay5_out1_im[15]}}, Delay5_out1_im[15:2]};

  always @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay6_out1 <= validIn;
        end
      end
    end

  Receiver_ip_src_Raise_Power_to_4 u_Raise_Power_to_4 (.clk(clk),
                                                       .reset(reset),
                                                       .enb_1_2_0(enb_1_2_0),
                                                       .dataIn_re(Data_Type_Conversion2_out1_re),  // sfix16_En12
                                                       .dataIn_im(Data_Type_Conversion2_out1_im),  // sfix16_En12
                                                       .validIn(Delay6_out1),
                                                       .dataOut_re(Raise_Power_to_4_dataOut_re),  // sfix16_En12
                                                       .dataOut_im(Raise_Power_to_4_dataOut_im),  // sfix16_En12
                                                       .validOut(Raise_Power_to_4_validOut)
                                                       );

  Receiver_ip_src_Coarse_Frequency_Estimator u_Coarse_Frequency_Estimator (.clk(clk),
                                                                           .reset(reset),
                                                                           .enb_1_2_0(enb_1_2_0),
                                                                           .dataIn_re(Raise_Power_to_4_dataOut_re),  // sfix16_En12
                                                                           .dataIn_im(Raise_Power_to_4_dataOut_im),  // sfix16_En12
                                                                           .validIn(Raise_Power_to_4_validOut),
                                                                           .normFreqEst(Coarse_Frequency_Estimator_normFreqEst)  // sfix35_En34
                                                                           );

  assign Gain_cast = {{3{Coarse_Frequency_Estimator_normFreqEst[34]}}, Coarse_Frequency_Estimator_normFreqEst};
  assign Gain_cast_1 = Gain_cast[36:0];
  assign Gain_out1 = Gain_cast_1[36:2];

  assign Data_Type_Conversion3_out1 = Gain_out1[33:13];

  assign Data_Type_Conversion4_out1 = Data_Type_Conversion3_out1;

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_reg <= {9{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay2_reg[0] <= Delay6_out1;
          Delay2_reg[32'sd8:32'sd1] <= Delay2_reg[32'sd7:32'sd0];
        end
      end
    end

  assign Delay2_out1 = Delay2_reg[8];

  always @(posedge clk or posedge reset)
    begin : Delay8_process
      if (reset == 1'b1) begin
        Delay8_reg <= {12{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay8_reg[0] <= Delay2_out1;
          Delay8_reg[32'sd11:32'sd1] <= Delay8_reg[32'sd10:32'sd0];
        end
      end
    end

  assign Delay8_out1 = Delay8_reg[11];

  Receiver_ip_src_NCO_block u_NCO (.clk(clk),
                                   .reset(reset),
                                   .enb_1_2_0(enb_1_2_0),
                                   .inc(Data_Type_Conversion4_out1),  // sfix21
                                   .validIn(Delay8_out1),
                                   .complexexp_re(NCO_out1_re),  // sfix16_En14
                                   .complexexp_im(NCO_out1_im)  // sfix16_En14
                                   );

  assign Math_Function_out1_re = NCO_out1_re;
  assign conj_cast = {NCO_out1_im[15], NCO_out1_im};
  assign conj_cast_1 =  - (conj_cast);
  assign Math_Function_out1_im = ((conj_cast_1[16] == 1'b0) && (conj_cast_1[15] != 1'b0) ? 16'sb0111111111111111 :
              ((conj_cast_1[16] == 1'b1) && (conj_cast_1[15] != 1'b1) ? 16'sb1000000000000000 :
              $signed(conj_cast_1[15:0])));

  always @(posedge clk or posedge reset)
    begin : Delay12_process
      if (reset == 1'b1) begin
        for(Delay12_t_1 = 32'sd0; Delay12_t_1 <= 32'sd1; Delay12_t_1 = Delay12_t_1 + 32'sd1) begin
          Delay12_reg_re[Delay12_t_1] <= 16'sb0000000000000000;
          Delay12_reg_im[Delay12_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay12_t_0_0 = 32'sd0; Delay12_t_0_0 <= 32'sd1; Delay12_t_0_0 = Delay12_t_0_0 + 32'sd1) begin
            Delay12_reg_re[Delay12_t_0_0] <= Delay12_reg_next_re[Delay12_t_0_0];
            Delay12_reg_im[Delay12_t_0_0] <= Delay12_reg_next_im[Delay12_t_0_0];
          end
        end
      end
    end

  assign Delay12_out1_re = Delay12_reg_re[1];
  assign Delay12_out1_im = Delay12_reg_im[1];
  assign Delay12_reg_next_re[0] = Math_Function_out1_re;
  assign Delay12_reg_next_im[0] = Math_Function_out1_im;
  assign Delay12_reg_next_re[1] = Delay12_reg_re[0];
  assign Delay12_reg_next_im[1] = Delay12_reg_im[0];

  assign Product1_mul_temp = Delay11_out1_re * Delay12_out1_re;
  assign Product1_sub_cast = Product1_mul_temp[29:14];
  assign Product1_mul_temp_1 = Delay11_out1_im * Delay12_out1_im;
  assign Product1_sub_cast_1 = Product1_mul_temp_1[29:14];
  assign Product1_out1_re = Product1_sub_cast - Product1_sub_cast_1;
  assign Product1_mul_temp_2 = Delay11_out1_im * Delay12_out1_re;
  assign Product1_add_cast = Product1_mul_temp_2[29:14];
  assign Product1_mul_temp_3 = Delay11_out1_re * Delay12_out1_im;
  assign Product1_add_cast_1 = Product1_mul_temp_3[29:14];
  assign Product1_out1_im = Product1_add_cast + Product1_add_cast_1;

  always @(posedge clk or posedge reset)
    begin : Delay13_process
      if (reset == 1'b1) begin
        for(Delay13_t_1 = 32'sd0; Delay13_t_1 <= 32'sd1; Delay13_t_1 = Delay13_t_1 + 32'sd1) begin
          Delay13_reg_re[Delay13_t_1] <= 16'sb0000000000000000;
          Delay13_reg_im[Delay13_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay13_t_0_0 = 32'sd0; Delay13_t_0_0 <= 32'sd1; Delay13_t_0_0 = Delay13_t_0_0 + 32'sd1) begin
            Delay13_reg_re[Delay13_t_0_0] <= Delay13_reg_next_re[Delay13_t_0_0];
            Delay13_reg_im[Delay13_t_0_0] <= Delay13_reg_next_im[Delay13_t_0_0];
          end
        end
      end
    end

  assign Delay13_out1_re = Delay13_reg_re[1];
  assign Delay13_out1_im = Delay13_reg_im[1];
  assign Delay13_reg_next_re[0] = Product1_out1_re;
  assign Delay13_reg_next_im[0] = Product1_out1_im;
  assign Delay13_reg_next_re[1] = Delay13_reg_re[0];
  assign Delay13_reg_next_im[1] = Delay13_reg_im[0];

  assign dataOut_re = Delay13_out1_re;

  assign dataOut_im = Delay13_out1_im;

  Receiver_ip_src_CFO_step_change_detector u_CFO_step_change_detector (.clk(clk),
                                                                       .reset(reset),
                                                                       .enb_1_2_0(enb_1_2_0),
                                                                       .In1(Data_Type_Conversion3_out1),  // sfix21_En21
                                                                       .Out1(CFO_step_change_detector_Out1)
                                                                       );

  always @(posedge clk or posedge reset)
    begin : Delay16_process
      if (reset == 1'b1) begin
        Delay16_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay16_reg[0] <= CFO_step_change_detector_Out1;
          Delay16_reg[1] <= Delay16_reg[0];
        end
      end
    end

  assign Delay16_out1 = Delay16_reg[1];

  always @(posedge clk or posedge reset)
    begin : Delay17_process
      if (reset == 1'b1) begin
        Delay17_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay17_reg[0] <= Delay16_out1;
          Delay17_reg[1] <= Delay17_reg[0];
        end
      end
    end

  assign Delay17_out1 = Delay17_reg[1];

  assign rstCS = Delay17_out1;

  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_reg <= {6{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay4_reg[0] <= Delay8_out1;
          Delay4_reg[32'sd5:32'sd1] <= Delay4_reg[32'sd4:32'sd0];
        end
      end
    end

  assign Delay4_out1 = Delay4_reg[5];

  always @(posedge clk or posedge reset)
    begin : Delay14_process
      if (reset == 1'b1) begin
        Delay14_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay14_reg[0] <= Delay4_out1;
          Delay14_reg[1] <= Delay14_reg[0];
        end
      end
    end

  assign Delay14_out1 = Delay14_reg[1];

  always @(posedge clk or posedge reset)
    begin : Delay15_process
      if (reset == 1'b1) begin
        Delay15_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay15_reg[0] <= Delay14_out1;
          Delay15_reg[1] <= Delay15_reg[0];
        end
      end
    end

  assign Delay15_out1 = Delay15_reg[1];

  assign validOut = Delay15_out1;

  assign normalizedFreqEst = Data_Type_Conversion3_out1;

endmodule  // Receiver_ip_src_Coarse_Frequency_Compensator

