// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Integrator.v
// Created: 2026-05-26 18:50:47
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Integrator
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Coarse Frequency Compensator/Coarse 
// Frequency Estimator/Integrato
// Hierarchy Level: 5
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Integrator
          (clk,
           reset,
           enb_1_2_0,
           dataIn_re,
           dataIn_im,
           validIn,
           IntegOut_re,
           IntegOut_im,
           IntegValid);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [31:0] dataIn_re;  // sfix32_En24
  input   signed [31:0] dataIn_im;  // sfix32_En24
  input   validIn;
  output  signed [31:0] IntegOut_re;  // sfix32_En24
  output  signed [31:0] IntegOut_im;  // sfix32_En24
  output  IntegValid;


  wire Reset_Generator_reset;
  reg  Delay2_out1;
  reg signed [31:0] Delay1_out1_re;  // sfix32_En24
  reg signed [31:0] Delay1_out1_im;  // sfix32_En24
  reg signed [31:0] Integ_Reg_out1_re;  // sfix32_En24
  reg signed [31:0] Integ_Reg_out1_im;  // sfix32_En24
  wire signed [31:0] Add1_out1_re;  // sfix32_En24
  wire signed [31:0] Add1_out1_im;  // sfix32_En24
  reg signed [31:0] Store_Reg_out1_re;  // sfix32_En24
  reg signed [31:0] Store_Reg_out1_im;  // sfix32_En24
  reg  Delay_out1;

  // store the value in the Reg before reset


  Receiver_ip_src_Reset_Generator u_Reset_Generator (.clk(clk),
                                                     .reset(reset),
                                                     .enb_1_2_0(enb_1_2_0),
                                                     .validIn(validIn),
                                                     .reset_1(Reset_Generator_reset)
                                                     );

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay2_out1 <= validIn;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1_re <= 32'sb00000000000000000000000000000000;
        Delay1_out1_im <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay1_out1_re <= dataIn_re;
          Delay1_out1_im <= dataIn_im;
        end
      end
    end

  assign Add1_out1_re = Delay1_out1_re + Integ_Reg_out1_re;
  assign Add1_out1_im = Delay1_out1_im + Integ_Reg_out1_im;

  always @(posedge clk or posedge reset)
    begin : Integ_Reg_process
      if (reset == 1'b1) begin
        Integ_Reg_out1_re <= 32'sb00000000000000000000000000000000;
        Integ_Reg_out1_im <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          if (Reset_Generator_reset == 1'b1) begin
            Integ_Reg_out1_re <= 32'sb00000000000000000000000000000000;
            Integ_Reg_out1_im <= 32'sb00000000000000000000000000000000;
          end
          else begin
            if (Delay2_out1) begin
              Integ_Reg_out1_re <= Add1_out1_re;
              Integ_Reg_out1_im <= Add1_out1_im;
            end
          end
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Store_Reg_process
      if (reset == 1'b1) begin
        Store_Reg_out1_re <= 32'sb00000000000000000000000000000000;
        Store_Reg_out1_im <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0 && Reset_Generator_reset) begin
          Store_Reg_out1_re <= Integ_Reg_out1_re;
          Store_Reg_out1_im <= Integ_Reg_out1_im;
        end
      end
    end

  assign IntegOut_re = Store_Reg_out1_re;

  assign IntegOut_im = Store_Reg_out1_im;

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay_out1 <= Reset_Generator_reset;
        end
      end
    end

  assign IntegValid = Delay_out1;

endmodule  // Receiver_ip_src_Integrator

