// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_FilterCoef_block1.v
// Created: 2026-05-26 18:50:49
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_FilterCoef_block1
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/Correlator/Discrete 
// FIR Filter/Filter/FilterCoe
// Hierarchy Level: 7
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_FilterCoef_block1
          (CoefOutI_0,
           CoefOutI_1,
           CoefOutI_2,
           CoefOutI_3,
           CoefOutI_4,
           CoefOutI_5,
           CoefOutI_6,
           CoefOutI_7,
           CoefOutI_8,
           CoefOutI_9,
           CoefOutI_10,
           CoefOutI_11,
           CoefOutI_12);


  output  signed [16:0] CoefOutI_0;  // sfix17_En19
  output  signed [16:0] CoefOutI_1;  // sfix17_En19
  output  signed [16:0] CoefOutI_2;  // sfix17_En19
  output  signed [16:0] CoefOutI_3;  // sfix17_En19
  output  signed [16:0] CoefOutI_4;  // sfix17_En19
  output  signed [16:0] CoefOutI_5;  // sfix17_En19
  output  signed [16:0] CoefOutI_6;  // sfix17_En19
  output  signed [16:0] CoefOutI_7;  // sfix17_En19
  output  signed [16:0] CoefOutI_8;  // sfix17_En19
  output  signed [16:0] CoefOutI_9;  // sfix17_En19
  output  signed [16:0] CoefOutI_10;  // sfix17_En19
  output  signed [16:0] CoefOutI_11;  // sfix17_En19
  output  signed [16:0] CoefOutI_12;  // sfix17_En19


  wire signed [16:0] CoefData;  // sfix17_En19
  wire signed [16:0] CoefData_1;  // sfix17_En19
  wire signed [16:0] CoefData_2;  // sfix17_En19
  wire signed [16:0] CoefData_3;  // sfix17_En19
  wire signed [16:0] CoefData_4;  // sfix17_En19
  wire signed [16:0] CoefData_5;  // sfix17_En19
  wire signed [16:0] CoefData_6;  // sfix17_En19
  wire signed [16:0] CoefData_7;  // sfix17_En19
  wire signed [16:0] CoefData_8;  // sfix17_En19
  wire signed [16:0] CoefData_9;  // sfix17_En19
  wire signed [16:0] CoefData_10;  // sfix17_En19
  wire signed [16:0] CoefData_11;  // sfix17_En19
  wire signed [16:0] CoefData_12;  // sfix17_En19


  // CoefReg_1
  assign CoefData = 17'sb00110111101100110;

  assign CoefOutI_0 = CoefData;

  // CoefReg_2
  assign CoefData_1 = 17'sb11001000010011010;

  assign CoefOutI_1 = CoefData_1;

  // CoefReg_3
  assign CoefData_2 = 17'sb00110111101100110;

  assign CoefOutI_2 = CoefData_2;

  // CoefReg_4
  assign CoefData_3 = 17'sb11001000010011010;

  assign CoefOutI_3 = CoefData_3;

  // CoefReg_5
  assign CoefData_4 = 17'sb00110111101100110;

  assign CoefOutI_4 = CoefData_4;

  // CoefReg_6
  assign CoefData_5 = 17'sb00110111101100110;

  assign CoefOutI_5 = CoefData_5;

  // CoefReg_7
  assign CoefData_6 = 17'sb11001000010011010;

  assign CoefOutI_6 = CoefData_6;

  // CoefReg_8
  assign CoefData_7 = 17'sb11001000010011010;

  assign CoefOutI_7 = CoefData_7;

  // CoefReg_9
  assign CoefData_8 = 17'sb00110111101100110;

  assign CoefOutI_8 = CoefData_8;

  // CoefReg_10
  assign CoefData_9 = 17'sb00110111101100110;

  assign CoefOutI_9 = CoefData_9;

  // CoefReg_11
  assign CoefData_10 = 17'sb00110111101100110;

  assign CoefOutI_10 = CoefData_10;

  // CoefReg_12
  assign CoefData_11 = 17'sb00110111101100110;

  assign CoefOutI_11 = CoefData_11;

  // CoefReg_13
  assign CoefData_12 = 17'sb00110111101100110;

  assign CoefOutI_12 = CoefData_12;

endmodule  // Receiver_ip_src_FilterCoef_block1

