// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_FilterTapSystolicWvldin.v
// Created: 2026-05-26 18:50:49
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_FilterTapSystolicWvldin
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/Correlator/Discrete 
// FIR Filter/Filter/subFilter/FilterTapSystolicWvldi
// Hierarchy Level: 8
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_FilterTapSystolicWvldin
          (clk,
           enb_1_2_0,
           dinReg2_0_re,
           coefIn_0,
           addin,
           dinRegVld,
           syncReset,
           dinDly2,
           tapout);


  input   clk;
  input   enb_1_2_0;
  input   signed [16:0] dinReg2_0_re;  // sfix17_En14
  input   signed [16:0] coefIn_0;  // sfix17_En19
  input   signed [47:0] addin;  // sfix48_En33
  input   dinRegVld;
  input   syncReset;
  output  signed [16:0] dinDly2;  // sfix17_En14
  output  signed [47:0] tapout;  // sfix48_En33


  reg signed [16:0] fTap_din_reg1;  // sfix17
  reg signed [16:0] fTap_coef_reg1;  // sfix17
  reg signed [16:0] fTap_din_reg2;  // sfix17
  reg signed [16:0] fTap_coef_reg2;  // sfix17
  reg signed [33:0] fTap_mult_reg;  // sfix34
  reg signed [47:0] fTap_addout_reg;  // sfix48
  reg signed [16:0] fTap_din_reg1_next;  // sfix17_En14
  reg signed [16:0] fTap_coef_reg1_next;  // sfix17_En19
  reg signed [16:0] fTap_din_reg2_next;  // sfix17_En14
  reg signed [16:0] fTap_coef_reg2_next;  // sfix17_En19
  reg signed [33:0] fTap_mult_reg_next;  // sfix34_En33
  reg signed [47:0] fTap_addout_reg_next;  // sfix48_En33
  reg signed [16:0] dinDly2_1;  // sfix17_En14
  reg signed [47:0] tapout_1;  // sfix48_En33
  reg signed [47:0] fTap_add_cast;  // sfix48_En33

  initial begin
    fTap_din_reg1 = 17'sb00000000000000000;
    fTap_coef_reg1 = 17'sb00000000000000000;
    fTap_din_reg2 = 17'sb00000000000000000;
    fTap_coef_reg2 = 17'sb00000000000000000;
    fTap_mult_reg = 34'sh000000000;
    fTap_addout_reg = 48'sh000000000000;
  end

  // FilterTapSystlicWvldIn
  always @(posedge clk)
    begin : fTap_process
      if (enb_1_2_0) begin
        if (syncReset == 1'b1) begin
          fTap_din_reg1 <= 17'sb00000000000000000;
          fTap_coef_reg1 <= 17'sb00000000000000000;
          fTap_din_reg2 <= 17'sb00000000000000000;
          fTap_coef_reg2 <= 17'sb00000000000000000;
          fTap_mult_reg <= 34'sh000000000;
          fTap_addout_reg <= 48'sh000000000000;
        end
        else begin
          fTap_din_reg1 <= fTap_din_reg1_next;
          fTap_coef_reg1 <= fTap_coef_reg1_next;
          fTap_din_reg2 <= fTap_din_reg2_next;
          fTap_coef_reg2 <= fTap_coef_reg2_next;
          fTap_mult_reg <= fTap_mult_reg_next;
          fTap_addout_reg <= fTap_addout_reg_next;
        end
      end
    end

  always @(addin, coefIn_0, dinReg2_0_re, dinRegVld, fTap_addout_reg, fTap_coef_reg1,
       fTap_coef_reg2, fTap_din_reg1, fTap_din_reg2, fTap_mult_reg) begin
    fTap_add_cast = 48'sh000000000000;
    fTap_din_reg1_next = fTap_din_reg1;
    fTap_coef_reg1_next = fTap_coef_reg1;
    fTap_din_reg2_next = fTap_din_reg2;
    fTap_coef_reg2_next = fTap_coef_reg2;
    fTap_mult_reg_next = fTap_mult_reg;
    fTap_addout_reg_next = fTap_addout_reg;
    if (dinRegVld) begin
      fTap_add_cast = {{14{fTap_mult_reg[33]}}, fTap_mult_reg};
      fTap_addout_reg_next = fTap_add_cast + addin;
      fTap_mult_reg_next = fTap_din_reg2 * fTap_coef_reg2;
      fTap_din_reg2_next = fTap_din_reg1;
      fTap_coef_reg2_next = fTap_coef_reg1;
      fTap_din_reg1_next = dinReg2_0_re;
      fTap_coef_reg1_next = coefIn_0;
    end
    dinDly2_1 = fTap_din_reg2;
    tapout_1 = fTap_addout_reg;
  end

  assign dinDly2 = dinDly2_1;

  assign tapout = tapout_1;

endmodule  // Receiver_ip_src_FilterTapSystolicWvldin

