// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Receiver.v
// Created: 2026-05-26 18:50:49
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 6.51042e-08
// Target subsystem base rate: 6.51042e-08
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        6.51042e-08
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// rxDiagBus_nSynced             ce_out        6.51042e-08
// rxDiagBus_normCoarseFreqEst   ce_out        6.51042e-08
// count_out                     ce_out        6.51042e-08
// packets_out                   ce_out        6.51042e-08
// bit_errors_out                ce_out        6.51042e-08
// debugI                        ce_out        6.51042e-08
// debugQ                        ce_out        6.51042e-08
// debugValid                    ce_out        6.51042e-08
// debugI1                       ce_out        6.51042e-08
// debugQ1                       ce_out        6.51042e-08
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Receiver
// Source Path: commhdlQPSKTxRx/Receiver
// Hierarchy Level: 0
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Receiver
          (clk,
           reset,
           clk_enable,
           validIn,
           dataInI,
           dataInQ,
           rstCS,
           iq_debug_mux,
           ce_out,
           rxDiagBus_nSynced,
           rxDiagBus_normCoarseFreqEst,
           count_out,
           packets_out,
           bit_errors_out,
           debugI,
           debugQ,
           debugValid,
           debugI1,
           debugQ1);


  input   clk;
  input   reset;
  input   clk_enable;
  input   validIn;
  input   signed [15:0] dataInI;  // int16
  input   signed [15:0] dataInQ;  // int16
  input   rstCS;
  input   [31:0] iq_debug_mux;  // uint32
  output  ce_out;
  output  rxDiagBus_nSynced;
  output  signed [20:0] rxDiagBus_normCoarseFreqEst;  // sfix21_En21
  output  [31:0] count_out;  // uint32
  output  [31:0] packets_out;  // uint32
  output  [31:0] bit_errors_out;  // uint32
  output  signed [15:0] debugI;  // int16
  output  signed [15:0] debugQ;  // int16
  output  debugValid;
  output  signed [15:0] debugI1;  // int16
  output  signed [15:0] debugQ1;  // int16


  wire enb_1_2_0;
  wire enb_1_2_1;
  wire enb_1_1_1;
  reg signed [15:0] Downsample2_bypass_reg;  // sfix16
  wire signed [15:0] Downsample2_out1;  // int16
  reg signed [15:0] Downsample3_bypass_reg;  // sfix16
  wire signed [15:0] Downsample3_out1;  // int16
  reg signed [15:0] Delay3_out1_re;  // int16
  reg signed [15:0] Delay3_out1_im;  // int16
  wire signed [15:0] Data_Type_Conversion2_out1_re;  // sfix16_En14
  wire signed [15:0] Data_Type_Conversion2_out1_im;  // sfix16_En14
  reg signed [15:0] Delay_out1_re;  // sfix16_En14
  reg signed [15:0] Delay_out1_im;  // sfix16_En14
  reg  Downsample1_out1;
  reg  Delay4_out1;
  reg  Delay1_out1;
  reg  Downsample_out1;
  reg  Delay5_out1;
  reg  Delay2_out1;
  reg [31:0] Downsample4_out1;  // uint32
  reg [31:0] Delay6_out1;  // uint32
  wire QPSK_Rx_dataOut;
  wire QPSK_Rx_ctrlOut_startOut;
  wire QPSK_Rx_ctrlOut_validOut;
  wire QPSK_Rx_rxDiagBus_nSynced;
  wire signed [20:0] QPSK_Rx_rxDiagBus_normCoarseFreqEst;  // sfix21_En21
  wire signed [15:0] QPSK_Rx_debugIOut;  // int16
  wire signed [15:0] QPSK_Rx_debugQOut;  // int16
  wire QPSK_Rx_debugValid;
  wire nSynced;
  wire nSynced_1;
  wire signed [20:0] normCoarseFreqEst;  // sfix21_En21
  wire signed [20:0] normCoarseFreqEst_1;  // sfix21_En21
  wire startOut;
  wire validOut;
  wire [31:0] Capture_Data_Bits_count_out;  // uint32
  wire [31:0] Capture_Data_Bits_packets_out;  // uint32
  wire [31:0] Capture_Data_Bits_bit_errors_out;  // uint32
  wire [31:0] Repeat3_out1;  // uint32
  wire [31:0] Repeat2_out1;  // uint32
  wire [31:0] Repeat1_out1;  // uint32
  reg signed [15:0] Delay7_out1;  // int16
  wire signed [15:0] nSynced_2;  // int16
  reg signed [15:0] Delay8_out1;  // int16
  wire signed [15:0] nSynced_3;  // int16
  reg  Delay11_out1;
  wire nSynced_4;


  Receiver_ip_src_Receiver_tc u_Receiver_tc (.clk(clk),
                                             .reset(reset),
                                             .clk_enable(clk_enable),
                                             .enb_1_1_1(enb_1_1_1),
                                             .enb_1_2_0(enb_1_2_0),
                                             .enb_1_2_1(enb_1_2_1)
                                             );

  // Downsample2: Downsample by 2, Sample offset 0 
  // Downsample bypass register
  always @(posedge clk or posedge reset)
    begin : Downsample2_bypass_process
      if (reset == 1'b1) begin
        Downsample2_bypass_reg <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_1) begin
          Downsample2_bypass_reg <= dataInI;
        end
      end
    end

  assign Downsample2_out1 = (enb_1_2_1 == 1'b1 ? dataInI :
              Downsample2_bypass_reg);

  // Downsample3: Downsample by 2, Sample offset 0 
  // Downsample bypass register
  always @(posedge clk or posedge reset)
    begin : Downsample3_bypass_process
      if (reset == 1'b1) begin
        Downsample3_bypass_reg <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_1) begin
          Downsample3_bypass_reg <= dataInQ;
        end
      end
    end

  assign Downsample3_out1 = (enb_1_2_1 == 1'b1 ? dataInQ :
              Downsample3_bypass_reg);

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1_re <= 16'sb0000000000000000;
        Delay3_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay3_out1_re <= Downsample2_out1;
          Delay3_out1_im <= Downsample3_out1;
        end
      end
    end

  assign Data_Type_Conversion2_out1_re = Delay3_out1_re;
  assign Data_Type_Conversion2_out1_im = Delay3_out1_im;

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1_re <= 16'sb0000000000000000;
        Delay_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay_out1_re <= Data_Type_Conversion2_out1_re;
          Delay_out1_im <= Data_Type_Conversion2_out1_im;
        end
      end
    end

  // Downsample by 2 register (Sample offset 0)
  always @(posedge clk or posedge reset)
    begin : Downsample1_output_process
      if (reset == 1'b1) begin
        Downsample1_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_1) begin
          Downsample1_out1 <= validIn;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay4_out1 <= Downsample1_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay1_out1 <= Delay4_out1;
        end
      end
    end

  // Downsample by 2 register (Sample offset 0)
  always @(posedge clk or posedge reset)
    begin : Downsample_output_process
      if (reset == 1'b1) begin
        Downsample_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_1) begin
          Downsample_out1 <= rstCS;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay5_out1 <= Downsample_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay2_out1 <= Delay5_out1;
        end
      end
    end

  // Downsample by 2 register (Sample offset 0)
  always @(posedge clk or posedge reset)
    begin : Downsample4_output_process
      if (reset == 1'b1) begin
        Downsample4_out1 <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_1) begin
          Downsample4_out1 <= iq_debug_mux;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_out1 <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay6_out1 <= Downsample4_out1;
        end
      end
    end

  Receiver_ip_src_QPSK_Rx u_QPSK_Rx (.clk(clk),
                                     .reset(reset),
                                     .enb_1_2_0(enb_1_2_0),
                                     .dataIn_re(Delay_out1_re),  // sfix16_En14
                                     .dataIn_im(Delay_out1_im),  // sfix16_En14
                                     .validIn(Delay1_out1),
                                     .rstCS(Delay2_out1),
                                     .debugMuxCtrl(Delay6_out1),  // uint32
                                     .dataOut(QPSK_Rx_dataOut),
                                     .ctrlOut_startOut(QPSK_Rx_ctrlOut_startOut),
                                     .ctrlOut_validOut(QPSK_Rx_ctrlOut_validOut),
                                     .rxDiagBus_nSynced(QPSK_Rx_rxDiagBus_nSynced),
                                     .rxDiagBus_normCoarseFreqEst(QPSK_Rx_rxDiagBus_normCoarseFreqEst),  // sfix21_En21
                                     .debugIOut(QPSK_Rx_debugIOut),  // int16
                                     .debugQOut(QPSK_Rx_debugQOut),  // int16
                                     .debugValid(QPSK_Rx_debugValid)
                                     );

  assign nSynced = QPSK_Rx_rxDiagBus_nSynced;

  assign nSynced_1 = nSynced;

  assign rxDiagBus_nSynced = nSynced_1;

  assign normCoarseFreqEst = QPSK_Rx_rxDiagBus_normCoarseFreqEst;

  assign normCoarseFreqEst_1 = normCoarseFreqEst;

  assign rxDiagBus_normCoarseFreqEst = normCoarseFreqEst_1;

  assign startOut = QPSK_Rx_ctrlOut_startOut;

  assign validOut = QPSK_Rx_ctrlOut_validOut;

  Receiver_ip_src_Capture_Data_Bits u_Capture_Data_Bits (.clk(clk),
                                                         .reset(reset),
                                                         .enb_1_2_0(enb_1_2_0),
                                                         .dataOut(QPSK_Rx_dataOut),
                                                         .dataSrt(startOut),
                                                         .valid(validOut),
                                                         .count_out(Capture_Data_Bits_count_out),  // uint32
                                                         .packets_out(Capture_Data_Bits_packets_out),  // uint32
                                                         .bit_errors_out(Capture_Data_Bits_bit_errors_out)  // uint32
                                                         );

  assign Repeat3_out1 = Capture_Data_Bits_count_out;

  assign count_out = Repeat3_out1;

  assign Repeat2_out1 = Capture_Data_Bits_packets_out;

  assign packets_out = Repeat2_out1;

  assign Repeat1_out1 = Capture_Data_Bits_bit_errors_out;

  assign bit_errors_out = Repeat1_out1;

  always @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay7_out1 <= QPSK_Rx_debugIOut;
        end
      end
    end

  assign nSynced_2 = Delay7_out1;

  assign debugI = nSynced_2;

  always @(posedge clk or posedge reset)
    begin : Delay8_process
      if (reset == 1'b1) begin
        Delay8_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay8_out1 <= QPSK_Rx_debugQOut;
        end
      end
    end

  assign nSynced_3 = Delay8_out1;

  assign debugQ = nSynced_3;

  always @(posedge clk or posedge reset)
    begin : Delay11_process
      if (reset == 1'b1) begin
        Delay11_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay11_out1 <= QPSK_Rx_debugValid;
        end
      end
    end

  assign nSynced_4 = Delay11_out1;

  assign debugValid = nSynced_4;

  assign debugI1 = dataInI;

  assign debugQ1 = dataInQ;

  assign ce_out = enb_1_1_1;

endmodule  // Receiver_ip_src_Receiver

