// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Validate_Input_Push_Pop.v
// Created: 2026-05-26 18:50:49
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Validate_Input_Push_Pop
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/FIFO/Validate 
// Input Push Po
// Hierarchy Level: 5
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Validate_Input_Push_Pop
          (clk,
           reset,
           enb_1_2_0,
           rst,
           push,
           pop,
           valid_push,
           valid_pop);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   rst;
  input   push;
  input   pop;
  output  valid_push;
  output  valid_pop;


  wire Constant_out1;
  wire Constant1_out1;
  reg [10:0] Delay_out1;  // ufix11
  wire Compare_To_Constant1_y;
  wire Logical_Operator7_out1;
  wire Switch_out1;
  wire Logical_Operator9_out1;
  wire Logical_Operator1_out1;
  wire [10:0] count;  // ufix11
  wire Compare_To_Constant_y;
  wire pop_on_empty_FIFO;
  wire Logical_Operator6_out1;
  wire Logical_Operator8_out1;
  wire Logical_Operator5_out1;
  wire push_on_full_FIFO;
  wire Logical_Operator2_out1;


  assign Constant_out1 = 1'b1;

  assign Constant1_out1 = 1'b0;

  Receiver_ip_src_Compare_To_Constant1 u_Compare_To_Constant1 (.u(Delay_out1),  // ufix11
                                                               .y(Compare_To_Constant1_y)
                                                               );

  assign Switch_out1 = (Logical_Operator7_out1 == 1'b0 ? Constant_out1 :
              Constant1_out1);

  assign Logical_Operator1_out1 = Logical_Operator9_out1 ^ Logical_Operator7_out1;

  Receiver_ip_src_MATLAB_Function_block1 u_MATLAB_Function (.clk(clk),
                                                            .reset(reset),
                                                            .enb_1_2_0(enb_1_2_0),
                                                            .rst(rst),
                                                            .enb_1(Logical_Operator1_out1),
                                                            .dir(Switch_out1),
                                                            .count(count)  // ufix11
                                                            );

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 11'b00000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay_out1 <= count;
        end
      end
    end

  Receiver_ip_src_Compare_To_Constant u_Compare_To_Constant (.u(Delay_out1),  // ufix11
                                                             .y(Compare_To_Constant_y)
                                                             );

  assign pop_on_empty_FIFO = Compare_To_Constant_y & pop;

  assign Logical_Operator6_out1 =  ~ pop_on_empty_FIFO;

  assign Logical_Operator7_out1 = pop & Logical_Operator6_out1;

  assign Logical_Operator8_out1 =  ~ Logical_Operator7_out1;

  assign Logical_Operator5_out1 = push & Logical_Operator8_out1;

  assign push_on_full_FIFO = Logical_Operator5_out1 & Compare_To_Constant1_y;

  assign Logical_Operator2_out1 =  ~ push_on_full_FIFO;

  assign Logical_Operator9_out1 = push & Logical_Operator2_out1;

  assign valid_push = Logical_Operator9_out1;

  assign valid_pop = Logical_Operator7_out1;

endmodule  // Receiver_ip_src_Validate_Input_Push_Pop

