// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Quadrant_Mapper.v
// Created: 2026-05-26 18:50:47
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Quadrant_Mapper
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Coarse Frequency Compensator/Coarse 
// Frequency Estimator/Extract Frequency/HDL_CMA_core/Quadrant_Mappe
// Hierarchy Level: 7
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Quadrant_Mapper
          (clk,
           reset,
           enb_1_2_0,
           xin,
           yin,
           xout,
           yout,
           QA_Control);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [32:0] xin;  // sfix33_En24
  input   signed [32:0] yin;  // sfix33_En24
  output  signed [32:0] xout;  // sfix33_En24
  output  signed [32:0] yout;  // sfix33_En24
  output  [4:0] QA_Control;  // ufix5


  wire signed [33:0] abs_y;  // sfix34_En24
  wire signed [33:0] abs_cast;  // sfix34_En24
  wire signed [32:0] xAbs;  // sfix33_En24
  reg signed [32:0] xAbsReg;  // sfix33_En24
  wire signed [33:0] abs_y_1;  // sfix34_En24
  wire signed [33:0] abs_cast_1;  // sfix34_En24
  wire signed [32:0] yAbs;  // sfix33_En24
  reg signed [32:0] yAbsReg;  // sfix33_En24
  wire XGreaterThanY;  // ufix1
  wire signed [32:0] xout_1;  // sfix33_En24
  wire signed [32:0] yout_1;  // sfix33_En24
  reg signed [32:0] in2reg;  // sfix33_En24
  wire yZero;  // ufix1
  reg signed [32:0] in1reg;  // sfix33_En24
  wire xPositive;  // ufix1
  wire yZeroXPositive;  // ufix1
  wire xNegative;  // ufix1
  wire yZeroXNegative;  // ufix1
  wire yNegative;  // ufix1
  wire [4:0] qcControl;  // ufix5


  assign abs_cast = {xin[32], xin};
  assign abs_y = (xin < 33'sh000000000 ?  - (abs_cast) :
              {xin[32], xin});
  assign xAbs = abs_y[32:0];

  always @(posedge clk or posedge reset)
    begin : DelayxAbs_process
      if (reset == 1'b1) begin
        xAbsReg <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xAbsReg <= xAbs;
        end
      end
    end

  assign abs_cast_1 = {yin[32], yin};
  assign abs_y_1 = (yin < 33'sh000000000 ?  - (abs_cast_1) :
              {yin[32], yin});
  assign yAbs = abs_y_1[32:0];

  always @(posedge clk or posedge reset)
    begin : DelayyAbs_process
      if (reset == 1'b1) begin
        yAbsReg <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yAbsReg <= yAbs;
        end
      end
    end

  assign XGreaterThanY = xAbsReg > yAbsReg;

  assign xout_1 = (XGreaterThanY == 1'b0 ? yAbsReg :
              xAbsReg);

  assign xout = xout_1;

  assign yout_1 = (XGreaterThanY == 1'b0 ? xAbsReg :
              yAbsReg);

  assign yout = yout_1;

  always @(posedge clk or posedge reset)
    begin : Delayin2_process
      if (reset == 1'b1) begin
        in2reg <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          in2reg <= yin;
        end
      end
    end

  assign yZero = in2reg == 33'sh000000000;

  always @(posedge clk or posedge reset)
    begin : Delayin1_process
      if (reset == 1'b1) begin
        in1reg <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          in1reg <= xin;
        end
      end
    end

  assign xPositive = in1reg >= 33'sh000000000;

  assign yZeroXPositive = yZero & xPositive;

  assign xNegative = in1reg < 33'sh000000000;

  assign yZeroXNegative = yZero & xNegative;

  assign yNegative = in2reg < 33'sh000000000;

  assign qcControl = {yZeroXPositive, yZeroXNegative, XGreaterThanY, xNegative, yNegative};

  assign QA_Control = qcControl;

endmodule  // Receiver_ip_src_Quadrant_Mapper

