function hRD = plugin_rd(board, design)
% Reference design definition

%   Copyright 2014-2015 The MathWorks, Inc.

% Construct reference design object
hRD = hdlcoder.ReferenceDesign('SynthesisTool', 'Xilinx Vivado');

% Create the reference design for the SOM-only
% This is the base reference design that other RDs can build upon
hRD.ReferenceDesignName = sprintf('%s (%s)', upper(board), design);

% Determine the board name based on the design
hRD.BoardName = sprintf('AnalogDevices ADRV9361-Z7035 AGC');

% Tool information
hRD.SupportedToolVersion = {'2019.1'};

% Add AGC control
hRD.addParameter( ...
    'ParameterID',   'en_agc', ...
    'DisplayName',   'Control AGC', ...
    'DefaultValue',  'Rx', ...
    'ParameterType',  hdlcoder.ParameterType.Dropdown, ...
    'Choice',       {'Rx', 'Tx'});

% Get the root directory
rootDir = fileparts(strtok(mfilename('fullpath'), '+'));
tmp = strsplit(rootDir,'/');
rootDir = fullfile('/',tmp{1:end-3});
rootDirBSP = fullfile('hdl','vendor','AnalogDevices','vivado');

% Design files are shared
hRD.SharedRD = true;
hRD.SharedRDFolder = rootDir;

board = 'ccfmc_lvds_agc';

hRD.addParameter( ...
    'ParameterID',   'project', ...
    'DisplayName',   'HDL Project Subfolder', ...
    'DefaultValue',  'adrv9361z7035');

hRD.addParameter( ...
    'ParameterID',   'carrier', ...
    'DisplayName',   'HDL Project Carrier', ...
    'DefaultValue',  'ccfmc_lvds');

hRD.addParameter( ...
    'ParameterID',   'ref_design', ...
    'DisplayName',   'Reference Type', ...
    'DefaultValue',  'rx');

hRD.addParameter( ...
    'ParameterID',   'preprocess', ...
    'DisplayName',   'Preprocess', ...
    'DefaultValue',  'on');

hRD.addParameter( ...
    'ParameterID',   'preprocess_script', ...
    'DisplayName',   'Preprocess Script', ...
    'DefaultValue',  fullfile('trx_examples', 'targeting', 'tuneAGC-ad9361', 'ccfmc_lvds_agc','tune_agc_preprocess.tcl'));

hRD.addCustomVivadoDesign( ...
    'CustomBlockDesignTcl', fullfile('hdl', 'vendor', 'AnalogDevices', 'vivado', 'projects', 'scripts', 'system_project_rxtx.tcl'), ...
    'CustomTopLevelHDL',    fullfile('trx_examples', 'targeting', 'tuneAGC-ad9361',  'ccfmc_lvds_agc', 'system_top.v'));

hRD.BlockDesignName = 'system';	
	
% custom constraint files
board_type = strsplit(board,'_');
hRD.CustomConstraints = {...
    fullfile(rootDirBSP, 'projects', 'adrv9361z7035', 'common', strcat(board_type{1}, '_constr.xdc')), ...
	fullfile(rootDirBSP, 'projects', 'adrv9361z7035', 'common', 'adrv9361z7035_constr.xdc'), ...
	fullfile(rootDirBSP, 'projects', 'adrv9361z7035', 'common', strcat('adrv9361z7035_constr_', board_type{2}, '.xdc')), ...
    };

% custom source files
hRD.CustomFiles = {...
	fullfile(rootDirBSP, 'library')...,
	fullfile(rootDirBSP, 'library','xilinx')...,
	fullfile(rootDirBSP, 'projects','common')...,
	fullfile(rootDirBSP, 'projects','scripts')...,
	fullfile(rootDirBSP, 'projects','fmcomms2')...,
	fullfile(rootDirBSP, 'projects','adrv9361z7035', 'common')...,
    fullfile(rootDirBSP, 'projects','adrv9361z7035', 'ccfmc_lvds')...,
    fullfile('trx_examples', 'targeting', 'tuneAGC-ad9361', 'ccfmc_lvds_agc')...,
    };	

%% Add interfaces
% add clock interface
hRD.addClockInterface( ...
    'ClockConnection',   'util_ad9361_divclk/clk_out', ...
    'ResetConnection',   'util_ad9361_divclk_reset/peripheral_aresetn');