// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Interpolation_Filter.v
// Created: 2026-05-26 18:50:49
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Interpolation_Filter
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Symbol Synchronizer/Interpolation 
// Filte
// Hierarchy Level: 4
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Interpolation_Filter
          (clk,
           reset,
           enb_1_2_0,
           In_re,
           In_im,
           mu,
           interpolant_re,
           interpolant_im);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [15:0] In_re;  // sfix16_En12
  input   signed [15:0] In_im;  // sfix16_En12
  input   signed [10:0] mu;  // sfix11_En10
  output  signed [18:0] interpolant_re;  // sfix19_En12
  output  signed [18:0] interpolant_im;  // sfix19_En12


  reg signed [15:0] Delay1_out1_re;  // sfix16_En12
  reg signed [15:0] Delay1_out1_im;  // sfix16_En12
  reg signed [15:0] Delay36_out1_re;  // sfix16_En12
  reg signed [15:0] Delay36_out1_im;  // sfix16_En12
  reg signed [15:0] Delay33_out1_re;  // sfix16_En12
  reg signed [15:0] Delay33_out1_im;  // sfix16_En12
  reg signed [15:0] Delay10_out1_re;  // sfix16_En12
  reg signed [15:0] Delay10_out1_im;  // sfix16_En12
  reg signed [15:0] Delay23_out1_re;  // sfix16_En12
  reg signed [15:0] Delay23_out1_im;  // sfix16_En12
  reg signed [15:0] Delay28_out1_re;  // sfix16_En12
  reg signed [15:0] Delay28_out1_im;  // sfix16_En12
  reg signed [15:0] Delay18_reg_re [0:1];  // sfix16_En12 [2]
  reg signed [15:0] Delay18_reg_im [0:1];  // sfix16_En12 [2]
  wire signed [15:0] Delay18_reg_next_re [0:1];  // sfix16_En12 [2]
  wire signed [15:0] Delay18_reg_next_im [0:1];  // sfix16_En12 [2]
  wire signed [15:0] Delay18_out1_re;  // sfix16_En12
  wire signed [15:0] Delay18_out1_im;  // sfix16_En12
  reg signed [15:0] Delay12_reg_re [0:1];  // sfix16_En12 [2]
  reg signed [15:0] Delay12_reg_im [0:1];  // sfix16_En12 [2]
  wire signed [15:0] Delay12_reg_next_re [0:1];  // sfix16_En12 [2]
  wire signed [15:0] Delay12_reg_next_im [0:1];  // sfix16_En12 [2]
  wire signed [15:0] Delay12_out1_re;  // sfix16_En12
  wire signed [15:0] Delay12_out1_im;  // sfix16_En12
  reg signed [15:0] Delay8_reg_re [0:1];  // sfix16_En12 [2]
  reg signed [15:0] Delay8_reg_im [0:1];  // sfix16_En12 [2]
  wire signed [15:0] Delay8_reg_next_re [0:1];  // sfix16_En12 [2]
  wire signed [15:0] Delay8_reg_next_im [0:1];  // sfix16_En12 [2]
  wire signed [15:0] Delay8_out1_re;  // sfix16_En12
  wire signed [15:0] Delay8_out1_im;  // sfix16_En12
  reg signed [15:0] Delay5_reg_re [0:1];  // sfix16_En12 [2]
  reg signed [15:0] Delay5_reg_im [0:1];  // sfix16_En12 [2]
  wire signed [15:0] Delay5_reg_next_re [0:1];  // sfix16_En12 [2]
  wire signed [15:0] Delay5_reg_next_im [0:1];  // sfix16_En12 [2]
  wire signed [15:0] Delay5_out1_re;  // sfix16_En12
  wire signed [15:0] Delay5_out1_im;  // sfix16_En12
  wire signed [15:0] divide_by_2_out1_re;  // sfix16_En12
  wire signed [15:0] divide_by_2_out1_im;  // sfix16_En12
  reg signed [15:0] Delay35_out1_re;  // sfix16_En12
  reg signed [15:0] Delay35_out1_im;  // sfix16_En12
  wire signed [16:0] Sum9_sub_cast;  // sfix17_En12
  wire signed [16:0] Sum9_sub_cast_1;  // sfix17_En12
  wire signed [16:0] Sum9_sub_cast_2;  // sfix17_En12
  wire signed [16:0] Sum9_sub_cast_3;  // sfix17_En12
  wire signed [16:0] Sum9_out1_re;  // sfix17_En12
  wire signed [16:0] Sum9_out1_im;  // sfix17_En12
  reg signed [16:0] Delay32_out1_re;  // sfix17_En12
  reg signed [16:0] Delay32_out1_im;  // sfix17_En12
  reg signed [15:0] Delay2_out1_re;  // sfix16_En12
  reg signed [15:0] Delay2_out1_im;  // sfix16_En12
  reg signed [15:0] Delay31_out1_re;  // sfix16_En12
  reg signed [15:0] Delay31_out1_im;  // sfix16_En12
  wire signed [17:0] Sum10_add_cast;  // sfix18_En12
  wire signed [17:0] Sum10_add_cast_1;  // sfix18_En12
  wire signed [17:0] Sum10_add_cast_2;  // sfix18_En12
  wire signed [17:0] Sum10_add_cast_3;  // sfix18_En12
  wire signed [17:0] Sum10_out1_re;  // sfix18_En12
  wire signed [17:0] Sum10_out1_im;  // sfix18_En12
  reg signed [17:0] Delay22_out1_re;  // sfix18_En12
  reg signed [17:0] Delay22_out1_im;  // sfix18_En12
  reg signed [15:0] Delay3_out1_re;  // sfix16_En12
  reg signed [15:0] Delay3_out1_im;  // sfix16_En12
  reg signed [15:0] Delay21_out1_re;  // sfix16_En12
  reg signed [15:0] Delay21_out1_im;  // sfix16_En12
  wire signed [18:0] Sum4_sub_cast;  // sfix19_En12
  wire signed [18:0] Sum4_sub_cast_1;  // sfix19_En12
  wire signed [18:0] Sum4_sub_cast_2;  // sfix19_En12
  wire signed [18:0] Sum4_sub_cast_3;  // sfix19_En12
  wire signed [18:0] Sum4_out1_re;  // sfix19_En12
  wire signed [18:0] Sum4_out1_im;  // sfix19_En12
  reg signed [18:0] Delay27_out1_re;  // sfix19_En12
  reg signed [18:0] Delay27_out1_im;  // sfix19_En12
  reg signed [18:0] Delay17_reg_re [0:1];  // sfix19_En12 [2]
  reg signed [18:0] Delay17_reg_im [0:1];  // sfix19_En12 [2]
  wire signed [18:0] Delay17_reg_next_re [0:1];  // sfix19_En12 [2]
  wire signed [18:0] Delay17_reg_next_im [0:1];  // sfix19_En12 [2]
  wire signed [18:0] Delay17_out1_re;  // sfix19_En12
  wire signed [18:0] Delay17_out1_im;  // sfix19_En12
  reg signed [15:0] Delay4_out1_re;  // sfix16_En12
  reg signed [15:0] Delay4_out1_im;  // sfix16_En12
  reg signed [15:0] Delay26_out1_re;  // sfix16_En12
  reg signed [15:0] Delay26_out1_im;  // sfix16_En12
  reg signed [15:0] Delay16_reg_re [0:1];  // sfix16_En12 [2]
  reg signed [15:0] Delay16_reg_im [0:1];  // sfix16_En12 [2]
  wire signed [15:0] Delay16_reg_next_re [0:1];  // sfix16_En12 [2]
  wire signed [15:0] Delay16_reg_next_im [0:1];  // sfix16_En12 [2]
  wire signed [15:0] Delay16_out1_re;  // sfix16_En12
  wire signed [15:0] Delay16_out1_im;  // sfix16_En12
  wire signed [19:0] Sum7_sub_cast;  // sfix20_En12
  wire signed [19:0] Sum7_sub_cast_1;  // sfix20_En12
  wire signed [19:0] Sum7_sub_temp;  // sfix20_En12
  wire signed [19:0] Sum7_sub_cast_2;  // sfix20_En12
  wire signed [19:0] Sum7_sub_cast_3;  // sfix20_En12
  wire signed [19:0] Sum7_sub_temp_1;  // sfix20_En12
  wire signed [15:0] Sum7_out1_re;  // sfix16_En10
  wire signed [15:0] Sum7_out1_im;  // sfix16_En10
  reg signed [15:0] Delay11_reg_re [0:1];  // sfix16_En10 [2]
  reg signed [15:0] Delay11_reg_im [0:1];  // sfix16_En10 [2]
  wire signed [15:0] Delay11_reg_next_re [0:1];  // sfix16_En10 [2]
  wire signed [15:0] Delay11_reg_next_im [0:1];  // sfix16_En10 [2]
  wire signed [15:0] Delay11_out1_re;  // sfix16_En10
  wire signed [15:0] Delay11_out1_im;  // sfix16_En10
  reg signed [15:0] Delay30_out1_re;  // sfix16_En12
  reg signed [15:0] Delay30_out1_im;  // sfix16_En12
  wire signed [16:0] Sum1_sub_cast;  // sfix17_En12
  wire signed [16:0] Sum1_sub_cast_1;  // sfix17_En12
  wire signed [16:0] Sum1_sub_cast_2;  // sfix17_En12
  wire signed [16:0] Sum1_sub_cast_3;  // sfix17_En12
  wire signed [16:0] Sum1_out1_re;  // sfix17_En12
  wire signed [16:0] Sum1_out1_im;  // sfix17_En12
  reg signed [16:0] Delay20_out1_re;  // sfix17_En12
  reg signed [16:0] Delay20_out1_im;  // sfix17_En12
  wire signed [17:0] Sum5_sub_cast;  // sfix18_En12
  wire signed [17:0] Sum5_sub_cast_1;  // sfix18_En12
  wire signed [17:0] Sum5_sub_cast_2;  // sfix18_En12
  wire signed [17:0] Sum5_sub_cast_3;  // sfix18_En12
  wire signed [17:0] Sum5_out1_re;  // sfix18_En12
  wire signed [17:0] Sum5_out1_im;  // sfix18_En12
  reg signed [17:0] Delay25_out1_re;  // sfix18_En12
  reg signed [17:0] Delay25_out1_im;  // sfix18_En12
  wire signed [18:0] Sum6_add_cast;  // sfix19_En12
  wire signed [18:0] Sum6_add_cast_1;  // sfix19_En12
  wire signed [18:0] Sum6_add_temp;  // sfix19_En12
  wire signed [18:0] Sum6_add_cast_2;  // sfix19_En12
  wire signed [18:0] Sum6_add_cast_3;  // sfix19_En12
  wire signed [18:0] Sum6_add_temp_1;  // sfix19_En12
  wire signed [15:0] Sum6_out1_re;  // sfix16_En11
  wire signed [15:0] Sum6_out1_im;  // sfix16_En11
  reg signed [15:0] Delay15_reg_re [0:1];  // sfix16_En11 [2]
  reg signed [15:0] Delay15_reg_im [0:1];  // sfix16_En11 [2]
  wire signed [15:0] Delay15_reg_next_re [0:1];  // sfix16_En11 [2]
  wire signed [15:0] Delay15_reg_next_im [0:1];  // sfix16_En11 [2]
  wire signed [15:0] Delay15_out1_re;  // sfix16_En11
  wire signed [15:0] Delay15_out1_im;  // sfix16_En11
  reg signed [10:0] Delay34_out1;  // sfix11_En10
  reg signed [10:0] Delay29_out1;  // sfix11_En10
  reg signed [10:0] Delay19_out1;  // sfix11_En10
  reg signed [10:0] Delay24_out1;  // sfix11_En10
  reg signed [10:0] Delay14_reg [0:1];  // sfix11 [2]
  wire signed [10:0] Delay14_reg_next [0:1];  // sfix11_En10 [2]
  wire signed [10:0] Delay14_out1;  // sfix11_En10
  wire signed [26:0] Product1_mul_temp;  // sfix27_En21
  wire signed [26:0] Product1_mul_temp_1;  // sfix27_En21
  wire signed [15:0] Product1_out1_re;  // sfix16_En10
  wire signed [15:0] Product1_out1_im;  // sfix16_En10
  reg signed [15:0] Delay9_reg_re [0:1];  // sfix16_En10 [2]
  reg signed [15:0] Delay9_reg_im [0:1];  // sfix16_En10 [2]
  wire signed [15:0] Delay9_reg_next_re [0:1];  // sfix16_En10 [2]
  wire signed [15:0] Delay9_reg_next_im [0:1];  // sfix16_En10 [2]
  wire signed [15:0] Delay9_out1_re;  // sfix16_En10
  wire signed [15:0] Delay9_out1_im;  // sfix16_En10
  wire signed [15:0] Sum3_out1_re;  // sfix16_En10
  wire signed [15:0] Sum3_out1_im;  // sfix16_En10
  reg signed [15:0] Delay6_reg_re [0:1];  // sfix16_En10 [2]
  reg signed [15:0] Delay6_reg_im [0:1];  // sfix16_En10 [2]
  wire signed [15:0] Delay6_reg_next_re [0:1];  // sfix16_En10 [2]
  wire signed [15:0] Delay6_reg_next_im [0:1];  // sfix16_En10 [2]
  wire signed [15:0] Delay6_out1_re;  // sfix16_En10
  wire signed [15:0] Delay6_out1_im;  // sfix16_En10
  reg signed [10:0] Delay13_reg [0:1];  // sfix11 [2]
  wire signed [10:0] Delay13_reg_next [0:1];  // sfix11_En10 [2]
  wire signed [10:0] Delay13_out1;  // sfix11_En10
  reg signed [10:0] Delay7_reg [0:1];  // sfix11 [2]
  wire signed [10:0] Delay7_reg_next [0:1];  // sfix11_En10 [2]
  wire signed [10:0] Delay7_out1;  // sfix11_En10
  wire signed [26:0] Product2_mul_temp;  // sfix27_En20
  wire signed [26:0] Product2_mul_temp_1;  // sfix27_En20
  wire signed [15:0] Product2_out1_re;  // sfix16_En10
  wire signed [15:0] Product2_out1_im;  // sfix16_En10
  reg signed [15:0] Delay_reg_re [0:1];  // sfix16_En10 [2]
  reg signed [15:0] Delay_reg_im [0:1];  // sfix16_En10 [2]
  wire signed [15:0] Delay_reg_next_re [0:1];  // sfix16_En10 [2]
  wire signed [15:0] Delay_reg_next_im [0:1];  // sfix16_En10 [2]
  wire signed [15:0] Delay_out1_re;  // sfix16_En10
  wire signed [15:0] Delay_out1_im;  // sfix16_En10
  wire signed [18:0] Sum2_add_cast;  // sfix19_En12
  wire signed [18:0] Sum2_add_cast_1;  // sfix19_En12
  wire signed [18:0] Sum2_add_cast_2;  // sfix19_En12
  wire signed [18:0] Sum2_add_cast_3;  // sfix19_En12
  wire signed [18:0] Sum2_out1_re;  // sfix19_En12
  wire signed [18:0] Sum2_out1_im;  // sfix19_En12
  reg signed [31:0] Delay18_t_0_0;  // int32
  reg signed [31:0] Delay18_t_1;  // int32
  reg signed [31:0] Delay12_t_0_0;  // int32
  reg signed [31:0] Delay12_t_1;  // int32
  reg signed [31:0] Delay8_t_0_0;  // int32
  reg signed [31:0] Delay8_t_1;  // int32
  reg signed [31:0] Delay5_t_0_0;  // int32
  reg signed [31:0] Delay5_t_1;  // int32
  reg signed [31:0] Delay17_t_0_0;  // int32
  reg signed [31:0] Delay17_t_1;  // int32
  reg signed [31:0] Delay16_t_0_0;  // int32
  reg signed [31:0] Delay16_t_1;  // int32
  reg signed [31:0] Delay11_t_0_0;  // int32
  reg signed [31:0] Delay11_t_1;  // int32
  reg signed [31:0] Delay15_t_0_0;  // int32
  reg signed [31:0] Delay15_t_1;  // int32
  reg signed [31:0] Delay14_t_0_0;  // int32
  reg signed [31:0] Delay14_t_1;  // int32
  reg signed [31:0] Delay9_t_0_0;  // int32
  reg signed [31:0] Delay9_t_1;  // int32
  reg signed [31:0] Delay6_t_0_0;  // int32
  reg signed [31:0] Delay6_t_1;  // int32
  reg signed [31:0] Delay13_t_0_0;  // int32
  reg signed [31:0] Delay13_t_1;  // int32
  reg signed [31:0] Delay7_t_0_0;  // int32
  reg signed [31:0] Delay7_t_1;  // int32
  reg signed [31:0] Delay_t_0_0;  // int32
  reg signed [31:0] Delay_t_1;  // int32

  initial begin

    for(Delay15_t_1 = 32'sd0; Delay15_t_1 <= 32'sd1; Delay15_t_1 = Delay15_t_1 + 32'sd1) begin
      Delay15_reg_re[Delay15_t_1] = 16'sb0000000000000000;
      Delay15_reg_im[Delay15_t_1] = 16'sb0000000000000000;
    end


    for(Delay14_t_1 = 32'sd0; Delay14_t_1 <= 32'sd1; Delay14_t_1 = Delay14_t_1 + 32'sd1) begin
      Delay14_reg[Delay14_t_1] = 11'sb00000000000;
    end


    for(Delay9_t_1 = 32'sd0; Delay9_t_1 <= 32'sd1; Delay9_t_1 = Delay9_t_1 + 32'sd1) begin
      Delay9_reg_re[Delay9_t_1] = 16'sb0000000000000000;
      Delay9_reg_im[Delay9_t_1] = 16'sb0000000000000000;
    end


    for(Delay6_t_1 = 32'sd0; Delay6_t_1 <= 32'sd1; Delay6_t_1 = Delay6_t_1 + 32'sd1) begin
      Delay6_reg_re[Delay6_t_1] = 16'sb0000000000000000;
      Delay6_reg_im[Delay6_t_1] = 16'sb0000000000000000;
    end


    for(Delay7_t_1 = 32'sd0; Delay7_t_1 <= 32'sd1; Delay7_t_1 = Delay7_t_1 + 32'sd1) begin
      Delay7_reg[Delay7_t_1] = 11'sb00000000000;
    end


    for(Delay_t_1 = 32'sd0; Delay_t_1 <= 32'sd1; Delay_t_1 = Delay_t_1 + 32'sd1) begin
      Delay_reg_re[Delay_t_1] = 16'sb0000000000000000;
      Delay_reg_im[Delay_t_1] = 16'sb0000000000000000;
    end

  end

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1_re <= 16'sb0000000000000000;
        Delay1_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay1_out1_re <= In_re;
          Delay1_out1_im <= In_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay36_process
      if (reset == 1'b1) begin
        Delay36_out1_re <= 16'sb0000000000000000;
        Delay36_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay36_out1_re <= Delay1_out1_re;
          Delay36_out1_im <= Delay1_out1_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay33_process
      if (reset == 1'b1) begin
        Delay33_out1_re <= 16'sb0000000000000000;
        Delay33_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay33_out1_re <= Delay36_out1_re;
          Delay33_out1_im <= Delay36_out1_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay10_process
      if (reset == 1'b1) begin
        Delay10_out1_re <= 16'sb0000000000000000;
        Delay10_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay10_out1_re <= Delay33_out1_re;
          Delay10_out1_im <= Delay33_out1_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay23_process
      if (reset == 1'b1) begin
        Delay23_out1_re <= 16'sb0000000000000000;
        Delay23_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay23_out1_re <= Delay10_out1_re;
          Delay23_out1_im <= Delay10_out1_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay28_process
      if (reset == 1'b1) begin
        Delay28_out1_re <= 16'sb0000000000000000;
        Delay28_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay28_out1_re <= Delay23_out1_re;
          Delay28_out1_im <= Delay23_out1_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay18_process
      if (reset == 1'b1) begin
        for(Delay18_t_1 = 32'sd0; Delay18_t_1 <= 32'sd1; Delay18_t_1 = Delay18_t_1 + 32'sd1) begin
          Delay18_reg_re[Delay18_t_1] <= 16'sb0000000000000000;
          Delay18_reg_im[Delay18_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay18_t_0_0 = 32'sd0; Delay18_t_0_0 <= 32'sd1; Delay18_t_0_0 = Delay18_t_0_0 + 32'sd1) begin
            Delay18_reg_re[Delay18_t_0_0] <= Delay18_reg_next_re[Delay18_t_0_0];
            Delay18_reg_im[Delay18_t_0_0] <= Delay18_reg_next_im[Delay18_t_0_0];
          end
        end
      end
    end

  assign Delay18_out1_re = Delay18_reg_re[1];
  assign Delay18_out1_im = Delay18_reg_im[1];
  assign Delay18_reg_next_re[0] = Delay28_out1_re;
  assign Delay18_reg_next_im[0] = Delay28_out1_im;
  assign Delay18_reg_next_re[1] = Delay18_reg_re[0];
  assign Delay18_reg_next_im[1] = Delay18_reg_im[0];

  always @(posedge clk or posedge reset)
    begin : Delay12_process
      if (reset == 1'b1) begin
        for(Delay12_t_1 = 32'sd0; Delay12_t_1 <= 32'sd1; Delay12_t_1 = Delay12_t_1 + 32'sd1) begin
          Delay12_reg_re[Delay12_t_1] <= 16'sb0000000000000000;
          Delay12_reg_im[Delay12_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay12_t_0_0 = 32'sd0; Delay12_t_0_0 <= 32'sd1; Delay12_t_0_0 = Delay12_t_0_0 + 32'sd1) begin
            Delay12_reg_re[Delay12_t_0_0] <= Delay12_reg_next_re[Delay12_t_0_0];
            Delay12_reg_im[Delay12_t_0_0] <= Delay12_reg_next_im[Delay12_t_0_0];
          end
        end
      end
    end

  assign Delay12_out1_re = Delay12_reg_re[1];
  assign Delay12_out1_im = Delay12_reg_im[1];
  assign Delay12_reg_next_re[0] = Delay18_out1_re;
  assign Delay12_reg_next_im[0] = Delay18_out1_im;
  assign Delay12_reg_next_re[1] = Delay12_reg_re[0];
  assign Delay12_reg_next_im[1] = Delay12_reg_im[0];

  always @(posedge clk or posedge reset)
    begin : Delay8_process
      if (reset == 1'b1) begin
        for(Delay8_t_1 = 32'sd0; Delay8_t_1 <= 32'sd1; Delay8_t_1 = Delay8_t_1 + 32'sd1) begin
          Delay8_reg_re[Delay8_t_1] <= 16'sb0000000000000000;
          Delay8_reg_im[Delay8_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay8_t_0_0 = 32'sd0; Delay8_t_0_0 <= 32'sd1; Delay8_t_0_0 = Delay8_t_0_0 + 32'sd1) begin
            Delay8_reg_re[Delay8_t_0_0] <= Delay8_reg_next_re[Delay8_t_0_0];
            Delay8_reg_im[Delay8_t_0_0] <= Delay8_reg_next_im[Delay8_t_0_0];
          end
        end
      end
    end

  assign Delay8_out1_re = Delay8_reg_re[1];
  assign Delay8_out1_im = Delay8_reg_im[1];
  assign Delay8_reg_next_re[0] = Delay12_out1_re;
  assign Delay8_reg_next_im[0] = Delay12_out1_im;
  assign Delay8_reg_next_re[1] = Delay8_reg_re[0];
  assign Delay8_reg_next_im[1] = Delay8_reg_im[0];

  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        for(Delay5_t_1 = 32'sd0; Delay5_t_1 <= 32'sd1; Delay5_t_1 = Delay5_t_1 + 32'sd1) begin
          Delay5_reg_re[Delay5_t_1] <= 16'sb0000000000000000;
          Delay5_reg_im[Delay5_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay5_t_0_0 = 32'sd0; Delay5_t_0_0 <= 32'sd1; Delay5_t_0_0 = Delay5_t_0_0 + 32'sd1) begin
            Delay5_reg_re[Delay5_t_0_0] <= Delay5_reg_next_re[Delay5_t_0_0];
            Delay5_reg_im[Delay5_t_0_0] <= Delay5_reg_next_im[Delay5_t_0_0];
          end
        end
      end
    end

  assign Delay5_out1_re = Delay5_reg_re[1];
  assign Delay5_out1_im = Delay5_reg_im[1];
  assign Delay5_reg_next_re[0] = Delay8_out1_re;
  assign Delay5_reg_next_im[0] = Delay8_out1_im;
  assign Delay5_reg_next_re[1] = Delay5_reg_re[0];
  assign Delay5_reg_next_im[1] = Delay5_reg_im[0];

  assign divide_by_2_out1_re = In_re >>> 8'd1;
  assign divide_by_2_out1_im = In_im >>> 8'd1;

  always @(posedge clk or posedge reset)
    begin : Delay35_process
      if (reset == 1'b1) begin
        Delay35_out1_re <= 16'sb0000000000000000;
        Delay35_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay35_out1_re <= divide_by_2_out1_re;
          Delay35_out1_im <= divide_by_2_out1_im;
        end
      end
    end

  assign Sum9_sub_cast = {Delay36_out1_re[15], Delay36_out1_re};
  assign Sum9_sub_cast_1 = {Delay35_out1_re[15], Delay35_out1_re};
  assign Sum9_out1_re = Sum9_sub_cast - Sum9_sub_cast_1;
  assign Sum9_sub_cast_2 = {Delay36_out1_im[15], Delay36_out1_im};
  assign Sum9_sub_cast_3 = {Delay35_out1_im[15], Delay35_out1_im};
  assign Sum9_out1_im = Sum9_sub_cast_2 - Sum9_sub_cast_3;

  always @(posedge clk or posedge reset)
    begin : Delay32_process
      if (reset == 1'b1) begin
        Delay32_out1_re <= 17'sb00000000000000000;
        Delay32_out1_im <= 17'sb00000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay32_out1_re <= Sum9_out1_re;
          Delay32_out1_im <= Sum9_out1_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1_re <= 16'sb0000000000000000;
        Delay2_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay2_out1_re <= Delay35_out1_re;
          Delay2_out1_im <= Delay35_out1_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay31_process
      if (reset == 1'b1) begin
        Delay31_out1_re <= 16'sb0000000000000000;
        Delay31_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay31_out1_re <= Delay2_out1_re;
          Delay31_out1_im <= Delay2_out1_im;
        end
      end
    end

  assign Sum10_add_cast = {Delay32_out1_re[16], Delay32_out1_re};
  assign Sum10_add_cast_1 = {{2{Delay31_out1_re[15]}}, Delay31_out1_re};
  assign Sum10_out1_re = Sum10_add_cast + Sum10_add_cast_1;
  assign Sum10_add_cast_2 = {Delay32_out1_im[16], Delay32_out1_im};
  assign Sum10_add_cast_3 = {{2{Delay31_out1_im[15]}}, Delay31_out1_im};
  assign Sum10_out1_im = Sum10_add_cast_2 + Sum10_add_cast_3;

  always @(posedge clk or posedge reset)
    begin : Delay22_process
      if (reset == 1'b1) begin
        Delay22_out1_re <= 18'sb000000000000000000;
        Delay22_out1_im <= 18'sb000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay22_out1_re <= Sum10_out1_re;
          Delay22_out1_im <= Sum10_out1_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1_re <= 16'sb0000000000000000;
        Delay3_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay3_out1_re <= Delay31_out1_re;
          Delay3_out1_im <= Delay31_out1_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay21_process
      if (reset == 1'b1) begin
        Delay21_out1_re <= 16'sb0000000000000000;
        Delay21_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay21_out1_re <= Delay3_out1_re;
          Delay21_out1_im <= Delay3_out1_im;
        end
      end
    end

  assign Sum4_sub_cast = {Delay22_out1_re[17], Delay22_out1_re};
  assign Sum4_sub_cast_1 = {{3{Delay21_out1_re[15]}}, Delay21_out1_re};
  assign Sum4_out1_re = Sum4_sub_cast - Sum4_sub_cast_1;
  assign Sum4_sub_cast_2 = {Delay22_out1_im[17], Delay22_out1_im};
  assign Sum4_sub_cast_3 = {{3{Delay21_out1_im[15]}}, Delay21_out1_im};
  assign Sum4_out1_im = Sum4_sub_cast_2 - Sum4_sub_cast_3;

  always @(posedge clk or posedge reset)
    begin : Delay27_process
      if (reset == 1'b1) begin
        Delay27_out1_re <= 19'sb0000000000000000000;
        Delay27_out1_im <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay27_out1_re <= Sum4_out1_re;
          Delay27_out1_im <= Sum4_out1_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay17_process
      if (reset == 1'b1) begin
        for(Delay17_t_1 = 32'sd0; Delay17_t_1 <= 32'sd1; Delay17_t_1 = Delay17_t_1 + 32'sd1) begin
          Delay17_reg_re[Delay17_t_1] <= 19'sb0000000000000000000;
          Delay17_reg_im[Delay17_t_1] <= 19'sb0000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay17_t_0_0 = 32'sd0; Delay17_t_0_0 <= 32'sd1; Delay17_t_0_0 = Delay17_t_0_0 + 32'sd1) begin
            Delay17_reg_re[Delay17_t_0_0] <= Delay17_reg_next_re[Delay17_t_0_0];
            Delay17_reg_im[Delay17_t_0_0] <= Delay17_reg_next_im[Delay17_t_0_0];
          end
        end
      end
    end

  assign Delay17_out1_re = Delay17_reg_re[1];
  assign Delay17_out1_im = Delay17_reg_im[1];
  assign Delay17_reg_next_re[0] = Delay27_out1_re;
  assign Delay17_reg_next_im[0] = Delay27_out1_im;
  assign Delay17_reg_next_re[1] = Delay17_reg_re[0];
  assign Delay17_reg_next_im[1] = Delay17_reg_im[0];

  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1_re <= 16'sb0000000000000000;
        Delay4_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay4_out1_re <= Delay21_out1_re;
          Delay4_out1_im <= Delay21_out1_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay26_process
      if (reset == 1'b1) begin
        Delay26_out1_re <= 16'sb0000000000000000;
        Delay26_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay26_out1_re <= Delay4_out1_re;
          Delay26_out1_im <= Delay4_out1_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay16_process
      if (reset == 1'b1) begin
        for(Delay16_t_1 = 32'sd0; Delay16_t_1 <= 32'sd1; Delay16_t_1 = Delay16_t_1 + 32'sd1) begin
          Delay16_reg_re[Delay16_t_1] <= 16'sb0000000000000000;
          Delay16_reg_im[Delay16_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay16_t_0_0 = 32'sd0; Delay16_t_0_0 <= 32'sd1; Delay16_t_0_0 = Delay16_t_0_0 + 32'sd1) begin
            Delay16_reg_re[Delay16_t_0_0] <= Delay16_reg_next_re[Delay16_t_0_0];
            Delay16_reg_im[Delay16_t_0_0] <= Delay16_reg_next_im[Delay16_t_0_0];
          end
        end
      end
    end

  assign Delay16_out1_re = Delay16_reg_re[1];
  assign Delay16_out1_im = Delay16_reg_im[1];
  assign Delay16_reg_next_re[0] = Delay26_out1_re;
  assign Delay16_reg_next_im[0] = Delay26_out1_im;
  assign Delay16_reg_next_re[1] = Delay16_reg_re[0];
  assign Delay16_reg_next_im[1] = Delay16_reg_im[0];

  assign Sum7_sub_cast = {Delay17_out1_re[18], Delay17_out1_re};
  assign Sum7_sub_cast_1 = {{4{Delay16_out1_re[15]}}, Delay16_out1_re};
  assign Sum7_sub_temp = Sum7_sub_cast - Sum7_sub_cast_1;
  assign Sum7_out1_re = Sum7_sub_temp[17:2];
  assign Sum7_sub_cast_2 = {Delay17_out1_im[18], Delay17_out1_im};
  assign Sum7_sub_cast_3 = {{4{Delay16_out1_im[15]}}, Delay16_out1_im};
  assign Sum7_sub_temp_1 = Sum7_sub_cast_2 - Sum7_sub_cast_3;
  assign Sum7_out1_im = Sum7_sub_temp_1[17:2];

  always @(posedge clk or posedge reset)
    begin : Delay11_process
      if (reset == 1'b1) begin
        for(Delay11_t_1 = 32'sd0; Delay11_t_1 <= 32'sd1; Delay11_t_1 = Delay11_t_1 + 32'sd1) begin
          Delay11_reg_re[Delay11_t_1] <= 16'sb0000000000000000;
          Delay11_reg_im[Delay11_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay11_t_0_0 = 32'sd0; Delay11_t_0_0 <= 32'sd1; Delay11_t_0_0 = Delay11_t_0_0 + 32'sd1) begin
            Delay11_reg_re[Delay11_t_0_0] <= Delay11_reg_next_re[Delay11_t_0_0];
            Delay11_reg_im[Delay11_t_0_0] <= Delay11_reg_next_im[Delay11_t_0_0];
          end
        end
      end
    end

  assign Delay11_out1_re = Delay11_reg_re[1];
  assign Delay11_out1_im = Delay11_reg_im[1];
  assign Delay11_reg_next_re[0] = Sum7_out1_re;
  assign Delay11_reg_next_im[0] = Sum7_out1_im;
  assign Delay11_reg_next_re[1] = Delay11_reg_re[0];
  assign Delay11_reg_next_im[1] = Delay11_reg_im[0];

  always @(posedge clk or posedge reset)
    begin : Delay30_process
      if (reset == 1'b1) begin
        Delay30_out1_re <= 16'sb0000000000000000;
        Delay30_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay30_out1_re <= Delay35_out1_re;
          Delay30_out1_im <= Delay35_out1_im;
        end
      end
    end

  assign Sum1_sub_cast = {Delay30_out1_re[15], Delay30_out1_re};
  assign Sum1_sub_cast_1 = {Delay31_out1_re[15], Delay31_out1_re};
  assign Sum1_out1_re = Sum1_sub_cast - Sum1_sub_cast_1;
  assign Sum1_sub_cast_2 = {Delay30_out1_im[15], Delay30_out1_im};
  assign Sum1_sub_cast_3 = {Delay31_out1_im[15], Delay31_out1_im};
  assign Sum1_out1_im = Sum1_sub_cast_2 - Sum1_sub_cast_3;

  always @(posedge clk or posedge reset)
    begin : Delay20_process
      if (reset == 1'b1) begin
        Delay20_out1_re <= 17'sb00000000000000000;
        Delay20_out1_im <= 17'sb00000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay20_out1_re <= Sum1_out1_re;
          Delay20_out1_im <= Sum1_out1_im;
        end
      end
    end

  assign Sum5_sub_cast = {Delay20_out1_re[16], Delay20_out1_re};
  assign Sum5_sub_cast_1 = {{2{Delay21_out1_re[15]}}, Delay21_out1_re};
  assign Sum5_out1_re = Sum5_sub_cast - Sum5_sub_cast_1;
  assign Sum5_sub_cast_2 = {Delay20_out1_im[16], Delay20_out1_im};
  assign Sum5_sub_cast_3 = {{2{Delay21_out1_im[15]}}, Delay21_out1_im};
  assign Sum5_out1_im = Sum5_sub_cast_2 - Sum5_sub_cast_3;

  always @(posedge clk or posedge reset)
    begin : Delay25_process
      if (reset == 1'b1) begin
        Delay25_out1_re <= 18'sb000000000000000000;
        Delay25_out1_im <= 18'sb000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay25_out1_re <= Sum5_out1_re;
          Delay25_out1_im <= Sum5_out1_im;
        end
      end
    end

  assign Sum6_add_cast = {{3{Delay26_out1_re[15]}}, Delay26_out1_re};
  assign Sum6_add_cast_1 = {Delay25_out1_re[17], Delay25_out1_re};
  assign Sum6_add_temp = Sum6_add_cast + Sum6_add_cast_1;
  assign Sum6_out1_re = ((Sum6_add_temp[18] == 1'b0) && (Sum6_add_temp[17:16] != 2'b00) ? 16'sb0111111111111111 :
              ((Sum6_add_temp[18] == 1'b1) && (Sum6_add_temp[17:16] != 2'b11) ? 16'sb1000000000000000 :
              $signed(Sum6_add_temp[16:1])));
  assign Sum6_add_cast_2 = {{3{Delay26_out1_im[15]}}, Delay26_out1_im};
  assign Sum6_add_cast_3 = {Delay25_out1_im[17], Delay25_out1_im};
  assign Sum6_add_temp_1 = Sum6_add_cast_2 + Sum6_add_cast_3;
  assign Sum6_out1_im = ((Sum6_add_temp_1[18] == 1'b0) && (Sum6_add_temp_1[17:16] != 2'b00) ? 16'sb0111111111111111 :
              ((Sum6_add_temp_1[18] == 1'b1) && (Sum6_add_temp_1[17:16] != 2'b11) ? 16'sb1000000000000000 :
              $signed(Sum6_add_temp_1[16:1])));

  always @(posedge clk)
    begin : Delay15_process
      if (enb_1_2_0) begin
        for(Delay15_t_0_0 = 32'sd0; Delay15_t_0_0 <= 32'sd1; Delay15_t_0_0 = Delay15_t_0_0 + 32'sd1) begin
          Delay15_reg_re[Delay15_t_0_0] <= Delay15_reg_next_re[Delay15_t_0_0];
          Delay15_reg_im[Delay15_t_0_0] <= Delay15_reg_next_im[Delay15_t_0_0];
        end
      end
    end

  assign Delay15_out1_re = Delay15_reg_re[1];
  assign Delay15_out1_im = Delay15_reg_im[1];
  assign Delay15_reg_next_re[0] = Sum6_out1_re;
  assign Delay15_reg_next_im[0] = Sum6_out1_im;
  assign Delay15_reg_next_re[1] = Delay15_reg_re[0];
  assign Delay15_reg_next_im[1] = Delay15_reg_im[0];

  always @(posedge clk or posedge reset)
    begin : Delay34_process
      if (reset == 1'b1) begin
        Delay34_out1 <= 11'sb00000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay34_out1 <= mu;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay29_process
      if (reset == 1'b1) begin
        Delay29_out1 <= 11'sb00000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay29_out1 <= Delay34_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay19_process
      if (reset == 1'b1) begin
        Delay19_out1 <= 11'sb00000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay19_out1 <= Delay29_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay24_process
      if (reset == 1'b1) begin
        Delay24_out1 <= 11'sb00000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay24_out1 <= Delay19_out1;
        end
      end
    end

  always @(posedge clk)
    begin : Delay14_process
      if (enb_1_2_0) begin
        for(Delay14_t_0_0 = 32'sd0; Delay14_t_0_0 <= 32'sd1; Delay14_t_0_0 = Delay14_t_0_0 + 32'sd1) begin
          Delay14_reg[Delay14_t_0_0] <= Delay14_reg_next[Delay14_t_0_0];
        end
      end
    end

  assign Delay14_out1 = Delay14_reg[1];
  assign Delay14_reg_next[0] = Delay24_out1;
  assign Delay14_reg_next[1] = Delay14_reg[0];

  assign Product1_mul_temp = Delay15_out1_re * Delay14_out1;
  assign Product1_out1_re = Product1_mul_temp[26:11] + $signed({1'b0, Product1_mul_temp[26] & (|Product1_mul_temp[10:0])});
  assign Product1_mul_temp_1 = Delay15_out1_im * Delay14_out1;
  assign Product1_out1_im = Product1_mul_temp_1[26:11] + $signed({1'b0, Product1_mul_temp_1[26] & (|Product1_mul_temp_1[10:0])});

  always @(posedge clk)
    begin : Delay9_process
      if (enb_1_2_0) begin
        for(Delay9_t_0_0 = 32'sd0; Delay9_t_0_0 <= 32'sd1; Delay9_t_0_0 = Delay9_t_0_0 + 32'sd1) begin
          Delay9_reg_re[Delay9_t_0_0] <= Delay9_reg_next_re[Delay9_t_0_0];
          Delay9_reg_im[Delay9_t_0_0] <= Delay9_reg_next_im[Delay9_t_0_0];
        end
      end
    end

  assign Delay9_out1_re = Delay9_reg_re[1];
  assign Delay9_out1_im = Delay9_reg_im[1];
  assign Delay9_reg_next_re[0] = Product1_out1_re;
  assign Delay9_reg_next_im[0] = Product1_out1_im;
  assign Delay9_reg_next_re[1] = Delay9_reg_re[0];
  assign Delay9_reg_next_im[1] = Delay9_reg_im[0];

  assign Sum3_out1_re = Delay11_out1_re + Delay9_out1_re;
  assign Sum3_out1_im = Delay11_out1_im + Delay9_out1_im;

  always @(posedge clk)
    begin : Delay6_process
      if (enb_1_2_0) begin
        for(Delay6_t_0_0 = 32'sd0; Delay6_t_0_0 <= 32'sd1; Delay6_t_0_0 = Delay6_t_0_0 + 32'sd1) begin
          Delay6_reg_re[Delay6_t_0_0] <= Delay6_reg_next_re[Delay6_t_0_0];
          Delay6_reg_im[Delay6_t_0_0] <= Delay6_reg_next_im[Delay6_t_0_0];
        end
      end
    end

  assign Delay6_out1_re = Delay6_reg_re[1];
  assign Delay6_out1_im = Delay6_reg_im[1];
  assign Delay6_reg_next_re[0] = Sum3_out1_re;
  assign Delay6_reg_next_im[0] = Sum3_out1_im;
  assign Delay6_reg_next_re[1] = Delay6_reg_re[0];
  assign Delay6_reg_next_im[1] = Delay6_reg_im[0];

  always @(posedge clk or posedge reset)
    begin : Delay13_process
      if (reset == 1'b1) begin
        for(Delay13_t_1 = 32'sd0; Delay13_t_1 <= 32'sd1; Delay13_t_1 = Delay13_t_1 + 32'sd1) begin
          Delay13_reg[Delay13_t_1] <= 11'sb00000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay13_t_0_0 = 32'sd0; Delay13_t_0_0 <= 32'sd1; Delay13_t_0_0 = Delay13_t_0_0 + 32'sd1) begin
            Delay13_reg[Delay13_t_0_0] <= Delay13_reg_next[Delay13_t_0_0];
          end
        end
      end
    end

  assign Delay13_out1 = Delay13_reg[1];
  assign Delay13_reg_next[0] = Delay14_out1;
  assign Delay13_reg_next[1] = Delay13_reg[0];

  always @(posedge clk)
    begin : Delay7_process
      if (enb_1_2_0) begin
        for(Delay7_t_0_0 = 32'sd0; Delay7_t_0_0 <= 32'sd1; Delay7_t_0_0 = Delay7_t_0_0 + 32'sd1) begin
          Delay7_reg[Delay7_t_0_0] <= Delay7_reg_next[Delay7_t_0_0];
        end
      end
    end

  assign Delay7_out1 = Delay7_reg[1];
  assign Delay7_reg_next[0] = Delay13_out1;
  assign Delay7_reg_next[1] = Delay7_reg[0];

  assign Product2_mul_temp = Delay6_out1_re * Delay7_out1;
  assign Product2_out1_re = Product2_mul_temp[25:10] + $signed({1'b0, Product2_mul_temp[26] & (|Product2_mul_temp[9:0])});
  assign Product2_mul_temp_1 = Delay6_out1_im * Delay7_out1;
  assign Product2_out1_im = Product2_mul_temp_1[25:10] + $signed({1'b0, Product2_mul_temp_1[26] & (|Product2_mul_temp_1[9:0])});

  always @(posedge clk)
    begin : Delay_process
      if (enb_1_2_0) begin
        for(Delay_t_0_0 = 32'sd0; Delay_t_0_0 <= 32'sd1; Delay_t_0_0 = Delay_t_0_0 + 32'sd1) begin
          Delay_reg_re[Delay_t_0_0] <= Delay_reg_next_re[Delay_t_0_0];
          Delay_reg_im[Delay_t_0_0] <= Delay_reg_next_im[Delay_t_0_0];
        end
      end
    end

  assign Delay_out1_re = Delay_reg_re[1];
  assign Delay_out1_im = Delay_reg_im[1];
  assign Delay_reg_next_re[0] = Product2_out1_re;
  assign Delay_reg_next_im[0] = Product2_out1_im;
  assign Delay_reg_next_re[1] = Delay_reg_re[0];
  assign Delay_reg_next_im[1] = Delay_reg_im[0];

  assign Sum2_add_cast = {{3{Delay5_out1_re[15]}}, Delay5_out1_re};
  assign Sum2_add_cast_1 = {Delay_out1_re[15], {Delay_out1_re, 2'b00}};
  assign Sum2_out1_re = Sum2_add_cast + Sum2_add_cast_1;
  assign Sum2_add_cast_2 = {{3{Delay5_out1_im[15]}}, Delay5_out1_im};
  assign Sum2_add_cast_3 = {Delay_out1_im[15], {Delay_out1_im, 2'b00}};
  assign Sum2_out1_im = Sum2_add_cast_2 + Sum2_add_cast_3;

  assign interpolant_re = Sum2_out1_re;

  assign interpolant_im = Sum2_out1_im;

endmodule  // Receiver_ip_src_Interpolation_Filter

