// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Peak_Search.v
// Created: 2026-05-26 18:50:49
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Peak_Search
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/Peak Search
// Hierarchy Level: 4
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Peak_Search
          (clk,
           reset,
           enb_1_2_0,
           corr,
           thresholdExceeded,
           validIn,
           timingOffset,
           done,
           success);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [31:0] corr;  // sfix32_En26
  input   thresholdExceeded;
  input   validIn;
  output  [10:0] timingOffset;  // ufix11
  output  done;
  output  success;


  wire [10:0] count_step;  // ufix11
  wire [10:0] count_from;  // ufix11
  reg [10:0] timing_Reference_out1;  // ufix11
  wire [10:0] count;  // ufix11
  wire need_to_wrap;
  wire [10:0] count_value;  // ufix11
  wire [10:0] count_1;  // ufix11
  wire Compare_To_Constant_out1;
  wire Logical_Operator_out1;
  wire Logical_Operator4_out1;
  reg signed [31:0] Unit_Delay_Enabled_Resettable_Synchronous_out1;  // sfix32_En26
  wire Relational_Operator_out1;
  reg [10:0] Unit_Delay_Enabled_Synchronous_out1;  // ufix11
  reg  Unit_Delay_Enabled_Resettable_Synchronous1_out1;

  // peak picker


  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 1132
  assign count_step = 11'b00000000001;

  assign count_from = 11'b00000000000;

  assign count = timing_Reference_out1 + count_step;

  assign need_to_wrap = timing_Reference_out1 == 11'b10001101100;

  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);

  assign count_1 = (validIn == 1'b0 ? timing_Reference_out1 :
              count_value);

  always @(posedge clk or posedge reset)
    begin : timing_Reference_process
      if (reset == 1'b1) begin
        timing_Reference_out1 <= 11'b00000000000;
      end
      else begin
        if (enb_1_2_0) begin
          timing_Reference_out1 <= count_1;
        end
      end
    end

  assign Compare_To_Constant_out1 = timing_Reference_out1 == 11'b10001101100;

  assign Logical_Operator_out1 = validIn & Compare_To_Constant_out1;

  always @(posedge clk or posedge reset)
    begin : Unit_Delay_Enabled_Resettable_Synchronous_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Resettable_Synchronous_out1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          if (Logical_Operator_out1 == 1'b1) begin
            Unit_Delay_Enabled_Resettable_Synchronous_out1 <= 32'sb00000000000000000000000000000000;
          end
          else begin
            if (Logical_Operator4_out1) begin
              Unit_Delay_Enabled_Resettable_Synchronous_out1 <= corr;
            end
          end
        end
      end
    end

  assign Relational_Operator_out1 = corr > Unit_Delay_Enabled_Resettable_Synchronous_out1;

  assign Logical_Operator4_out1 = Relational_Operator_out1 & thresholdExceeded;

  always @(posedge clk or posedge reset)
    begin : Unit_Delay_Enabled_Synchronous_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Synchronous_out1 <= 11'b00000000000;
      end
      else begin
        if (enb_1_2_0 && Logical_Operator4_out1) begin
          Unit_Delay_Enabled_Synchronous_out1 <= timing_Reference_out1;
        end
      end
    end

  assign timingOffset = Unit_Delay_Enabled_Synchronous_out1;

  assign done = Logical_Operator_out1;

  always @(posedge clk or posedge reset)
    begin : Unit_Delay_Enabled_Resettable_Synchronous1_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Resettable_Synchronous1_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          if (Logical_Operator_out1 == 1'b1) begin
            Unit_Delay_Enabled_Resettable_Synchronous1_out1 <= 1'b0;
          end
          else begin
            if (thresholdExceeded) begin
              Unit_Delay_Enabled_Resettable_Synchronous1_out1 <= thresholdExceeded;
            end
          end
        end
      end
    end

  assign success = Unit_Delay_Enabled_Resettable_Synchronous1_out1;

endmodule  // Receiver_ip_src_Peak_Search

