// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Quadrant_Correction.v
// Created: 2026-05-26 18:50:47
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Quadrant_Correction
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Coarse Frequency Compensator/Coarse 
// Frequency Estimator/Extract Frequency/HDL_CMA_core/Quadrant_Correctio
// Hierarchy Level: 7
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Quadrant_Correction
          (zin,
           QA_Control,
           zout);


  input   signed [34:0] zin;  // sfix35_En34
  input   [4:0] QA_Control;  // ufix5
  output  signed [34:0] zout;  // sfix35_En34


  wire yZeroXPositive;  // ufix1
  wire yZeroXNegative;  // ufix1
  wire [1:0] xyNegative;  // ufix2
  wire AbsRel;  // ufix1
  wire signed [34:0] pidivtwo;  // sfix35_En34
  wire signed [34:0] pivdivtwosubout;  // sfix35_En34
  wire signed [34:0] mux1out;  // sfix35_En34
  wire signed [35:0] Negation_cast;  // sfix36_En34
  wire signed [35:0] Negation_cast_1;  // sfix36_En34
  wire signed [36:0] Negation_cast_2;  // sfix37_En34
  wire signed [34:0] mux1out_negate;  // sfix35_En34
  wire signed [34:0] pionepos;  // sfix35_En34
  wire signed [34:0] pi_subtraction;  // sfix35_En34
  wire signed [34:0] pioneneg;  // sfix35_En34
  wire signed [34:0] negpi_addition;  // sfix35_En34
  wire signed [34:0] mux2out;  // sfix35_En34
  wire signed [34:0] mux5out;  // sfix35_En34
  wire signed [34:0] zero;  // sfix35_En34
  wire signed [34:0] mux6out;  // sfix35_En34


  assign yZeroXPositive = QA_Control[4];

  assign yZeroXNegative = QA_Control[3];

  assign xyNegative = QA_Control[1:0];

  assign AbsRel = QA_Control[2];

  assign pidivtwo = 35'sh200000000;

  assign pivdivtwosubout = pidivtwo - zin;

  assign mux1out = (AbsRel == 1'b0 ? pivdivtwosubout :
              zin);

  assign Negation_cast = {mux1out[34], mux1out};
  assign Negation_cast_1 =  - (Negation_cast);
  assign Negation_cast_2 = {Negation_cast_1[35], Negation_cast_1};
  assign mux1out_negate = Negation_cast_2[34:0];

  assign pionepos = 35'sh3FFFFFFFF;

  assign pi_subtraction = pionepos - mux1out;

  assign pioneneg = 35'sh400000000;

  assign negpi_addition = pioneneg + mux1out;

  assign mux2out = (xyNegative == 2'b00 ? mux1out :
              (xyNegative == 2'b01 ? mux1out_negate :
              (xyNegative == 2'b10 ? pi_subtraction :
              negpi_addition)));

  assign mux5out = (yZeroXNegative == 1'b0 ? mux2out :
              pionepos);

  assign zero = 35'sh000000000;

  assign mux6out = (yZeroXPositive == 1'b0 ? mux5out :
              zero);

  assign zout = mux6out;

endmodule  // Receiver_ip_src_Quadrant_Correction

