// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Average_Estimates.v
// Created: 2026-05-26 18:50:48
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Average_Estimates
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Phase Ambiguity Estimation and Correction/Average 
// Estimate
// Hierarchy Level: 4
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Average_Estimates
          (clk,
           reset,
           enb_1_2_0,
           endIn,
           estin_re,
           estin_im,
           validIn,
           avgEst_re,
           avgEst_im);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   endIn;
  input   signed [31:0] estin_re;  // sfix32_En29
  input   signed [31:0] estin_im;  // sfix32_En29
  input   validIn;
  output  signed [15:0] avgEst_re;  // sfix16_En14
  output  signed [15:0] avgEst_im;  // sfix16_En14


  reg  Delay2_out1;
  reg  Delay1_out1;
  reg  Delay3_out1;
  reg signed [31:0] Delay_out1_re;  // sfix32_En29
  reg signed [31:0] Delay_out1_im;  // sfix32_En29
  wire signed [23:0] Data_Type_Conversion_out1_re;  // sfix24_En13
  wire signed [23:0] Data_Type_Conversion_out1_im;  // sfix24_En13
  reg signed [23:0] Unit_Delay_Enabled_Resettable_Synchronous_out1_re;  // sfix24_En13
  reg signed [23:0] Unit_Delay_Enabled_Resettable_Synchronous_out1_im;  // sfix24_En13
  wire signed [24:0] Add_add_cast;  // sfix25_En13
  wire signed [24:0] Add_add_cast_1;  // sfix25_En13
  wire signed [24:0] Add_add_cast_2;  // sfix25_En13
  wire signed [24:0] Add_add_cast_3;  // sfix25_En13
  wire signed [24:0] Add_out1_re;  // sfix25_En13
  wire signed [24:0] Add_out1_im;  // sfix25_En13
  wire signed [23:0] Data_Type_Conversion1_out1_re;  // sfix24_En13
  wire signed [23:0] Data_Type_Conversion1_out1_im;  // sfix24_En13
  wire signed [23:0] Divide_by_8_out1_re;  // sfix24_En16
  wire signed [23:0] Divide_by_8_out1_im;  // sfix24_En16
  reg signed [23:0] Unit_Delay_Enabled_Synchronous_out1_re;  // sfix24_En16
  reg signed [23:0] Unit_Delay_Enabled_Synchronous_out1_im;  // sfix24_En16
  wire signed [15:0] Data_Type_Conversion2_out1_re;  // sfix16_En14
  wire signed [15:0] Data_Type_Conversion2_out1_im;  // sfix16_En14


  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay2_out1 <= endIn;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay1_out1 <= validIn;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay3_out1 <= Delay2_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1_re <= 32'sb00000000000000000000000000000000;
        Delay_out1_im <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay_out1_re <= estin_re;
          Delay_out1_im <= estin_im;
        end
      end
    end

  assign Data_Type_Conversion_out1_re = {{8{Delay_out1_re[31]}}, Delay_out1_re[31:16]};
  assign Data_Type_Conversion_out1_im = {{8{Delay_out1_im[31]}}, Delay_out1_im[31:16]};

  assign Add_add_cast = {Unit_Delay_Enabled_Resettable_Synchronous_out1_re[23], Unit_Delay_Enabled_Resettable_Synchronous_out1_re};
  assign Add_add_cast_1 = {Data_Type_Conversion_out1_re[23], Data_Type_Conversion_out1_re};
  assign Add_out1_re = Add_add_cast + Add_add_cast_1;
  assign Add_add_cast_2 = {Unit_Delay_Enabled_Resettable_Synchronous_out1_im[23], Unit_Delay_Enabled_Resettable_Synchronous_out1_im};
  assign Add_add_cast_3 = {Data_Type_Conversion_out1_im[23], Data_Type_Conversion_out1_im};
  assign Add_out1_im = Add_add_cast_2 + Add_add_cast_3;

  assign Data_Type_Conversion1_out1_re = Add_out1_re[23:0];
  assign Data_Type_Conversion1_out1_im = Add_out1_im[23:0];

  always @(posedge clk or posedge reset)
    begin : Unit_Delay_Enabled_Resettable_Synchronous_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Resettable_Synchronous_out1_re <= 24'sb000000000000000000000000;
        Unit_Delay_Enabled_Resettable_Synchronous_out1_im <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          if (Delay3_out1 == 1'b1) begin
            Unit_Delay_Enabled_Resettable_Synchronous_out1_re <= 24'sb000000000000000000000000;
            Unit_Delay_Enabled_Resettable_Synchronous_out1_im <= 24'sb000000000000000000000000;
          end
          else begin
            if (Delay1_out1) begin
              Unit_Delay_Enabled_Resettable_Synchronous_out1_re <= Data_Type_Conversion1_out1_re;
              Unit_Delay_Enabled_Resettable_Synchronous_out1_im <= Data_Type_Conversion1_out1_im;
            end
          end
        end
      end
    end

  assign Divide_by_8_out1_re = Unit_Delay_Enabled_Resettable_Synchronous_out1_re;
  assign Divide_by_8_out1_im = Unit_Delay_Enabled_Resettable_Synchronous_out1_im;

  always @(posedge clk or posedge reset)
    begin : Unit_Delay_Enabled_Synchronous_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Synchronous_out1_re <= 24'sb000000000000000000000000;
        Unit_Delay_Enabled_Synchronous_out1_im <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb_1_2_0 && Delay2_out1) begin
          Unit_Delay_Enabled_Synchronous_out1_re <= Divide_by_8_out1_re;
          Unit_Delay_Enabled_Synchronous_out1_im <= Divide_by_8_out1_im;
        end
      end
    end

  assign Data_Type_Conversion2_out1_re = Unit_Delay_Enabled_Synchronous_out1_re[17:2];
  assign Data_Type_Conversion2_out1_im = Unit_Delay_Enabled_Synchronous_out1_im[17:2];

  assign avgEst_re = Data_Type_Conversion2_out1_re;

  assign avgEst_im = Data_Type_Conversion2_out1_im;

endmodule  // Receiver_ip_src_Average_Estimates

