// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Preamble_Detector.v
// Created: 2026-05-26 18:50:49
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Preamble_Detector
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector
// Hierarchy Level: 3
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Preamble_Detector
          (clk,
           reset,
           enb_1_2_0,
           dataIn_re,
           dataIn_im,
           validIn,
           dataOut_re,
           dataOut_im,
           syncPulse,
           validOut);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [15:0] dataIn_re;  // sfix16_En14
  input   signed [15:0] dataIn_im;  // sfix16_En14
  input   validIn;
  output  signed [15:0] dataOut_re;  // sfix16_En14
  output  signed [15:0] dataOut_im;  // sfix16_En14
  output  syncPulse;
  output  validOut;


  reg signed [15:0] Delay1_out1_re;  // sfix16_En14
  reg signed [15:0] Delay1_out1_im;  // sfix16_En14
  reg  Delay2_out1;
  wire signed [31:0] Correlator_dataOut;  // sfix32_En26
  wire signed [31:0] Correlator_threshold;  // sfix32_En28
  wire Correlator_validOut;
  wire signed [33:0] Relational_Operator_cast;  // sfix34_En28
  wire signed [33:0] Relational_Operator_cast_1;  // sfix34_En28
  wire Relational_Operator_out1;
  wire [10:0] Peak_Search_timingOffset;  // ufix11
  wire done;
  wire success;
  reg [10:0] Delay11_out1;  // ufix11
  wire Logical_Operator_out1;
  reg  Delay12_out1;
  reg signed [15:0] Delay_reg_re [0:19];  // sfix16_En14 [20]
  reg signed [15:0] Delay_reg_im [0:19];  // sfix16_En14 [20]
  reg signed [15:0] Delay_reg_next_re [0:19];  // sfix16_En14 [20]
  reg signed [15:0] Delay_reg_next_im [0:19];  // sfix16_En14 [20]
  reg signed [15:0] Delay_out1_re;  // sfix16_En14
  reg signed [15:0] Delay_out1_im;  // sfix16_En14
  reg signed [15:0] Delay6_reg_re [0:5];  // sfix16_En14 [6]
  reg signed [15:0] Delay6_reg_im [0:5];  // sfix16_En14 [6]
  reg signed [15:0] Delay6_reg_next_re [0:5];  // sfix16_En14 [6]
  reg signed [15:0] Delay6_reg_next_im [0:5];  // sfix16_En14 [6]
  reg signed [15:0] Delay6_out1_re;  // sfix16_En14
  reg signed [15:0] Delay6_out1_im;  // sfix16_En14
  reg  [19:0] Delay7_reg;  // ufix1 [20]
  wire Delay7_out1;
  reg  [5:0] Delay8_reg;  // ufix1 [6]
  wire Delay8_out1;
  reg  [4531:0] Delay10_reg;  // ufix1 [4532]
  wire Delay10_out1;
  wire Constant_out1;
  wire signed [15:0] FIFO_out_re;  // sfix16_En14
  wire signed [15:0] FIFO_out_im;  // sfix16_En14
  reg signed [15:0] Delay13_out1_re;  // sfix16_En14
  reg signed [15:0] Delay13_out1_im;  // sfix16_En14
  reg  Delay14_out1;
  wire signed [15:0] synchronizedData_re;  // sfix16_En14
  wire signed [15:0] synchronizedData_im;  // sfix16_En14
  wire synchronizedValid;
  wire synchronizedPulse;
  reg signed [15:0] Delay3_out1_re;  // sfix16_En14
  reg signed [15:0] Delay3_out1_im;  // sfix16_En14
  reg  Delay4_out1;
  reg  Delay5_out1;
  reg signed [31:0] Delay_t_0_0;  // int32
  reg signed [31:0] Delay_t_0_1;  // int32
  reg signed [31:0] Delay_t_1;  // int32
  reg signed [31:0] Delay6_t_0_0;  // int32
  reg signed [31:0] Delay6_t_0_1;  // int32
  reg signed [31:0] Delay6_t_1;  // int32


  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1_re <= 16'sb0000000000000000;
        Delay1_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay1_out1_re <= dataIn_re;
          Delay1_out1_im <= dataIn_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay2_out1 <= validIn;
        end
      end
    end

  Receiver_ip_src_Correlator u_Correlator (.clk(clk),
                                           .reset(reset),
                                           .enb_1_2_0(enb_1_2_0),
                                           .dataIn_re(Delay1_out1_re),  // sfix16_En14
                                           .dataIn_im(Delay1_out1_im),  // sfix16_En14
                                           .validIn(Delay2_out1),
                                           .dataOut(Correlator_dataOut),  // sfix32_En26
                                           .threshold(Correlator_threshold),  // sfix32_En28
                                           .validOut(Correlator_validOut)
                                           );

  assign Relational_Operator_cast = {Correlator_dataOut, 2'b00};
  assign Relational_Operator_cast_1 = {{2{Correlator_threshold[31]}}, Correlator_threshold};
  assign Relational_Operator_out1 = Relational_Operator_cast > Relational_Operator_cast_1;

  Receiver_ip_src_Peak_Search u_Peak_Search (.clk(clk),
                                             .reset(reset),
                                             .enb_1_2_0(enb_1_2_0),
                                             .corr(Correlator_dataOut),  // sfix32_En26
                                             .thresholdExceeded(Relational_Operator_out1),
                                             .validIn(Correlator_validOut),
                                             .timingOffset(Peak_Search_timingOffset),  // ufix11
                                             .done(done),
                                             .success(success)
                                             );

  always @(posedge clk or posedge reset)
    begin : Delay11_process
      if (reset == 1'b1) begin
        Delay11_out1 <= 11'b00000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay11_out1 <= Peak_Search_timingOffset;
        end
      end
    end

  assign Logical_Operator_out1 = done & success;

  always @(posedge clk or posedge reset)
    begin : Delay12_process
      if (reset == 1'b1) begin
        Delay12_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay12_out1 <= Logical_Operator_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        for(Delay_t_1 = 32'sd0; Delay_t_1 <= 32'sd19; Delay_t_1 = Delay_t_1 + 32'sd1) begin
          Delay_reg_re[Delay_t_1] <= 16'sb0000000000000000;
          Delay_reg_im[Delay_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay_t_0_1 = 32'sd0; Delay_t_0_1 <= 32'sd19; Delay_t_0_1 = Delay_t_0_1 + 32'sd1) begin
            Delay_reg_re[Delay_t_0_1] <= Delay_reg_next_re[Delay_t_0_1];
            Delay_reg_im[Delay_t_0_1] <= Delay_reg_next_im[Delay_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay_out1_re = Delay_reg_re[19];
    Delay_out1_im = Delay_reg_im[19];
    Delay_reg_next_re[0] = Delay1_out1_re;
    Delay_reg_next_im[0] = Delay1_out1_im;

    for(Delay_t_0_0 = 32'sd0; Delay_t_0_0 <= 32'sd18; Delay_t_0_0 = Delay_t_0_0 + 32'sd1) begin
      Delay_reg_next_re[Delay_t_0_0 + 32'sd1] = Delay_reg_re[Delay_t_0_0];
      Delay_reg_next_im[Delay_t_0_0 + 32'sd1] = Delay_reg_im[Delay_t_0_0];
    end

  end

  always @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        for(Delay6_t_1 = 32'sd0; Delay6_t_1 <= 32'sd5; Delay6_t_1 = Delay6_t_1 + 32'sd1) begin
          Delay6_reg_re[Delay6_t_1] <= 16'sb0000000000000000;
          Delay6_reg_im[Delay6_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay6_t_0_1 = 32'sd0; Delay6_t_0_1 <= 32'sd5; Delay6_t_0_1 = Delay6_t_0_1 + 32'sd1) begin
            Delay6_reg_re[Delay6_t_0_1] <= Delay6_reg_next_re[Delay6_t_0_1];
            Delay6_reg_im[Delay6_t_0_1] <= Delay6_reg_next_im[Delay6_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay6_out1_re = Delay6_reg_re[5];
    Delay6_out1_im = Delay6_reg_im[5];
    Delay6_reg_next_re[0] = Delay_out1_re;
    Delay6_reg_next_im[0] = Delay_out1_im;

    for(Delay6_t_0_0 = 32'sd0; Delay6_t_0_0 <= 32'sd4; Delay6_t_0_0 = Delay6_t_0_0 + 32'sd1) begin
      Delay6_reg_next_re[Delay6_t_0_0 + 32'sd1] = Delay6_reg_re[Delay6_t_0_0];
      Delay6_reg_next_im[Delay6_t_0_0 + 32'sd1] = Delay6_reg_im[Delay6_t_0_0];
    end

  end

  always @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_reg <= {20{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay7_reg[0] <= Delay2_out1;
          Delay7_reg[32'sd19:32'sd1] <= Delay7_reg[32'sd18:32'sd0];
        end
      end
    end

  assign Delay7_out1 = Delay7_reg[19];

  always @(posedge clk or posedge reset)
    begin : Delay8_process
      if (reset == 1'b1) begin
        Delay8_reg <= {6{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay8_reg[0] <= Delay7_out1;
          Delay8_reg[32'sd5:32'sd1] <= Delay8_reg[32'sd4:32'sd0];
        end
      end
    end

  assign Delay8_out1 = Delay8_reg[5];

  always @(posedge clk or posedge reset)
    begin : Delay10_process
      if (reset == 1'b1) begin
        Delay10_reg <= {4532{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay10_reg[0] <= Delay8_out1;
          Delay10_reg[32'sd4531:32'sd1] <= Delay10_reg[32'sd4530:32'sd0];
        end
      end
    end

  assign Delay10_out1 = Delay10_reg[4531];

  assign Constant_out1 = 1'b0;

  Receiver_ip_src_FIFO u_FIFO (.clk(clk),
                               .reset(reset),
                               .enb_1_2_0(enb_1_2_0),
                               .in_re(Delay6_out1_re),  // sfix16_En14
                               .in_im(Delay6_out1_im),  // sfix16_En14
                               .push(Delay8_out1),
                               .pop(Delay10_out1),
                               .reset_1(Constant_out1),
                               .out_re(FIFO_out_re),  // sfix16_En14
                               .out_im(FIFO_out_im)  // sfix16_En14
                               );

  always @(posedge clk or posedge reset)
    begin : Delay13_process
      if (reset == 1'b1) begin
        Delay13_out1_re <= 16'sb0000000000000000;
        Delay13_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay13_out1_re <= FIFO_out_re;
          Delay13_out1_im <= FIFO_out_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay14_process
      if (reset == 1'b1) begin
        Delay14_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay14_out1 <= Delay10_out1;
        end
      end
    end

  Receiver_ip_src_Timing_Adjust u_Timing_Adjust (.clk(clk),
                                                 .reset(reset),
                                                 .enb_1_2_0(enb_1_2_0),
                                                 .timingOffset(Delay11_out1),  // ufix11
                                                 .timingOffsetValid(Delay12_out1),
                                                 .dataIn_re(Delay13_out1_re),  // sfix16_En14
                                                 .dataIn_im(Delay13_out1_im),  // sfix16_En14
                                                 .validIn(Delay14_out1),
                                                 .dataOut_re(synchronizedData_re),  // sfix16_En14
                                                 .dataOut_im(synchronizedData_im),  // sfix16_En14
                                                 .validOut(synchronizedValid),
                                                 .SyncPulse(synchronizedPulse)
                                                 );

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1_re <= 16'sb0000000000000000;
        Delay3_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay3_out1_re <= synchronizedData_re;
          Delay3_out1_im <= synchronizedData_im;
        end
      end
    end

  assign dataOut_re = Delay3_out1_re;

  assign dataOut_im = Delay3_out1_im;

  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay4_out1 <= synchronizedPulse;
        end
      end
    end

  assign syncPulse = Delay4_out1;

  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay5_out1 <= synchronizedValid;
        end
      end
    end

  assign validOut = Delay5_out1;

endmodule  // Receiver_ip_src_Preamble_Detector

