// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_NCO.v
// Created: 2026-05-26 18:50:47
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_NCO
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Carrier Synchronizer/Direct Digital 
// Synthesis/NC
// Hierarchy Level: 5
// Model version: 11.305
// 
// NCO
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_NCO
          (clk,
           reset,
           enb_1_2_0,
           inc,
           resetPhase,
           validIn,
           complexexp_re,
           complexexp_im);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [20:0] inc;  // sfix21
  input   resetPhase;
  input   validIn;
  output  signed [15:0] complexexp_re;  // sfix16_En14
  output  signed [15:0] complexexp_im;  // sfix16_En14


  reg  [4:0] outsel_reg_reg;  // ufix1 [5]
  wire outsel;
  wire signed [15:0] outzero_re;  // sfix16_En14
  wire signed [15:0] outzero_im;  // sfix16_En14
  wire signed [20:0] const0;  // sfix21
  wire signed [20:0] validPInc;  // sfix21
  reg signed [20:0] accphase_reg;  // sfix21
  wire signed [20:0] addpInc;  // sfix21
  wire signed [20:0] addPInc_rst;  // sfix21
  wire signed [20:0] pOffset;  // sfix21
  wire signed [20:0] accoffset;  // sfix21
  reg signed [20:0] accoffsete_reg;  // sfix21
  wire [10:0] dither;  // ufix11
  wire signed [20:0] casteddither;  // sfix21
  reg signed [20:0] dither_reg;  // sfix21
  wire signed [20:0] accumulator;  // sfix21
  wire [13:0] accQuantized;  // ufix14_E7
  wire signed [15:0] outs_re;  // sfix16_En14
  wire signed [15:0] outs_im;  // sfix16_En14
  wire signed [15:0] validouts_re;  // sfix16_En14
  wire signed [15:0] validouts_im;  // sfix16_En14
  reg signed [15:0] complexexp_re_1;  // sfix16_En14
  reg signed [15:0] complexexp_im_1;  // sfix16_En14


  always @(posedge clk or posedge reset)
    begin : outsel_reg_process
      if (reset == 1'b1) begin
        outsel_reg_reg <= {5{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          outsel_reg_reg[0] <= validIn;
          outsel_reg_reg[32'sd4:32'sd1] <= outsel_reg_reg[32'sd3:32'sd0];
        end
      end
    end

  assign outsel = outsel_reg_reg[4];

  assign outzero_re = 16'sb0000000000000000;
  assign outzero_im = 16'sb0000000000000000;

  // Constant Zero
  assign const0 = 21'sb000000000000000000000;

  assign validPInc = (validIn == 1'b0 ? const0 :
              inc);

  // Add phase increment
  assign addpInc = accphase_reg + validPInc;

  assign addPInc_rst = (resetPhase == 1'b0 ? addpInc :
              const0);

  // Phase increment accumulator register
  always @(posedge clk or posedge reset)
    begin : AccPhaseRegister_process
      if (reset == 1'b1) begin
        accphase_reg <= 21'sb000000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          accphase_reg <= addPInc_rst;
        end
      end
    end

  assign pOffset = 21'sb000000000000000000000;

  // Add phase offset
  assign accoffset = accphase_reg + pOffset;

  // Phase offset accumulator register
  always @(posedge clk or posedge reset)
    begin : AccOffsetRegister_process
      if (reset == 1'b1) begin
        accoffsete_reg <= 21'sb000000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          accoffsete_reg <= accoffset;
        end
      end
    end

  Receiver_ip_src_DitherGen u_dither_inst (.clk(clk),
                                           .reset(reset),
                                           .enb_1_2_0(enb_1_2_0),
                                           .validIn(validIn),
                                           .dither(dither)  // ufix11
                                           );

  assign casteddither = {10'b0, dither};

  // Dither input register
  always @(posedge clk or posedge reset)
    begin : DitherRegister_process
      if (reset == 1'b1) begin
        dither_reg <= 21'sb000000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          dither_reg <= casteddither;
        end
      end
    end

  // Add dither
  assign accumulator = accoffsete_reg + dither_reg;

  // Phase quantization
  assign accQuantized = accumulator[20:7];

  Receiver_ip_src_WaveformGen u_Wave_inst (.clk(clk),
                                           .reset(reset),
                                           .enb_1_2_0(enb_1_2_0),
                                           .phaseIdx(accQuantized),  // ufix14_E7
                                           .exp_re(outs_re),  // sfix16_En14
                                           .exp_im(outs_im)  // sfix16_En14
                                           );

  assign validouts_re = (outsel == 1'b0 ? outzero_re :
              outs_re);
  assign validouts_im = (outsel == 1'b0 ? outzero_im :
              outs_im);

  // Output register
  always @(posedge clk or posedge reset)
    begin : OutputRegister_process
      if (reset == 1'b1) begin
        complexexp_re_1 <= 16'sb0000000000000000;
        complexexp_im_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          complexexp_re_1 <= validouts_re;
          complexexp_im_1 <= validouts_im;
        end
      end
    end

  assign complexexp_re = complexexp_re_1;

  assign complexexp_im = complexexp_im_1;

endmodule  // Receiver_ip_src_NCO

