// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Filter.v
// Created: 2026-05-26 18:50:49
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Filter
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/Correlator/Discrete 
// FIR Filter/Filte
// Hierarchy Level: 6
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Filter
          (clk,
           reset,
           enb_1_2_0,
           dataIn_re,
           dataIn_im,
           validIn,
           syncReset,
           dataOut_re,
           dataOut_im,
           validOut);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [15:0] dataIn_re;  // sfix16_En14
  input   signed [15:0] dataIn_im;  // sfix16_En14
  input   validIn;
  input   syncReset;
  output  signed [15:0] dataOut_re;  // sfix16_En13
  output  signed [15:0] dataOut_im;  // sfix16_En13
  output  validOut;


  reg  dinRegVld;
  reg signed [15:0] dinReg_0_re;  // sfix16_En14
  wire signed [16:0] dinReg_cast_0_re;  // sfix17_En14
  reg signed [16:0] dinReg2_0_re;  // sfix17_En14
  wire signed [16:0] CoefOutP_0;  // sfix17_En19
  wire signed [16:0] CoefOutP_1;  // sfix17_En19
  wire signed [16:0] CoefOutP_2;  // sfix17_En19
  wire signed [16:0] CoefOutP_3;  // sfix17_En19
  wire signed [16:0] CoefOutP_4;  // sfix17_En19
  wire signed [16:0] CoefOutP_5;  // sfix17_En19
  wire signed [16:0] CoefOutP_6;  // sfix17_En19
  wire signed [16:0] CoefOutP_7;  // sfix17_En19
  wire signed [16:0] CoefOutP_8;  // sfix17_En19
  wire signed [16:0] CoefOutP_9;  // sfix17_En19
  wire signed [16:0] CoefOutP_10;  // sfix17_En19
  wire signed [16:0] CoefOutP_11;  // sfix17_En19
  wire signed [16:0] CoefOutP_12;  // sfix17_En19
  reg  dinReg2Vld;
  wire signed [47:0] dout_1_P;  // sfix48_En33
  wire doutVld;
  reg signed [15:0] dinReg_0_im;  // sfix16_En14
  wire signed [16:0] adder_add_cast;  // sfix17_En14
  wire signed [16:0] adder_add_cast_1;  // sfix17_En14
  wire signed [16:0] dinRealPImag_0;  // sfix17_En14
  reg signed [16:0] dinReg2_0_P;  // sfix17_En14
  wire signed [16:0] CoefOutI_0;  // sfix17_En19
  wire signed [16:0] CoefOutI_1;  // sfix17_En19
  wire signed [16:0] CoefOutI_2;  // sfix17_En19
  wire signed [16:0] CoefOutI_3;  // sfix17_En19
  wire signed [16:0] CoefOutI_4;  // sfix17_En19
  wire signed [16:0] CoefOutI_5;  // sfix17_En19
  wire signed [16:0] CoefOutI_6;  // sfix17_En19
  wire signed [16:0] CoefOutI_7;  // sfix17_En19
  wire signed [16:0] CoefOutI_8;  // sfix17_En19
  wire signed [16:0] CoefOutI_9;  // sfix17_En19
  wire signed [16:0] CoefOutI_10;  // sfix17_En19
  wire signed [16:0] CoefOutI_11;  // sfix17_En19
  wire signed [16:0] CoefOutI_12;  // sfix17_En19
  wire signed [47:0] dout_1_I;  // sfix48_En33
  wire doutVld_IdeadOut;
  wire signed [48:0] subtractor_sub_cast;  // sfix49_En33
  wire signed [48:0] subtractor_sub_cast_1;  // sfix49_En33
  wire signed [48:0] dout_1_r;  // sfix49_En33
  wire signed [15:0] dout_1_cast_r;  // sfix16_En13
  reg signed [15:0] dout_1_re;  // sfix16_En13
  wire signed [16:0] dinReg2_cast_0_im;  // sfix17_En14
  reg signed [16:0] dinReg2_0_im;  // sfix17_En14
  wire signed [16:0] CoefOutS_0;  // sfix17_En19
  wire signed [16:0] CoefOutS_1;  // sfix17_En19
  wire signed [16:0] CoefOutS_2;  // sfix17_En19
  wire signed [16:0] CoefOutS_3;  // sfix17_En19
  wire signed [16:0] CoefOutS_4;  // sfix17_En19
  wire signed [16:0] CoefOutS_5;  // sfix17_En19
  wire signed [16:0] CoefOutS_6;  // sfix17_En19
  wire signed [16:0] CoefOutS_7;  // sfix17_En19
  wire signed [16:0] CoefOutS_8;  // sfix17_En19
  wire signed [16:0] CoefOutS_9;  // sfix17_En19
  wire signed [16:0] CoefOutS_10;  // sfix17_En19
  wire signed [16:0] CoefOutS_11;  // sfix17_En19
  wire signed [16:0] CoefOutS_12;  // sfix17_En19
  wire signed [47:0] dout_1_M;  // sfix48_En33
  wire doutVld_MdeadOut;
  wire signed [48:0] adder_add_cast_2;  // sfix49_En33
  wire signed [48:0] adder_add_cast_3;  // sfix49_En33
  wire signed [48:0] dout_1_i_1;  // sfix49_En33
  wire signed [15:0] dout_1_cast_i;  // sfix16_En13
  reg signed [15:0] dout_1_im;  // sfix16_En13
  reg  doutVldReg;


  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        dinRegVld <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            dinRegVld <= 1'b0;
          end
          else begin
            dinRegVld <= validIn;
          end
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        dinReg_0_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            dinReg_0_re <= 16'sb0000000000000000;
          end
          else begin
            if (validIn) begin
              dinReg_0_re <= dataIn_re;
            end
          end
        end
      end
    end

  assign dinReg_cast_0_re = {dinReg_0_re[15], dinReg_0_re};

  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        dinReg2_0_re <= 17'sb00000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_re <= 17'sb00000000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_re <= dinReg_cast_0_re;
            end
          end
        end
      end
    end

  Receiver_ip_src_FilterCoef u_CoefTableP_1 (.CoefOutP_0(CoefOutP_0),  // sfix17_En19
                                             .CoefOutP_1(CoefOutP_1),  // sfix17_En19
                                             .CoefOutP_2(CoefOutP_2),  // sfix17_En19
                                             .CoefOutP_3(CoefOutP_3),  // sfix17_En19
                                             .CoefOutP_4(CoefOutP_4),  // sfix17_En19
                                             .CoefOutP_5(CoefOutP_5),  // sfix17_En19
                                             .CoefOutP_6(CoefOutP_6),  // sfix17_En19
                                             .CoefOutP_7(CoefOutP_7),  // sfix17_En19
                                             .CoefOutP_8(CoefOutP_8),  // sfix17_En19
                                             .CoefOutP_9(CoefOutP_9),  // sfix17_En19
                                             .CoefOutP_10(CoefOutP_10),  // sfix17_En19
                                             .CoefOutP_11(CoefOutP_11),  // sfix17_En19
                                             .CoefOutP_12(CoefOutP_12)  // sfix17_En19
                                             );

  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        dinReg2Vld <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            dinReg2Vld <= 1'b0;
          end
          else begin
            dinReg2Vld <= dinRegVld;
          end
        end
      end
    end

  Receiver_ip_src_subFilter u_subFilter_1_reP (.clk(clk),
                                               .reset(reset),
                                               .enb_1_2_0(enb_1_2_0),
                                               .dinReg2_0_re(dinReg2_0_re),  // sfix17_En14
                                               .coefIn_0(CoefOutP_0),  // sfix17_En19
                                               .coefIn_1(CoefOutP_1),  // sfix17_En19
                                               .coefIn_2(CoefOutP_2),  // sfix17_En19
                                               .coefIn_3(CoefOutP_3),  // sfix17_En19
                                               .coefIn_4(CoefOutP_4),  // sfix17_En19
                                               .coefIn_5(CoefOutP_5),  // sfix17_En19
                                               .coefIn_6(CoefOutP_6),  // sfix17_En19
                                               .coefIn_7(CoefOutP_7),  // sfix17_En19
                                               .coefIn_8(CoefOutP_8),  // sfix17_En19
                                               .coefIn_9(CoefOutP_9),  // sfix17_En19
                                               .coefIn_10(CoefOutP_10),  // sfix17_En19
                                               .coefIn_11(CoefOutP_11),  // sfix17_En19
                                               .coefIn_12(CoefOutP_12),  // sfix17_En19
                                               .dinRegVld(dinReg2Vld),
                                               .syncReset(syncReset),
                                               .dout_1_re(dout_1_P),  // sfix48_En33
                                               .doutVld(doutVld)
                                               );

  always @(posedge clk or posedge reset)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        dinReg_0_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            dinReg_0_im <= 16'sb0000000000000000;
          end
          else begin
            if (validIn) begin
              dinReg_0_im <= dataIn_im;
            end
          end
        end
      end
    end

  assign adder_add_cast = {dinReg_0_re[15], dinReg_0_re};
  assign adder_add_cast_1 = {dinReg_0_im[15], dinReg_0_im};
  assign dinRealPImag_0 = adder_add_cast + adder_add_cast_1;

  always @(posedge clk or posedge reset)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        dinReg2_0_P <= 17'sb00000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_P <= 17'sb00000000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_P <= dinRealPImag_0;
            end
          end
        end
      end
    end

  Receiver_ip_src_FilterCoef_block1 u_CoefTableI_1 (.CoefOutI_0(CoefOutI_0),  // sfix17_En19
                                                    .CoefOutI_1(CoefOutI_1),  // sfix17_En19
                                                    .CoefOutI_2(CoefOutI_2),  // sfix17_En19
                                                    .CoefOutI_3(CoefOutI_3),  // sfix17_En19
                                                    .CoefOutI_4(CoefOutI_4),  // sfix17_En19
                                                    .CoefOutI_5(CoefOutI_5),  // sfix17_En19
                                                    .CoefOutI_6(CoefOutI_6),  // sfix17_En19
                                                    .CoefOutI_7(CoefOutI_7),  // sfix17_En19
                                                    .CoefOutI_8(CoefOutI_8),  // sfix17_En19
                                                    .CoefOutI_9(CoefOutI_9),  // sfix17_En19
                                                    .CoefOutI_10(CoefOutI_10),  // sfix17_En19
                                                    .CoefOutI_11(CoefOutI_11),  // sfix17_En19
                                                    .CoefOutI_12(CoefOutI_12)  // sfix17_En19
                                                    );

  Receiver_ip_src_subFilter u_subFilter_1_im (.clk(clk),
                                              .reset(reset),
                                              .enb_1_2_0(enb_1_2_0),
                                              .dinReg2_0_re(dinReg2_0_P),  // sfix17_En14
                                              .coefIn_0(CoefOutI_0),  // sfix17_En19
                                              .coefIn_1(CoefOutI_1),  // sfix17_En19
                                              .coefIn_2(CoefOutI_2),  // sfix17_En19
                                              .coefIn_3(CoefOutI_3),  // sfix17_En19
                                              .coefIn_4(CoefOutI_4),  // sfix17_En19
                                              .coefIn_5(CoefOutI_5),  // sfix17_En19
                                              .coefIn_6(CoefOutI_6),  // sfix17_En19
                                              .coefIn_7(CoefOutI_7),  // sfix17_En19
                                              .coefIn_8(CoefOutI_8),  // sfix17_En19
                                              .coefIn_9(CoefOutI_9),  // sfix17_En19
                                              .coefIn_10(CoefOutI_10),  // sfix17_En19
                                              .coefIn_11(CoefOutI_11),  // sfix17_En19
                                              .coefIn_12(CoefOutI_12),  // sfix17_En19
                                              .dinRegVld(dinReg2Vld),
                                              .syncReset(syncReset),
                                              .dout_1_re(dout_1_I),  // sfix48_En33
                                              .doutVld(doutVld_IdeadOut)
                                              );

  assign subtractor_sub_cast = {dout_1_P[47], dout_1_P};
  assign subtractor_sub_cast_1 = {dout_1_I[47], dout_1_I};
  assign dout_1_r = subtractor_sub_cast - subtractor_sub_cast_1;

  assign dout_1_cast_r = dout_1_r[35:20];

  always @(posedge clk or posedge reset)
    begin : intdelay_6_process
      if (reset == 1'b1) begin
        dout_1_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            dout_1_re <= 16'sb0000000000000000;
          end
          else begin
            dout_1_re <= dout_1_cast_r;
          end
        end
      end
    end

  assign dataOut_re = dout_1_re;

  assign dinReg2_cast_0_im = {dinReg_0_im[15], dinReg_0_im};

  always @(posedge clk or posedge reset)
    begin : intdelay_7_process
      if (reset == 1'b1) begin
        dinReg2_0_im <= 17'sb00000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_im <= 17'sb00000000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_im <= dinReg2_cast_0_im;
            end
          end
        end
      end
    end

  Receiver_ip_src_FilterCoef_block u_CoefTableS_1 (.CoefOutS_0(CoefOutS_0),  // sfix17_En19
                                                   .CoefOutS_1(CoefOutS_1),  // sfix17_En19
                                                   .CoefOutS_2(CoefOutS_2),  // sfix17_En19
                                                   .CoefOutS_3(CoefOutS_3),  // sfix17_En19
                                                   .CoefOutS_4(CoefOutS_4),  // sfix17_En19
                                                   .CoefOutS_5(CoefOutS_5),  // sfix17_En19
                                                   .CoefOutS_6(CoefOutS_6),  // sfix17_En19
                                                   .CoefOutS_7(CoefOutS_7),  // sfix17_En19
                                                   .CoefOutS_8(CoefOutS_8),  // sfix17_En19
                                                   .CoefOutS_9(CoefOutS_9),  // sfix17_En19
                                                   .CoefOutS_10(CoefOutS_10),  // sfix17_En19
                                                   .CoefOutS_11(CoefOutS_11),  // sfix17_En19
                                                   .CoefOutS_12(CoefOutS_12)  // sfix17_En19
                                                   );

  Receiver_ip_src_subFilter u_subFilter_1_reS (.clk(clk),
                                               .reset(reset),
                                               .enb_1_2_0(enb_1_2_0),
                                               .dinReg2_0_re(dinReg2_0_im),  // sfix17_En14
                                               .coefIn_0(CoefOutS_0),  // sfix17_En19
                                               .coefIn_1(CoefOutS_1),  // sfix17_En19
                                               .coefIn_2(CoefOutS_2),  // sfix17_En19
                                               .coefIn_3(CoefOutS_3),  // sfix17_En19
                                               .coefIn_4(CoefOutS_4),  // sfix17_En19
                                               .coefIn_5(CoefOutS_5),  // sfix17_En19
                                               .coefIn_6(CoefOutS_6),  // sfix17_En19
                                               .coefIn_7(CoefOutS_7),  // sfix17_En19
                                               .coefIn_8(CoefOutS_8),  // sfix17_En19
                                               .coefIn_9(CoefOutS_9),  // sfix17_En19
                                               .coefIn_10(CoefOutS_10),  // sfix17_En19
                                               .coefIn_11(CoefOutS_11),  // sfix17_En19
                                               .coefIn_12(CoefOutS_12),  // sfix17_En19
                                               .dinRegVld(dinReg2Vld),
                                               .syncReset(syncReset),
                                               .dout_1_re(dout_1_M),  // sfix48_En33
                                               .doutVld(doutVld_MdeadOut)
                                               );

  assign adder_add_cast_2 = {dout_1_M[47], dout_1_M};
  assign adder_add_cast_3 = {dout_1_I[47], dout_1_I};
  assign dout_1_i_1 = adder_add_cast_2 + adder_add_cast_3;

  assign dout_1_cast_i = dout_1_i_1[35:20];

  always @(posedge clk or posedge reset)
    begin : intdelay_8_process
      if (reset == 1'b1) begin
        dout_1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            dout_1_im <= 16'sb0000000000000000;
          end
          else begin
            dout_1_im <= dout_1_cast_i;
          end
        end
      end
    end

  assign dataOut_im = dout_1_im;

  always @(posedge clk or posedge reset)
    begin : intdelay_9_process
      if (reset == 1'b1) begin
        doutVldReg <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            doutVldReg <= 1'b0;
          end
          else begin
            doutVldReg <= doutVld;
          end
        end
      end
    end

  assign validOut = doutVldReg;

endmodule  // Receiver_ip_src_Filter

