// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Rate_Handle.v
// Created: 2026-05-26 18:50:49
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Rate_Handle
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Symbol Synchronizer/Rate Handle
// Hierarchy Level: 4
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Rate_Handle
          (clk,
           reset,
           enb_1_2_0,
           dataIn_re,
           dataIn_im,
           strobe,
           validIn,
           dataOut_re,
           dataOut_im,
           validOut);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [15:0] dataIn_re;  // sfix16_En14
  input   signed [15:0] dataIn_im;  // sfix16_En14
  input   strobe;
  input   validIn;
  output  signed [15:0] dataOut_re;  // sfix16_En14
  output  signed [15:0] dataOut_im;  // sfix16_En14
  output  validOut;


  wire [1:0] count_step;  // ufix2
  wire [1:0] count_from;  // ufix2
  reg [1:0] HDL_Counter_out1;  // ufix2
  wire [1:0] count;  // ufix2
  wire need_to_wrap;
  wire [1:0] count_value;  // ufix2
  wire [1:0] count_1;  // ufix2
  wire Compare_To_Constant_out1;
  wire Logical_Operator_out1;
  wire Constant_out1;
  wire signed [15:0] FIFO_out_re;  // sfix16_En14
  wire signed [15:0] FIFO_out_im;  // sfix16_En14
  wire FIFO_validPop;


  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 3
  assign count_step = 2'b01;

  assign count_from = 2'b00;

  assign count = HDL_Counter_out1 + count_step;

  assign need_to_wrap = HDL_Counter_out1 == 2'b11;

  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);

  assign count_1 = (validIn == 1'b0 ? HDL_Counter_out1 :
              count_value);

  always @(posedge clk or posedge reset)
    begin : HDL_Counter_process
      if (reset == 1'b1) begin
        HDL_Counter_out1 <= 2'b00;
      end
      else begin
        if (enb_1_2_0) begin
          HDL_Counter_out1 <= count_1;
        end
      end
    end

  assign Compare_To_Constant_out1 = HDL_Counter_out1 == 2'b00;

  assign Logical_Operator_out1 = validIn & Compare_To_Constant_out1;

  assign Constant_out1 = 1'b0;

  Receiver_ip_src_FIFO_block u_FIFO (.clk(clk),
                                     .reset(reset),
                                     .enb_1_2_0(enb_1_2_0),
                                     .in_re(dataIn_re),  // sfix16_En14
                                     .in_im(dataIn_im),  // sfix16_En14
                                     .push(strobe),
                                     .pop(Logical_Operator_out1),
                                     .reset_1(Constant_out1),
                                     .out_re(FIFO_out_re),  // sfix16_En14
                                     .out_im(FIFO_out_im),  // sfix16_En14
                                     .validPop(FIFO_validPop)
                                     );

  assign dataOut_re = FIFO_out_re;

  assign dataOut_im = FIFO_out_im;

  assign validOut = FIFO_validPop;

endmodule  // Receiver_ip_src_Rate_Handle

