// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Phase_Ambiguity_Estimator.v
// Created: 2026-05-26 18:50:49
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Phase_Ambiguity_Estimator
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Phase Ambiguity Estimation and Correction/Phase 
// Ambiguity Estimato
// Hierarchy Level: 4
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Phase_Ambiguity_Estimator
          (clk,
           reset,
           enb_1_2_0,
           dataIn_re,
           dataIn_im,
           syncPulse,
           validIn,
           endOut,
           estOut_re,
           estOut_im,
           validOut);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [15:0] dataIn_re;  // sfix16_En14
  input   signed [15:0] dataIn_im;  // sfix16_En14
  input   syncPulse;
  input   validIn;
  output  endOut;
  output  signed [31:0] estOut_re;  // sfix32_En29
  output  signed [31:0] estOut_im;  // sfix32_En29
  output  validOut;


  wire [2:0] count_step;  // ufix3
  wire [2:0] count_from;  // ufix3
  wire [2:0] count_reset;  // ufix3
  reg [2:0] HDL_Counter_out1;  // ufix3
  wire [2:0] count;  // ufix3
  wire need_to_wrap;
  wire [2:0] count_value;  // ufix3
  wire Subsystem1_validOut;
  wire [2:0] count_1;  // ufix3
  wire Subsystem_Out2;
  wire [2:0] count_2;  // ufix3
  wire Compare_To_Constant_out1;
  wire Logical_Operator_out1;
  reg  Delay3_out1;
  reg  [1:0] Delay7_reg;  // ufix1 [2]
  wire Delay7_out1;
  reg  [1:0] Delay11_reg;  // ufix1 [2]
  wire Delay11_out1;
  reg signed [15:0] Delay1_out1_re;  // sfix16_En14
  reg signed [15:0] Delay1_out1_im;  // sfix16_En14
  reg signed [15:0] Delay5_reg_re [0:1];  // sfix16_En14 [2]
  reg signed [15:0] Delay5_reg_im [0:1];  // sfix16_En14 [2]
  wire signed [15:0] Delay5_reg_next_re [0:1];  // sfix16_En14 [2]
  wire signed [15:0] Delay5_reg_next_im [0:1];  // sfix16_En14 [2]
  wire signed [15:0] Delay5_out1_re;  // sfix16_En14
  wire signed [15:0] Delay5_out1_im;  // sfix16_En14
  reg [2:0] Delay8_out1;  // ufix3
  wire signed [15:0] Direct_Lookup_Table_n_D_table_data_re [0:7];  // sfix16_En15 [8]
  wire signed [15:0] Direct_Lookup_Table_n_D_table_data_im [0:7];  // sfix16_En15 [8]
  wire signed [15:0] Direct_Lookup_Table_n_D_out1_re;  // sfix16_En15
  wire signed [15:0] Direct_Lookup_Table_n_D_out1_im;  // sfix16_En15
  wire signed [16:0] conj_cast;  // sfix17_En15
  wire signed [16:0] conj_cast_1;  // sfix17_En15
  wire signed [15:0] Math_Function_out1_re;  // sfix16_En15
  wire signed [15:0] Math_Function_out1_im;  // sfix16_En15
  reg signed [15:0] Delay4_reg_re [0:1];  // sfix16_En15 [2]
  reg signed [15:0] Delay4_reg_im [0:1];  // sfix16_En15 [2]
  wire signed [15:0] Delay4_reg_next_re [0:1];  // sfix16_En15 [2]
  wire signed [15:0] Delay4_reg_next_im [0:1];  // sfix16_En15 [2]
  wire signed [15:0] Delay4_out1_re;  // sfix16_En15
  wire signed [15:0] Delay4_out1_im;  // sfix16_En15
  wire signed [31:0] Product_mul_temp;  // sfix32_En29
  wire signed [31:0] Product_mul_temp_1;  // sfix32_En29
  wire signed [31:0] Product_mul_temp_2;  // sfix32_En29
  wire signed [31:0] Product_mul_temp_3;  // sfix32_En29
  wire signed [31:0] Product_out1_re;  // sfix32_En29
  wire signed [31:0] Product_out1_im;  // sfix32_En29
  reg signed [31:0] Delay9_reg_re [0:1];  // sfix32_En29 [2]
  reg signed [31:0] Delay9_reg_im [0:1];  // sfix32_En29 [2]
  wire signed [31:0] Delay9_reg_next_re [0:1];  // sfix32_En29 [2]
  wire signed [31:0] Delay9_reg_next_im [0:1];  // sfix32_En29 [2]
  wire signed [31:0] Delay9_out1_re;  // sfix32_En29
  wire signed [31:0] Delay9_out1_im;  // sfix32_En29
  reg  Delay2_out1;
  reg  [1:0] Delay6_reg;  // ufix1 [2]
  wire Delay6_out1;
  reg  [1:0] Delay10_reg;  // ufix1 [2]
  wire Delay10_out1;
  reg signed [31:0] Delay5_t_0_0;  // int32
  reg signed [31:0] Delay5_t_1;  // int32
  reg signed [31:0] Delay4_t_0_0;  // int32
  reg signed [31:0] Delay4_t_1;  // int32
  reg signed [31:0] Delay9_t_0_0;  // int32
  reg signed [31:0] Delay9_t_1;  // int32

  initial begin

    for(Delay5_t_1 = 32'sd0; Delay5_t_1 <= 32'sd1; Delay5_t_1 = Delay5_t_1 + 32'sd1) begin
      Delay5_reg_re[Delay5_t_1] = 16'sb0000000000000000;
      Delay5_reg_im[Delay5_t_1] = 16'sb0000000000000000;
    end


    for(Delay4_t_1 = 32'sd0; Delay4_t_1 <= 32'sd1; Delay4_t_1 = Delay4_t_1 + 32'sd1) begin
      Delay4_reg_re[Delay4_t_1] = 16'sb0000000000000000;
      Delay4_reg_im[Delay4_t_1] = 16'sb0000000000000000;
    end


    for(Delay9_t_1 = 32'sd0; Delay9_t_1 <= 32'sd1; Delay9_t_1 = Delay9_t_1 + 32'sd1) begin
      Delay9_reg_re[Delay9_t_1] = 32'sb00000000000000000000000000000000;
      Delay9_reg_im[Delay9_t_1] = 32'sb00000000000000000000000000000000;
    end

  end

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 7
  assign count_step = 3'b001;

  assign count_from = 3'b000;

  assign count_reset = 3'b000;

  assign count = HDL_Counter_out1 + count_step;

  assign need_to_wrap = HDL_Counter_out1 == 3'b111;

  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);

  assign count_1 = (Subsystem1_validOut == 1'b0 ? HDL_Counter_out1 :
              count_value);

  assign count_2 = (Subsystem_Out2 == 1'b0 ? count_1 :
              count_reset);

  always @(posedge clk or posedge reset)
    begin : HDL_Counter_process
      if (reset == 1'b1) begin
        HDL_Counter_out1 <= 3'b000;
      end
      else begin
        if (enb_1_2_0) begin
          HDL_Counter_out1 <= count_2;
        end
      end
    end

  assign Compare_To_Constant_out1 = HDL_Counter_out1 == 3'b111;

  Receiver_ip_src_Subsystem u_Subsystem (.clk(clk),
                                         .reset(reset),
                                         .enb_1_2_0(enb_1_2_0),
                                         .L(syncPulse),
                                         .H(Logical_Operator_out1),
                                         .Out2(Subsystem_Out2)
                                         );

  Receiver_ip_src_Subsystem1 u_Subsystem1 (.In1(Subsystem_Out2),
                                           .validIn(validIn),
                                           .validOut(Subsystem1_validOut)
                                           );

  assign Logical_Operator_out1 = Subsystem1_validOut & Compare_To_Constant_out1;

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay3_out1 <= Logical_Operator_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay7_reg[0] <= Delay3_out1;
          Delay7_reg[1] <= Delay7_reg[0];
        end
      end
    end

  assign Delay7_out1 = Delay7_reg[1];

  always @(posedge clk or posedge reset)
    begin : Delay11_process
      if (reset == 1'b1) begin
        Delay11_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay11_reg[0] <= Delay7_out1;
          Delay11_reg[1] <= Delay11_reg[0];
        end
      end
    end

  assign Delay11_out1 = Delay11_reg[1];

  assign endOut = Delay11_out1;

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1_re <= 16'sb0000000000000000;
        Delay1_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay1_out1_re <= dataIn_re;
          Delay1_out1_im <= dataIn_im;
        end
      end
    end

  always @(posedge clk)
    begin : Delay5_process
      if (enb_1_2_0) begin
        for(Delay5_t_0_0 = 32'sd0; Delay5_t_0_0 <= 32'sd1; Delay5_t_0_0 = Delay5_t_0_0 + 32'sd1) begin
          Delay5_reg_re[Delay5_t_0_0] <= Delay5_reg_next_re[Delay5_t_0_0];
          Delay5_reg_im[Delay5_t_0_0] <= Delay5_reg_next_im[Delay5_t_0_0];
        end
      end
    end

  assign Delay5_out1_re = Delay5_reg_re[1];
  assign Delay5_out1_im = Delay5_reg_im[1];
  assign Delay5_reg_next_re[0] = Delay1_out1_re;
  assign Delay5_reg_next_im[0] = Delay1_out1_im;
  assign Delay5_reg_next_re[1] = Delay5_reg_re[0];
  assign Delay5_reg_next_im[1] = Delay5_reg_im[0];

  always @(posedge clk or posedge reset)
    begin : Delay8_process
      if (reset == 1'b1) begin
        Delay8_out1 <= 3'b000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay8_out1 <= HDL_Counter_out1;
        end
      end
    end

  assign Direct_Lookup_Table_n_D_table_data_re[0] = 16'sb1010010101111110;
  assign Direct_Lookup_Table_n_D_table_data_re[1] = 16'sb1010010101111110;
  assign Direct_Lookup_Table_n_D_table_data_re[2] = 16'sb0101101010000010;
  assign Direct_Lookup_Table_n_D_table_data_re[3] = 16'sb0101101010000010;
  assign Direct_Lookup_Table_n_D_table_data_re[4] = 16'sb1010010101111110;
  assign Direct_Lookup_Table_n_D_table_data_re[5] = 16'sb1010010101111110;
  assign Direct_Lookup_Table_n_D_table_data_re[6] = 16'sb0101101010000010;
  assign Direct_Lookup_Table_n_D_table_data_re[7] = 16'sb1010010101111110;
  assign Direct_Lookup_Table_n_D_table_data_im[0] = 16'sb1010010101111110;
  assign Direct_Lookup_Table_n_D_table_data_im[1] = 16'sb1010010101111110;
  assign Direct_Lookup_Table_n_D_table_data_im[2] = 16'sb0101101010000010;
  assign Direct_Lookup_Table_n_D_table_data_im[3] = 16'sb0101101010000010;
  assign Direct_Lookup_Table_n_D_table_data_im[4] = 16'sb1010010101111110;
  assign Direct_Lookup_Table_n_D_table_data_im[5] = 16'sb1010010101111110;
  assign Direct_Lookup_Table_n_D_table_data_im[6] = 16'sb0101101010000010;
  assign Direct_Lookup_Table_n_D_table_data_im[7] = 16'sb1010010101111110;
  assign Direct_Lookup_Table_n_D_out1_re = Direct_Lookup_Table_n_D_table_data_re[Delay8_out1];
  assign Direct_Lookup_Table_n_D_out1_im = Direct_Lookup_Table_n_D_table_data_im[Delay8_out1];

  assign Math_Function_out1_re = Direct_Lookup_Table_n_D_out1_re;
  assign conj_cast = {Direct_Lookup_Table_n_D_out1_im[15], Direct_Lookup_Table_n_D_out1_im};
  assign conj_cast_1 =  - (conj_cast);
  assign Math_Function_out1_im = ((conj_cast_1[16] == 1'b0) && (conj_cast_1[15] != 1'b0) ? 16'sb0111111111111111 :
              ((conj_cast_1[16] == 1'b1) && (conj_cast_1[15] != 1'b1) ? 16'sb1000000000000000 :
              $signed(conj_cast_1[15:0])));

  always @(posedge clk)
    begin : Delay4_process
      if (enb_1_2_0) begin
        for(Delay4_t_0_0 = 32'sd0; Delay4_t_0_0 <= 32'sd1; Delay4_t_0_0 = Delay4_t_0_0 + 32'sd1) begin
          Delay4_reg_re[Delay4_t_0_0] <= Delay4_reg_next_re[Delay4_t_0_0];
          Delay4_reg_im[Delay4_t_0_0] <= Delay4_reg_next_im[Delay4_t_0_0];
        end
      end
    end

  assign Delay4_out1_re = Delay4_reg_re[1];
  assign Delay4_out1_im = Delay4_reg_im[1];
  assign Delay4_reg_next_re[0] = Math_Function_out1_re;
  assign Delay4_reg_next_im[0] = Math_Function_out1_im;
  assign Delay4_reg_next_re[1] = Delay4_reg_re[0];
  assign Delay4_reg_next_im[1] = Delay4_reg_im[0];

  assign Product_mul_temp = Delay5_out1_re * Delay4_out1_re;
  assign Product_mul_temp_1 = Delay5_out1_im * Delay4_out1_im;
  assign Product_out1_re = Product_mul_temp - Product_mul_temp_1;
  assign Product_mul_temp_2 = Delay5_out1_im * Delay4_out1_re;
  assign Product_mul_temp_3 = Delay5_out1_re * Delay4_out1_im;
  assign Product_out1_im = Product_mul_temp_2 + Product_mul_temp_3;

  always @(posedge clk)
    begin : Delay9_process
      if (enb_1_2_0) begin
        for(Delay9_t_0_0 = 32'sd0; Delay9_t_0_0 <= 32'sd1; Delay9_t_0_0 = Delay9_t_0_0 + 32'sd1) begin
          Delay9_reg_re[Delay9_t_0_0] <= Delay9_reg_next_re[Delay9_t_0_0];
          Delay9_reg_im[Delay9_t_0_0] <= Delay9_reg_next_im[Delay9_t_0_0];
        end
      end
    end

  assign Delay9_out1_re = Delay9_reg_re[1];
  assign Delay9_out1_im = Delay9_reg_im[1];
  assign Delay9_reg_next_re[0] = Product_out1_re;
  assign Delay9_reg_next_im[0] = Product_out1_im;
  assign Delay9_reg_next_re[1] = Delay9_reg_re[0];
  assign Delay9_reg_next_im[1] = Delay9_reg_im[0];

  assign estOut_re = Delay9_out1_re;

  assign estOut_im = Delay9_out1_im;

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay2_out1 <= Subsystem1_validOut;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay6_reg[0] <= Delay2_out1;
          Delay6_reg[1] <= Delay6_reg[0];
        end
      end
    end

  assign Delay6_out1 = Delay6_reg[1];

  always @(posedge clk or posedge reset)
    begin : Delay10_process
      if (reset == 1'b1) begin
        Delay10_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay10_reg[0] <= Delay6_out1;
          Delay10_reg[1] <= Delay10_reg[0];
        end
      end
    end

  assign Delay10_out1 = Delay10_reg[1];

  assign validOut = Delay10_out1;

endmodule  // Receiver_ip_src_Phase_Ambiguity_Estimator

