// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_FilterCoef_block2.v
// Created: 2026-05-26 18:50:49
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_FilterCoef_block2
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/RRC Receive Filter/Filter/FilterCoef
// Hierarchy Level: 4
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_FilterCoef_block2
          (CoefOut_0,
           CoefOut_1,
           CoefOut_2,
           CoefOut_3,
           CoefOut_4,
           CoefOut_5,
           CoefOut_6,
           CoefOut_7,
           CoefOut_8,
           CoefOut_9,
           CoefOut_10,
           CoefOut_11,
           CoefOut_12,
           CoefOut_13,
           CoefOut_14,
           CoefOut_15,
           CoefOut_16);


  output  signed [15:0] CoefOut_0;  // sfix16_En15
  output  signed [15:0] CoefOut_1;  // sfix16_En15
  output  signed [15:0] CoefOut_2;  // sfix16_En15
  output  signed [15:0] CoefOut_3;  // sfix16_En15
  output  signed [15:0] CoefOut_4;  // sfix16_En15
  output  signed [15:0] CoefOut_5;  // sfix16_En15
  output  signed [15:0] CoefOut_6;  // sfix16_En15
  output  signed [15:0] CoefOut_7;  // sfix16_En15
  output  signed [15:0] CoefOut_8;  // sfix16_En15
  output  signed [15:0] CoefOut_9;  // sfix16_En15
  output  signed [15:0] CoefOut_10;  // sfix16_En15
  output  signed [15:0] CoefOut_11;  // sfix16_En15
  output  signed [15:0] CoefOut_12;  // sfix16_En15
  output  signed [15:0] CoefOut_13;  // sfix16_En15
  output  signed [15:0] CoefOut_14;  // sfix16_En15
  output  signed [15:0] CoefOut_15;  // sfix16_En15
  output  signed [15:0] CoefOut_16;  // sfix16_En15


  wire signed [15:0] CoefData;  // sfix16_En15
  wire signed [15:0] CoefData_1;  // sfix16_En15
  wire signed [15:0] CoefData_2;  // sfix16_En15
  wire signed [15:0] CoefData_3;  // sfix16_En15
  wire signed [15:0] CoefData_4;  // sfix16_En15
  wire signed [15:0] CoefData_5;  // sfix16_En15
  wire signed [15:0] CoefData_6;  // sfix16_En15
  wire signed [15:0] CoefData_7;  // sfix16_En15
  wire signed [15:0] CoefData_8;  // sfix16_En15
  wire signed [15:0] CoefData_9;  // sfix16_En15
  wire signed [15:0] CoefData_10;  // sfix16_En15
  wire signed [15:0] CoefData_11;  // sfix16_En15
  wire signed [15:0] CoefData_12;  // sfix16_En15
  wire signed [15:0] CoefData_13;  // sfix16_En15
  wire signed [15:0] CoefData_14;  // sfix16_En15
  wire signed [15:0] CoefData_15;  // sfix16_En15
  wire signed [15:0] CoefData_16;  // sfix16_En15


  // CoefReg_1
  assign CoefData = 16'sb0000001010111000;

  assign CoefOut_0 = CoefData;

  // CoefReg_2
  assign CoefData_1 = 16'sb0000000011111110;

  assign CoefOut_1 = CoefData_1;

  // CoefReg_3
  assign CoefData_2 = 16'sb1111101100110010;

  assign CoefOut_2 = CoefData_2;

  // CoefReg_4
  assign CoefData_3 = 16'sb1111010111110101;

  assign CoefOut_3 = CoefData_3;

  // CoefReg_5
  assign CoefData_4 = 16'sb1111100100110101;

  assign CoefOut_4 = CoefData_4;

  // CoefReg_6
  assign CoefData_5 = 16'sb0000101000001011;

  assign CoefOut_5 = CoefData_5;

  // CoefReg_7
  assign CoefData_6 = 16'sb0010010100001100;

  assign CoefOut_6 = CoefData_6;

  // CoefReg_8
  assign CoefData_7 = 16'sb0011111001100100;

  assign CoefOut_7 = CoefData_7;

  // CoefReg_9
  assign CoefData_8 = 16'sb0100100011000101;

  assign CoefOut_8 = CoefData_8;

  // CoefReg_10
  assign CoefData_9 = 16'sb0011111001100100;

  assign CoefOut_9 = CoefData_9;

  // CoefReg_11
  assign CoefData_10 = 16'sb0010010100001100;

  assign CoefOut_10 = CoefData_10;

  // CoefReg_12
  assign CoefData_11 = 16'sb0000101000001011;

  assign CoefOut_11 = CoefData_11;

  // CoefReg_13
  assign CoefData_12 = 16'sb1111100100110101;

  assign CoefOut_12 = CoefData_12;

  // CoefReg_14
  assign CoefData_13 = 16'sb1111010111110101;

  assign CoefOut_13 = CoefData_13;

  // CoefReg_15
  assign CoefData_14 = 16'sb1111101100110010;

  assign CoefOut_14 = CoefData_14;

  // CoefReg_16
  assign CoefData_15 = 16'sb0000000011111110;

  assign CoefOut_15 = CoefData_15;

  // CoefReg_17
  assign CoefData_16 = 16'sb0000001010111000;

  assign CoefOut_16 = CoefData_16;

endmodule  // Receiver_ip_src_FilterCoef_block2

