% fix_msggen -- model-level Tx content fix: the Message Generator filled the
% payload after "ADI Hello World" with a cycling ASCII counter digit and
% alternating toggle bits; on silicon that varying filler produces periodic
% BIST error bursts (the historic 7.27% self-test artifact) while a
% zero-padded payload (the host golden's structure) measures 0.000000%.
% Replace the filler with zero padding. Flags, framing, and counters are
% unchanged so downstream pacing and count_out ports are untouched.
sys = 'commhdlQPSKTxRx';
load_system(sys);
rt = sfroot;
ch = rt.find('-isa','Stateflow.EMChart','Path', ...
    [sys '/Transmitter/Input Data/Message Generator/MATLAB Function']);
assert(~isempty(ch), 'Message Generator chart not found');
s = ch.Script;

oldEmit = sprintf([ ...
'    if indexCount < msgbitsLen %% Insert msg\n' ...
'        out = msgbits(indexCount + 1);\n' ...
'        msgCountBitIndex = uint8(0);\n' ...
'    elseif msgCountBitIndex < (8) %% Number insert\n' ...
'        out = bitget(msgCount+48, 8-msgCountBitIndex) > 0;\n' ...
'        msgCountBitIndex = msgCountBitIndex + 1;\n' ...
'    else %% Toggle bits after message\n' ...
'        out = toggle;\n' ...
'        msgCountBitIndex = uint8(0);\n' ...
'        if toggle\n' ...
'            toggle = false;\n' ...
'        else\n' ...
'            toggle = true;\n' ...
'        end\n' ...
'    end\n']);
newEmit = sprintf([ ...
'    if indexCount < msgbitsLen %% Insert msg\n' ...
'        out = msgbits(indexCount + 1);\n' ...
'        msgCountBitIndex = uint8(0);\n' ...
'    else %% Zero padding: varying filler (counter digit + toggle bits)\n' ...
'        %% caused periodic false-lock error bursts in the deployed BIST;\n' ...
'        %% zero-padded payload matches the verified host golden structure.\n' ...
'        out = false;\n' ...
'        msgCountBitIndex = uint8(0);\n' ...
'    end\n']);
assert(contains(s, oldEmit), 'emit block not found verbatim -- script drifted');
ch.Script = strrep(s, oldEmit, newEmit);
save_system(sys);
fprintf('FIX_MSGGEN: emit block replaced and model saved\n');
% readback verification
s2 = ch.Script;
assert(~contains(s2,'Toggle bits after message') && contains(s2,'Zero padding'), 'readback failed');
fprintf('FIX_MSGGEN_OK\n');
