// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Correlator.v
// Created: 2026-05-26 18:50:49
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Correlator
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/Correlator
// Hierarchy Level: 4
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Correlator
          (clk,
           reset,
           enb_1_2_0,
           dataIn_re,
           dataIn_im,
           validIn,
           dataOut,
           threshold,
           validOut);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [15:0] dataIn_re;  // sfix16_En14
  input   signed [15:0] dataIn_im;  // sfix16_En14
  input   validIn;
  output  signed [31:0] dataOut;  // sfix32_En26
  output  signed [31:0] threshold;  // sfix32_En28
  output  validOut;


  wire signed [15:0] Discrete_FIR_Filter_out1_re;  // sfix16_En13
  wire signed [15:0] Discrete_FIR_Filter_out1_im;  // sfix16_En13
  wire Discrete_FIR_Filter_out2;
  reg signed [15:0] Delay6_out1_re;  // sfix16_En13
  reg signed [15:0] Delay6_out1_im;  // sfix16_En13
  wire signed [31:0] Magnitude_Squared_Out1_re;  // sfix32_En26
  reg signed [31:0] Delay2_out1;  // sfix32_En26
  wire signed [31:0] Magnitude_Squared_and_Moving_Sum_E1;  // sfix32_En28
  reg signed [31:0] Delay4_out1;  // sfix32_En28
  wire signed [31:0] y;  // sfix32_En28
  reg signed [31:0] Delay8_reg [0:3];  // sfix32 [4]
  reg signed [31:0] Delay8_reg_next [0:3];  // sfix32_En28 [4]
  reg signed [31:0] Delay8_out1;  // sfix32_En28
  reg signed [31:0] Delay5_out1;  // sfix32_En28
  reg  Delay1_out1;
  reg  [3:0] Delay7_reg;  // ufix1 [4]
  wire Delay7_out1;
  reg  Delay3_out1;
  reg signed [31:0] Delay8_t_0_0;  // int32
  reg signed [31:0] Delay8_t_0_1;  // int32
  reg signed [31:0] Delay8_t_1;  // int32


  Receiver_ip_src_Discrete_FIR_Filter u_Discrete_FIR_Filter (.clk(clk),
                                                             .reset(reset),
                                                             .enb_1_2_0(enb_1_2_0),
                                                             .dataIn_re(dataIn_re),  // sfix16_En14
                                                             .dataIn_im(dataIn_im),  // sfix16_En14
                                                             .validIn(validIn),
                                                             .dataOut_re(Discrete_FIR_Filter_out1_re),  // sfix16_En13
                                                             .dataOut_im(Discrete_FIR_Filter_out1_im),  // sfix16_En13
                                                             .validOut(Discrete_FIR_Filter_out2)
                                                             );

  always @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_out1_re <= 16'sb0000000000000000;
        Delay6_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay6_out1_re <= Discrete_FIR_Filter_out1_re;
          Delay6_out1_im <= Discrete_FIR_Filter_out1_im;
        end
      end
    end

  Receiver_ip_src_Magnitude_Squared u_Magnitude_Squared (.clk(clk),
                                                         .enb_1_2_0(enb_1_2_0),
                                                         .In1_re(Delay6_out1_re),  // sfix16_En13
                                                         .In1_im(Delay6_out1_im),  // sfix16_En13
                                                         .Out1_re(Magnitude_Squared_Out1_re)  // sfix32_En26
                                                         );

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay2_out1 <= Magnitude_Squared_Out1_re;
        end
      end
    end

  assign dataOut = Delay2_out1;

  Receiver_ip_src_Magnitude_Squared_and_Moving_Sum u_Magnitude_Squared_and_Moving_Sum (.clk(clk),
                                                                                       .reset(reset),
                                                                                       .enb_1_2_0(enb_1_2_0),
                                                                                       .scaled1_re(dataIn_re),  // sfix16_En14
                                                                                       .scaled1_im(dataIn_im),  // sfix16_En14
                                                                                       .validIn(validIn),
                                                                                       .E1(Magnitude_Squared_and_Moving_Sum_E1)  // sfix32_En28
                                                                                       );

  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay4_out1 <= Magnitude_Squared_and_Moving_Sum_E1;
        end
      end
    end

  Receiver_ip_src_ThresholdLimiter u_ThresholdLimiter (.x(Delay4_out1),  // sfix32_En28
                                                       .y(y)  // sfix32_En28
                                                       );

  always @(posedge clk or posedge reset)
    begin : Delay8_process
      if (reset == 1'b1) begin
        for(Delay8_t_1 = 32'sd0; Delay8_t_1 <= 32'sd3; Delay8_t_1 = Delay8_t_1 + 32'sd1) begin
          Delay8_reg[Delay8_t_1] <= 32'sb00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay8_t_0_1 = 32'sd0; Delay8_t_0_1 <= 32'sd3; Delay8_t_0_1 = Delay8_t_0_1 + 32'sd1) begin
            Delay8_reg[Delay8_t_0_1] <= Delay8_reg_next[Delay8_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay8_out1 = Delay8_reg[3];
    Delay8_reg_next[0] = y;

    for(Delay8_t_0_0 = 32'sd0; Delay8_t_0_0 <= 32'sd2; Delay8_t_0_0 = Delay8_t_0_0 + 32'sd1) begin
      Delay8_reg_next[Delay8_t_0_0 + 32'sd1] = Delay8_reg[Delay8_t_0_0];
    end

  end

  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay5_out1 <= Delay8_out1;
        end
      end
    end

  assign threshold = Delay5_out1;

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay1_out1 <= Discrete_FIR_Filter_out2;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_reg <= {4{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay7_reg[0] <= Delay1_out1;
          Delay7_reg[32'sd3:32'sd1] <= Delay7_reg[32'sd2:32'sd0];
        end
      end
    end

  assign Delay7_out1 = Delay7_reg[3];

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay3_out1 <= Delay7_out1;
        end
      end
    end

  assign validOut = Delay3_out1;

endmodule  // Receiver_ip_src_Correlator

