// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_HDL_CMA_core.v
// Created: 2026-05-26 18:50:47
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_HDL_CMA_core
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Coarse Frequency Compensator/Coarse 
// Frequency Estimator/Extract Frequency/HDL_CMA_cor
// Hierarchy Level: 6
// Model version: 11.305
// 
// Complex to Magnitude-Angle
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_HDL_CMA_core
          (clk,
           reset,
           enb_1_2_0,
           In_re,
           In_im,
           validIn,
           angle,
           validOut);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [31:0] In_re;  // sfix32_En24
  input   signed [31:0] In_im;  // sfix32_En24
  input   validIn;
  output  signed [34:0] angle;  // sfix35_En34
  output  validOut;


  reg  [33:0] Delay_ValidIn_reg;  // ufix1 [34]
  wire ValidOutDelayed;
  wire signed [32:0] xin31deadIn;  // sfix33_En24
  wire signed [32:0] qMapReal;  // sfix33_En24
  reg signed [32:0] In1Register;  // sfix33_En24
  wire signed [32:0] qMapImag;  // sfix33_En24
  reg signed [32:0] In2Register;  // sfix33_En24
  wire signed [32:0] XQMapped;  // sfix33_En24
  wire signed [32:0] yQMapped;  // sfix33_En24
  wire [4:0] ControlQC;  // ufix5
  reg signed [32:0] xin1;  // sfix33_En24
  reg signed [32:0] yin1;  // sfix33_En24
  wire signed [34:0] zin1;  // sfix35_En34
  wire [31:0] lut_value1;  // ufix32_En34
  wire [5:0] shift1;  // ufix6
  wire signed [32:0] xout1;  // sfix33_En24
  wire signed [32:0] yout1;  // sfix33_En24
  wire signed [34:0] zout1;  // sfix35_En34
  reg signed [32:0] xin2;  // sfix33_En24
  reg signed [32:0] yin2;  // sfix33_En24
  reg signed [34:0] zin2;  // sfix35_En34
  wire [31:0] lut_value2;  // ufix32_En34
  wire [5:0] shift2;  // ufix6
  wire signed [32:0] xout2;  // sfix33_En24
  wire signed [32:0] yout2;  // sfix33_En24
  wire signed [34:0] zout2;  // sfix35_En34
  reg signed [32:0] xin3;  // sfix33_En24
  reg signed [32:0] yin3;  // sfix33_En24
  reg signed [34:0] zin3;  // sfix35_En34
  wire [31:0] lut_value3;  // ufix32_En34
  wire [5:0] shift3;  // ufix6
  wire signed [32:0] xout3;  // sfix33_En24
  wire signed [32:0] yout3;  // sfix33_En24
  wire signed [34:0] zout3;  // sfix35_En34
  reg signed [32:0] xin4;  // sfix33_En24
  reg signed [32:0] yin4;  // sfix33_En24
  reg signed [34:0] zin4;  // sfix35_En34
  wire [31:0] lut_value4;  // ufix32_En34
  wire [5:0] shift4;  // ufix6
  wire signed [32:0] xout4;  // sfix33_En24
  wire signed [32:0] yout4;  // sfix33_En24
  wire signed [34:0] zout4;  // sfix35_En34
  reg signed [32:0] xin5;  // sfix33_En24
  reg signed [32:0] yin5;  // sfix33_En24
  reg signed [34:0] zin5;  // sfix35_En34
  wire [31:0] lut_value5;  // ufix32_En34
  wire [5:0] shift5;  // ufix6
  wire signed [32:0] xout5;  // sfix33_En24
  wire signed [32:0] yout5;  // sfix33_En24
  wire signed [34:0] zout5;  // sfix35_En34
  reg signed [32:0] xin6;  // sfix33_En24
  reg signed [32:0] yin6;  // sfix33_En24
  reg signed [34:0] zin6;  // sfix35_En34
  wire [31:0] lut_value6;  // ufix32_En34
  wire [5:0] shift6;  // ufix6
  wire signed [32:0] xout6;  // sfix33_En24
  wire signed [32:0] yout6;  // sfix33_En24
  wire signed [34:0] zout6;  // sfix35_En34
  reg signed [32:0] xin7;  // sfix33_En24
  reg signed [32:0] yin7;  // sfix33_En24
  reg signed [34:0] zin7;  // sfix35_En34
  wire [31:0] lut_value7;  // ufix32_En34
  wire [5:0] shift7;  // ufix6
  wire signed [32:0] xout7;  // sfix33_En24
  wire signed [32:0] yout7;  // sfix33_En24
  wire signed [34:0] zout7;  // sfix35_En34
  reg signed [32:0] xin8;  // sfix33_En24
  reg signed [32:0] yin8;  // sfix33_En24
  reg signed [34:0] zin8;  // sfix35_En34
  wire [31:0] lut_value8;  // ufix32_En34
  wire [5:0] shift8;  // ufix6
  wire signed [32:0] xout8;  // sfix33_En24
  wire signed [32:0] yout8;  // sfix33_En24
  wire signed [34:0] zout8;  // sfix35_En34
  reg signed [32:0] xin9;  // sfix33_En24
  reg signed [32:0] yin9;  // sfix33_En24
  reg signed [34:0] zin9;  // sfix35_En34
  wire [31:0] lut_value9;  // ufix32_En34
  wire [5:0] shift9;  // ufix6
  wire signed [32:0] xout9;  // sfix33_En24
  wire signed [32:0] yout9;  // sfix33_En24
  wire signed [34:0] zout9;  // sfix35_En34
  reg signed [32:0] xin10;  // sfix33_En24
  reg signed [32:0] yin10;  // sfix33_En24
  reg signed [34:0] zin10;  // sfix35_En34
  wire [31:0] lut_value10;  // ufix32_En34
  wire [5:0] shift10;  // ufix6
  wire signed [32:0] xout10;  // sfix33_En24
  wire signed [32:0] yout10;  // sfix33_En24
  wire signed [34:0] zout10;  // sfix35_En34
  reg signed [32:0] xin11;  // sfix33_En24
  reg signed [32:0] yin11;  // sfix33_En24
  reg signed [34:0] zin11;  // sfix35_En34
  wire [31:0] lut_value11;  // ufix32_En34
  wire [5:0] shift11;  // ufix6
  wire signed [32:0] xout11;  // sfix33_En24
  wire signed [32:0] yout11;  // sfix33_En24
  wire signed [34:0] zout11;  // sfix35_En34
  reg signed [32:0] xin12;  // sfix33_En24
  reg signed [32:0] yin12;  // sfix33_En24
  reg signed [34:0] zin12;  // sfix35_En34
  wire [31:0] lut_value12;  // ufix32_En34
  wire [5:0] shift12;  // ufix6
  wire signed [32:0] xout12;  // sfix33_En24
  wire signed [32:0] yout12;  // sfix33_En24
  wire signed [34:0] zout12;  // sfix35_En34
  reg signed [32:0] xin13;  // sfix33_En24
  reg signed [32:0] yin13;  // sfix33_En24
  reg signed [34:0] zin13;  // sfix35_En34
  wire [31:0] lut_value13;  // ufix32_En34
  wire [5:0] shift13;  // ufix6
  wire signed [32:0] xout13;  // sfix33_En24
  wire signed [32:0] yout13;  // sfix33_En24
  wire signed [34:0] zout13;  // sfix35_En34
  reg signed [32:0] xin14;  // sfix33_En24
  reg signed [32:0] yin14;  // sfix33_En24
  reg signed [34:0] zin14;  // sfix35_En34
  wire [31:0] lut_value14;  // ufix32_En34
  wire [5:0] shift14;  // ufix6
  wire signed [32:0] xout14;  // sfix33_En24
  wire signed [32:0] yout14;  // sfix33_En24
  wire signed [34:0] zout14;  // sfix35_En34
  reg signed [32:0] xin15;  // sfix33_En24
  reg signed [32:0] yin15;  // sfix33_En24
  reg signed [34:0] zin15;  // sfix35_En34
  wire [31:0] lut_value15;  // ufix32_En34
  wire [5:0] shift15;  // ufix6
  wire signed [32:0] xout15;  // sfix33_En24
  wire signed [32:0] yout15;  // sfix33_En24
  wire signed [34:0] zout15;  // sfix35_En34
  reg signed [32:0] xin16;  // sfix33_En24
  reg signed [32:0] yin16;  // sfix33_En24
  reg signed [34:0] zin16;  // sfix35_En34
  wire [31:0] lut_value16;  // ufix32_En34
  wire [5:0] shift16;  // ufix6
  wire signed [32:0] xout16;  // sfix33_En24
  wire signed [32:0] yout16;  // sfix33_En24
  wire signed [34:0] zout16;  // sfix35_En34
  reg signed [32:0] xin17;  // sfix33_En24
  reg signed [32:0] yin17;  // sfix33_En24
  reg signed [34:0] zin17;  // sfix35_En34
  wire [31:0] lut_value17;  // ufix32_En34
  wire [5:0] shift17;  // ufix6
  wire signed [32:0] xout17;  // sfix33_En24
  wire signed [32:0] yout17;  // sfix33_En24
  wire signed [34:0] zout17;  // sfix35_En34
  reg signed [32:0] xin18;  // sfix33_En24
  reg signed [32:0] yin18;  // sfix33_En24
  reg signed [34:0] zin18;  // sfix35_En34
  wire [31:0] lut_value18;  // ufix32_En34
  wire [5:0] shift18;  // ufix6
  wire signed [32:0] xout18;  // sfix33_En24
  wire signed [32:0] yout18;  // sfix33_En24
  wire signed [34:0] zout18;  // sfix35_En34
  reg signed [32:0] xin19;  // sfix33_En24
  reg signed [32:0] yin19;  // sfix33_En24
  reg signed [34:0] zin19;  // sfix35_En34
  wire [31:0] lut_value19;  // ufix32_En34
  wire [5:0] shift19;  // ufix6
  wire signed [32:0] xout19;  // sfix33_En24
  wire signed [32:0] yout19;  // sfix33_En24
  wire signed [34:0] zout19;  // sfix35_En34
  reg signed [32:0] xin20;  // sfix33_En24
  reg signed [32:0] yin20;  // sfix33_En24
  reg signed [34:0] zin20;  // sfix35_En34
  wire [31:0] lut_value20;  // ufix32_En34
  wire [5:0] shift20;  // ufix6
  wire signed [32:0] xout20;  // sfix33_En24
  wire signed [32:0] yout20;  // sfix33_En24
  wire signed [34:0] zout20;  // sfix35_En34
  reg signed [32:0] xin21;  // sfix33_En24
  reg signed [32:0] yin21;  // sfix33_En24
  reg signed [34:0] zin21;  // sfix35_En34
  wire [31:0] lut_value21;  // ufix32_En34
  wire [5:0] shift21;  // ufix6
  wire signed [32:0] xout21;  // sfix33_En24
  wire signed [32:0] yout21;  // sfix33_En24
  wire signed [34:0] zout21;  // sfix35_En34
  reg signed [32:0] xin22;  // sfix33_En24
  reg signed [32:0] yin22;  // sfix33_En24
  reg signed [34:0] zin22;  // sfix35_En34
  wire [31:0] lut_value22;  // ufix32_En34
  wire [5:0] shift22;  // ufix6
  wire signed [32:0] xout22;  // sfix33_En24
  wire signed [32:0] yout22;  // sfix33_En24
  wire signed [34:0] zout22;  // sfix35_En34
  reg signed [32:0] xin23;  // sfix33_En24
  reg signed [32:0] yin23;  // sfix33_En24
  reg signed [34:0] zin23;  // sfix35_En34
  wire [31:0] lut_value23;  // ufix32_En34
  wire [5:0] shift23;  // ufix6
  wire signed [32:0] xout23;  // sfix33_En24
  wire signed [32:0] yout23;  // sfix33_En24
  wire signed [34:0] zout23;  // sfix35_En34
  reg signed [32:0] xin24;  // sfix33_En24
  reg signed [32:0] yin24;  // sfix33_En24
  reg signed [34:0] zin24;  // sfix35_En34
  wire [31:0] lut_value24;  // ufix32_En34
  wire [5:0] shift24;  // ufix6
  wire signed [32:0] xout24;  // sfix33_En24
  wire signed [32:0] yout24;  // sfix33_En24
  wire signed [34:0] zout24;  // sfix35_En34
  reg signed [32:0] xin25;  // sfix33_En24
  reg signed [32:0] yin25;  // sfix33_En24
  reg signed [34:0] zin25;  // sfix35_En34
  wire [31:0] lut_value25;  // ufix32_En34
  wire [5:0] shift25;  // ufix6
  wire signed [32:0] xout25;  // sfix33_En24
  wire signed [32:0] yout25;  // sfix33_En24
  wire signed [34:0] zout25;  // sfix35_En34
  reg signed [32:0] xin26;  // sfix33_En24
  reg signed [32:0] yin26;  // sfix33_En24
  reg signed [34:0] zin26;  // sfix35_En34
  wire [31:0] lut_value26;  // ufix32_En34
  wire [5:0] shift26;  // ufix6
  wire signed [32:0] xout26;  // sfix33_En24
  wire signed [32:0] yout26;  // sfix33_En24
  wire signed [34:0] zout26;  // sfix35_En34
  reg signed [32:0] xin27;  // sfix33_En24
  reg signed [32:0] yin27;  // sfix33_En24
  reg signed [34:0] zin27;  // sfix35_En34
  wire [31:0] lut_value27;  // ufix32_En34
  wire [5:0] shift27;  // ufix6
  wire signed [32:0] xout27;  // sfix33_En24
  wire signed [32:0] yout27;  // sfix33_En24
  wire signed [34:0] zout27;  // sfix35_En34
  reg signed [32:0] xin28;  // sfix33_En24
  reg signed [32:0] yin28;  // sfix33_En24
  reg signed [34:0] zin28;  // sfix35_En34
  wire [31:0] lut_value28;  // ufix32_En34
  wire [5:0] shift28;  // ufix6
  wire signed [32:0] xout28;  // sfix33_En24
  wire signed [32:0] yout28;  // sfix33_En24
  wire signed [34:0] zout28;  // sfix35_En34
  reg signed [32:0] xin29;  // sfix33_En24
  reg signed [32:0] yin29;  // sfix33_En24
  reg signed [34:0] zin29;  // sfix35_En34
  wire [31:0] lut_value29;  // ufix32_En34
  wire [5:0] shift29;  // ufix6
  wire signed [32:0] xout29;  // sfix33_En24
  wire signed [32:0] yout29;  // sfix33_En24
  wire signed [34:0] zout29;  // sfix35_En34
  reg signed [32:0] xin30;  // sfix33_En24
  reg signed [32:0] yin30;  // sfix33_En24
  reg signed [34:0] zin30;  // sfix35_En34
  wire [31:0] lut_value30;  // ufix32_En34
  wire [5:0] shift30;  // ufix6
  wire signed [32:0] xout30deadOut;  // sfix33_En24
  wire signed [32:0] yout30;  // sfix33_En24
  wire signed [34:0] zout30;  // sfix35_En34
  reg signed [32:0] yin31;  // sfix33_En24
  reg signed [34:0] zin31;  // sfix35_En34
  wire [31:0] lut_value31;  // ufix32_En34
  wire [5:0] shift31deadIn;  // ufix6
  wire signed [32:0] xout31deadOut;  // sfix33_En24
  wire signed [32:0] yout31deadOut;  // sfix33_En24
  wire signed [34:0] zout31;  // sfix35_En34
  reg signed [34:0] zin32;  // sfix35_En34
  wire reset_outval;
  reg [4:0] DelayQC_Control_reg [0:31];  // ufix5 [32]
  reg [4:0] DelayQC_Control_reg_next [0:31];  // ufix5 [32]
  reg [4:0] ControlQCDelay;  // ufix5
  wire signed [34:0] zout_corrected;  // sfix35_En34
  wire signed [34:0] zeroCA;  // sfix35_En34
  wire signed [34:0] outSwitchAng;  // sfix35_En34
  reg signed [34:0] zout_corrected_1;  // sfix35_En34
  reg  validOut_1;
  reg signed [31:0] DelayQC_Control_t_0_0;  // int32
  reg signed [31:0] DelayQC_Control_t_0_1;  // int32
  reg signed [31:0] DelayQC_Control_t_1;  // int32


  always @(posedge clk or posedge reset)
    begin : Delay_ValidIn_process
      if (reset == 1'b1) begin
        Delay_ValidIn_reg <= {34{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay_ValidIn_reg[0] <= validIn;
          Delay_ValidIn_reg[32'sd33:32'sd1] <= Delay_ValidIn_reg[32'sd32:32'sd0];
        end
      end
    end

  assign ValidOutDelayed = Delay_ValidIn_reg[33];

  assign xin31deadIn = 33'sh000000000;

  assign qMapReal = {In_re[31], In_re};

  always @(posedge clk or posedge reset)
    begin : DelayRealInput_process
      if (reset == 1'b1) begin
        In1Register <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          In1Register <= qMapReal;
        end
      end
    end

  assign qMapImag = {In_im[31], In_im};

  always @(posedge clk or posedge reset)
    begin : DelayImagInput_process
      if (reset == 1'b1) begin
        In2Register <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          In2Register <= qMapImag;
        end
      end
    end

  Receiver_ip_src_Quadrant_Mapper u_QuadrantMapper (.clk(clk),
                                                    .reset(reset),
                                                    .enb_1_2_0(enb_1_2_0),
                                                    .xin(In1Register),  // sfix33_En24
                                                    .yin(In2Register),  // sfix33_En24
                                                    .xout(XQMapped),  // sfix33_En24
                                                    .yout(yQMapped),  // sfix33_En24
                                                    .QA_Control(ControlQC)  // ufix5
                                                    );

  always @(posedge clk or posedge reset)
    begin : DelayQuadMapper1_process
      if (reset == 1'b1) begin
        xin1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin1 <= XQMapped;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : DelayQuadMapper2_process
      if (reset == 1'b1) begin
        yin1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin1 <= yQMapped;
        end
      end
    end

  assign zin1 = 35'sh000000000;

  assign lut_value1 = 32'b10010111001000000010100011101101;

  assign shift1 = 6'b000001;

  Receiver_ip_src_CordicKernelMag u_Iteration (.xin(xin1),  // sfix33_En24
                                               .yin(yin1),  // sfix33_En24
                                               .zin(zin1),  // sfix35_En34
                                               .lut_value(lut_value1),  // ufix32_En34
                                               .idx(shift1),  // ufix6
                                               .xout(xout1),  // sfix33_En24
                                               .yout(yout1),  // sfix33_En24
                                               .zout(zout1)  // sfix35_En34
                                               );

  always @(posedge clk or posedge reset)
    begin : Pipeline1_process
      if (reset == 1'b1) begin
        xin2 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin2 <= xout1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline1_1_process
      if (reset == 1'b1) begin
        yin2 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin2 <= yout1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline1_2_process
      if (reset == 1'b1) begin
        zin2 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin2 <= zout1;
        end
      end
    end

  assign lut_value2 = 32'b01001111110110011100001011011011;

  assign shift2 = 6'b000010;

  Receiver_ip_src_CordicKernelMag u_Iteration_1 (.xin(xin2),  // sfix33_En24
                                                 .yin(yin2),  // sfix33_En24
                                                 .zin(zin2),  // sfix35_En34
                                                 .lut_value(lut_value2),  // ufix32_En34
                                                 .idx(shift2),  // ufix6
                                                 .xout(xout2),  // sfix33_En24
                                                 .yout(yout2),  // sfix33_En24
                                                 .zout(zout2)  // sfix35_En34
                                                 );

  always @(posedge clk or posedge reset)
    begin : Pipeline2_process
      if (reset == 1'b1) begin
        xin3 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin3 <= xout2;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline2_1_process
      if (reset == 1'b1) begin
        yin3 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin3 <= yout2;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline2_2_process
      if (reset == 1'b1) begin
        zin3 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin3 <= zout2;
        end
      end
    end

  assign lut_value3 = 32'b00101000100010001000111010100001;

  assign shift3 = 6'b000011;

  Receiver_ip_src_CordicKernelMag u_Iteration_2 (.xin(xin3),  // sfix33_En24
                                                 .yin(yin3),  // sfix33_En24
                                                 .zin(zin3),  // sfix35_En34
                                                 .lut_value(lut_value3),  // ufix32_En34
                                                 .idx(shift3),  // ufix6
                                                 .xout(xout3),  // sfix33_En24
                                                 .yout(yout3),  // sfix33_En24
                                                 .zout(zout3)  // sfix35_En34
                                                 );

  always @(posedge clk or posedge reset)
    begin : Pipeline3_process
      if (reset == 1'b1) begin
        xin4 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin4 <= xout3;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline3_1_process
      if (reset == 1'b1) begin
        yin4 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin4 <= yout3;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline3_2_process
      if (reset == 1'b1) begin
        zin4 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin4 <= zout3;
        end
      end
    end

  assign lut_value4 = 32'b00010100010110000110101000011000;

  assign shift4 = 6'b000100;

  Receiver_ip_src_CordicKernelMag u_Iteration_3 (.xin(xin4),  // sfix33_En24
                                                 .yin(yin4),  // sfix33_En24
                                                 .zin(zin4),  // sfix35_En34
                                                 .lut_value(lut_value4),  // ufix32_En34
                                                 .idx(shift4),  // ufix6
                                                 .xout(xout4),  // sfix33_En24
                                                 .yout(yout4),  // sfix33_En24
                                                 .zout(zout4)  // sfix35_En34
                                                 );

  always @(posedge clk or posedge reset)
    begin : Pipeline4_process
      if (reset == 1'b1) begin
        xin5 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin5 <= xout4;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline4_1_process
      if (reset == 1'b1) begin
        yin5 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin5 <= yout4;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline4_2_process
      if (reset == 1'b1) begin
        zin5 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin5 <= zout4;
        end
      end
    end

  assign lut_value5 = 32'b00001010001011101011111100001011;

  assign shift5 = 6'b000101;

  Receiver_ip_src_CordicKernelMag u_Iteration_4 (.xin(xin5),  // sfix33_En24
                                                 .yin(yin5),  // sfix33_En24
                                                 .zin(zin5),  // sfix35_En34
                                                 .lut_value(lut_value5),  // ufix32_En34
                                                 .idx(shift5),  // ufix6
                                                 .xout(xout5),  // sfix33_En24
                                                 .yout(yout5),  // sfix33_En24
                                                 .zout(zout5)  // sfix35_En34
                                                 );

  always @(posedge clk or posedge reset)
    begin : Pipeline5_process
      if (reset == 1'b1) begin
        xin6 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin6 <= xout5;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline5_1_process
      if (reset == 1'b1) begin
        yin6 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin6 <= yout5;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline5_2_process
      if (reset == 1'b1) begin
        zin6 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin6 <= zout5;
        end
      end
    end

  assign lut_value6 = 32'b00000101000101111011000011110011;

  assign shift6 = 6'b000110;

  Receiver_ip_src_CordicKernelMag u_Iteration_5 (.xin(xin6),  // sfix33_En24
                                                 .yin(yin6),  // sfix33_En24
                                                 .zin(zin6),  // sfix35_En34
                                                 .lut_value(lut_value6),  // ufix32_En34
                                                 .idx(shift6),  // ufix6
                                                 .xout(xout6),  // sfix33_En24
                                                 .yout(yout6),  // sfix33_En24
                                                 .zout(zout6)  // sfix35_En34
                                                 );

  always @(posedge clk or posedge reset)
    begin : Pipeline6_process
      if (reset == 1'b1) begin
        xin7 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin7 <= xout6;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline6_1_process
      if (reset == 1'b1) begin
        yin7 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin7 <= yout6;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline6_2_process
      if (reset == 1'b1) begin
        zin7 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin7 <= zout6;
        end
      end
    end

  assign lut_value7 = 32'b00000010100010111110001010101001;

  assign shift7 = 6'b000111;

  Receiver_ip_src_CordicKernelMag u_Iteration_6 (.xin(xin7),  // sfix33_En24
                                                 .yin(yin7),  // sfix33_En24
                                                 .zin(zin7),  // sfix35_En34
                                                 .lut_value(lut_value7),  // ufix32_En34
                                                 .idx(shift7),  // ufix6
                                                 .xout(xout7),  // sfix33_En24
                                                 .yout(yout7),  // sfix33_En24
                                                 .zout(zout7)  // sfix35_En34
                                                 );

  always @(posedge clk or posedge reset)
    begin : Pipeline7_process
      if (reset == 1'b1) begin
        xin8 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin8 <= xout7;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline7_1_process
      if (reset == 1'b1) begin
        yin8 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin8 <= yout7;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline7_2_process
      if (reset == 1'b1) begin
        zin8 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin8 <= zout7;
        end
      end
    end

  assign lut_value8 = 32'b00000001010001011111001010011010;

  assign shift8 = 6'b001000;

  Receiver_ip_src_CordicKernelMag u_Iteration_7 (.xin(xin8),  // sfix33_En24
                                                 .yin(yin8),  // sfix33_En24
                                                 .zin(zin8),  // sfix35_En34
                                                 .lut_value(lut_value8),  // ufix32_En34
                                                 .idx(shift8),  // ufix6
                                                 .xout(xout8),  // sfix33_En24
                                                 .yout(yout8),  // sfix33_En24
                                                 .zout(zout8)  // sfix35_En34
                                                 );

  always @(posedge clk or posedge reset)
    begin : Pipeline8_process
      if (reset == 1'b1) begin
        xin9 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin9 <= xout8;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline8_1_process
      if (reset == 1'b1) begin
        yin9 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin9 <= yout8;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline8_2_process
      if (reset == 1'b1) begin
        zin9 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin9 <= zout8;
        end
      end
    end

  assign lut_value9 = 32'b00000000101000101111100101110110;

  assign shift9 = 6'b001001;

  Receiver_ip_src_CordicKernelMag u_Iteration_8 (.xin(xin9),  // sfix33_En24
                                                 .yin(yin9),  // sfix33_En24
                                                 .zin(zin9),  // sfix35_En34
                                                 .lut_value(lut_value9),  // ufix32_En34
                                                 .idx(shift9),  // ufix6
                                                 .xout(xout9),  // sfix33_En24
                                                 .yout(yout9),  // sfix33_En24
                                                 .zout(zout9)  // sfix35_En34
                                                 );

  always @(posedge clk or posedge reset)
    begin : Pipeline9_process
      if (reset == 1'b1) begin
        xin10 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin10 <= xout9;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline9_1_process
      if (reset == 1'b1) begin
        yin10 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin10 <= yout9;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline9_2_process
      if (reset == 1'b1) begin
        zin10 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin10 <= zout9;
        end
      end
    end

  assign lut_value10 = 32'b00000000010100010111110011000000;

  assign shift10 = 6'b001010;

  Receiver_ip_src_CordicKernelMag u_Iteration_9 (.xin(xin10),  // sfix33_En24
                                                 .yin(yin10),  // sfix33_En24
                                                 .zin(zin10),  // sfix35_En34
                                                 .lut_value(lut_value10),  // ufix32_En34
                                                 .idx(shift10),  // ufix6
                                                 .xout(xout10),  // sfix33_En24
                                                 .yout(yout10),  // sfix33_En24
                                                 .zout(zout10)  // sfix35_En34
                                                 );

  always @(posedge clk or posedge reset)
    begin : Pipeline10_process
      if (reset == 1'b1) begin
        xin11 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin11 <= xout10;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline10_1_process
      if (reset == 1'b1) begin
        yin11 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin11 <= yout10;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline10_2_process
      if (reset == 1'b1) begin
        zin11 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin11 <= zout10;
        end
      end
    end

  assign lut_value11 = 32'b00000000001010001011111001100001;

  assign shift11 = 6'b001011;

  Receiver_ip_src_CordicKernelMag u_Iteration_10 (.xin(xin11),  // sfix33_En24
                                                  .yin(yin11),  // sfix33_En24
                                                  .zin(zin11),  // sfix35_En34
                                                  .lut_value(lut_value11),  // ufix32_En34
                                                  .idx(shift11),  // ufix6
                                                  .xout(xout11),  // sfix33_En24
                                                  .yout(yout11),  // sfix33_En24
                                                  .zout(zout11)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline11_process
      if (reset == 1'b1) begin
        xin12 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin12 <= xout11;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline11_1_process
      if (reset == 1'b1) begin
        yin12 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin12 <= yout11;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline11_2_process
      if (reset == 1'b1) begin
        zin12 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin12 <= zout11;
        end
      end
    end

  assign lut_value12 = 32'b00000000000101000101111100110000;

  assign shift12 = 6'b001100;

  Receiver_ip_src_CordicKernelMag u_Iteration_11 (.xin(xin12),  // sfix33_En24
                                                  .yin(yin12),  // sfix33_En24
                                                  .zin(zin12),  // sfix35_En34
                                                  .lut_value(lut_value12),  // ufix32_En34
                                                  .idx(shift12),  // ufix6
                                                  .xout(xout12),  // sfix33_En24
                                                  .yout(yout12),  // sfix33_En24
                                                  .zout(zout12)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline12_process
      if (reset == 1'b1) begin
        xin13 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin13 <= xout12;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline12_1_process
      if (reset == 1'b1) begin
        yin13 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin13 <= yout12;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline12_2_process
      if (reset == 1'b1) begin
        zin13 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin13 <= zout12;
        end
      end
    end

  assign lut_value13 = 32'b00000000000010100010111110011000;

  assign shift13 = 6'b001101;

  Receiver_ip_src_CordicKernelMag u_Iteration_12 (.xin(xin13),  // sfix33_En24
                                                  .yin(yin13),  // sfix33_En24
                                                  .zin(zin13),  // sfix35_En34
                                                  .lut_value(lut_value13),  // ufix32_En34
                                                  .idx(shift13),  // ufix6
                                                  .xout(xout13),  // sfix33_En24
                                                  .yout(yout13),  // sfix33_En24
                                                  .zout(zout13)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline13_process
      if (reset == 1'b1) begin
        xin14 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin14 <= xout13;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline13_1_process
      if (reset == 1'b1) begin
        yin14 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin14 <= yout13;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline13_2_process
      if (reset == 1'b1) begin
        zin14 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin14 <= zout13;
        end
      end
    end

  assign lut_value14 = 32'b00000000000001010001011111001100;

  assign shift14 = 6'b001110;

  Receiver_ip_src_CordicKernelMag u_Iteration_13 (.xin(xin14),  // sfix33_En24
                                                  .yin(yin14),  // sfix33_En24
                                                  .zin(zin14),  // sfix35_En34
                                                  .lut_value(lut_value14),  // ufix32_En34
                                                  .idx(shift14),  // ufix6
                                                  .xout(xout14),  // sfix33_En24
                                                  .yout(yout14),  // sfix33_En24
                                                  .zout(zout14)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline14_process
      if (reset == 1'b1) begin
        xin15 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin15 <= xout14;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline14_1_process
      if (reset == 1'b1) begin
        yin15 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin15 <= yout14;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline14_2_process
      if (reset == 1'b1) begin
        zin15 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin15 <= zout14;
        end
      end
    end

  assign lut_value15 = 32'b00000000000000101000101111100110;

  assign shift15 = 6'b001111;

  Receiver_ip_src_CordicKernelMag u_Iteration_14 (.xin(xin15),  // sfix33_En24
                                                  .yin(yin15),  // sfix33_En24
                                                  .zin(zin15),  // sfix35_En34
                                                  .lut_value(lut_value15),  // ufix32_En34
                                                  .idx(shift15),  // ufix6
                                                  .xout(xout15),  // sfix33_En24
                                                  .yout(yout15),  // sfix33_En24
                                                  .zout(zout15)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline15_process
      if (reset == 1'b1) begin
        xin16 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin16 <= xout15;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline15_1_process
      if (reset == 1'b1) begin
        yin16 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin16 <= yout15;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline15_2_process
      if (reset == 1'b1) begin
        zin16 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin16 <= zout15;
        end
      end
    end

  assign lut_value16 = 32'b00000000000000010100010111110011;

  assign shift16 = 6'b010000;

  Receiver_ip_src_CordicKernelMag u_Iteration_15 (.xin(xin16),  // sfix33_En24
                                                  .yin(yin16),  // sfix33_En24
                                                  .zin(zin16),  // sfix35_En34
                                                  .lut_value(lut_value16),  // ufix32_En34
                                                  .idx(shift16),  // ufix6
                                                  .xout(xout16),  // sfix33_En24
                                                  .yout(yout16),  // sfix33_En24
                                                  .zout(zout16)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline16_process
      if (reset == 1'b1) begin
        xin17 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin17 <= xout16;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline16_1_process
      if (reset == 1'b1) begin
        yin17 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin17 <= yout16;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline16_2_process
      if (reset == 1'b1) begin
        zin17 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin17 <= zout16;
        end
      end
    end

  assign lut_value17 = 32'b00000000000000001010001011111010;

  assign shift17 = 6'b010001;

  Receiver_ip_src_CordicKernelMag u_Iteration_16 (.xin(xin17),  // sfix33_En24
                                                  .yin(yin17),  // sfix33_En24
                                                  .zin(zin17),  // sfix35_En34
                                                  .lut_value(lut_value17),  // ufix32_En34
                                                  .idx(shift17),  // ufix6
                                                  .xout(xout17),  // sfix33_En24
                                                  .yout(yout17),  // sfix33_En24
                                                  .zout(zout17)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline17_process
      if (reset == 1'b1) begin
        xin18 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin18 <= xout17;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline17_1_process
      if (reset == 1'b1) begin
        yin18 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin18 <= yout17;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline17_2_process
      if (reset == 1'b1) begin
        zin18 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin18 <= zout17;
        end
      end
    end

  assign lut_value18 = 32'b00000000000000000101000101111101;

  assign shift18 = 6'b010010;

  Receiver_ip_src_CordicKernelMag u_Iteration_17 (.xin(xin18),  // sfix33_En24
                                                  .yin(yin18),  // sfix33_En24
                                                  .zin(zin18),  // sfix35_En34
                                                  .lut_value(lut_value18),  // ufix32_En34
                                                  .idx(shift18),  // ufix6
                                                  .xout(xout18),  // sfix33_En24
                                                  .yout(yout18),  // sfix33_En24
                                                  .zout(zout18)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline18_process
      if (reset == 1'b1) begin
        xin19 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin19 <= xout18;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline18_1_process
      if (reset == 1'b1) begin
        yin19 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin19 <= yout18;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline18_2_process
      if (reset == 1'b1) begin
        zin19 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin19 <= zout18;
        end
      end
    end

  assign lut_value19 = 32'b00000000000000000010100010111110;

  assign shift19 = 6'b010011;

  Receiver_ip_src_CordicKernelMag u_Iteration_18 (.xin(xin19),  // sfix33_En24
                                                  .yin(yin19),  // sfix33_En24
                                                  .zin(zin19),  // sfix35_En34
                                                  .lut_value(lut_value19),  // ufix32_En34
                                                  .idx(shift19),  // ufix6
                                                  .xout(xout19),  // sfix33_En24
                                                  .yout(yout19),  // sfix33_En24
                                                  .zout(zout19)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline19_process
      if (reset == 1'b1) begin
        xin20 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin20 <= xout19;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline19_1_process
      if (reset == 1'b1) begin
        yin20 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin20 <= yout19;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline19_2_process
      if (reset == 1'b1) begin
        zin20 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin20 <= zout19;
        end
      end
    end

  assign lut_value20 = 32'b00000000000000000001010001011111;

  assign shift20 = 6'b010100;

  Receiver_ip_src_CordicKernelMag u_Iteration_19 (.xin(xin20),  // sfix33_En24
                                                  .yin(yin20),  // sfix33_En24
                                                  .zin(zin20),  // sfix35_En34
                                                  .lut_value(lut_value20),  // ufix32_En34
                                                  .idx(shift20),  // ufix6
                                                  .xout(xout20),  // sfix33_En24
                                                  .yout(yout20),  // sfix33_En24
                                                  .zout(zout20)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline20_process
      if (reset == 1'b1) begin
        xin21 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin21 <= xout20;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline20_1_process
      if (reset == 1'b1) begin
        yin21 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin21 <= yout20;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline20_2_process
      if (reset == 1'b1) begin
        zin21 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin21 <= zout20;
        end
      end
    end

  assign lut_value21 = 32'b00000000000000000000101000110000;

  assign shift21 = 6'b010101;

  Receiver_ip_src_CordicKernelMag u_Iteration_20 (.xin(xin21),  // sfix33_En24
                                                  .yin(yin21),  // sfix33_En24
                                                  .zin(zin21),  // sfix35_En34
                                                  .lut_value(lut_value21),  // ufix32_En34
                                                  .idx(shift21),  // ufix6
                                                  .xout(xout21),  // sfix33_En24
                                                  .yout(yout21),  // sfix33_En24
                                                  .zout(zout21)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline21_process
      if (reset == 1'b1) begin
        xin22 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin22 <= xout21;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline21_1_process
      if (reset == 1'b1) begin
        yin22 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin22 <= yout21;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline21_2_process
      if (reset == 1'b1) begin
        zin22 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin22 <= zout21;
        end
      end
    end

  assign lut_value22 = 32'b00000000000000000000010100011000;

  assign shift22 = 6'b010110;

  Receiver_ip_src_CordicKernelMag u_Iteration_21 (.xin(xin22),  // sfix33_En24
                                                  .yin(yin22),  // sfix33_En24
                                                  .zin(zin22),  // sfix35_En34
                                                  .lut_value(lut_value22),  // ufix32_En34
                                                  .idx(shift22),  // ufix6
                                                  .xout(xout22),  // sfix33_En24
                                                  .yout(yout22),  // sfix33_En24
                                                  .zout(zout22)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline22_process
      if (reset == 1'b1) begin
        xin23 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin23 <= xout22;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline22_1_process
      if (reset == 1'b1) begin
        yin23 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin23 <= yout22;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline22_2_process
      if (reset == 1'b1) begin
        zin23 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin23 <= zout22;
        end
      end
    end

  assign lut_value23 = 32'b00000000000000000000001010001100;

  assign shift23 = 6'b010111;

  Receiver_ip_src_CordicKernelMag u_Iteration_22 (.xin(xin23),  // sfix33_En24
                                                  .yin(yin23),  // sfix33_En24
                                                  .zin(zin23),  // sfix35_En34
                                                  .lut_value(lut_value23),  // ufix32_En34
                                                  .idx(shift23),  // ufix6
                                                  .xout(xout23),  // sfix33_En24
                                                  .yout(yout23),  // sfix33_En24
                                                  .zout(zout23)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline23_process
      if (reset == 1'b1) begin
        xin24 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin24 <= xout23;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline23_1_process
      if (reset == 1'b1) begin
        yin24 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin24 <= yout23;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline23_2_process
      if (reset == 1'b1) begin
        zin24 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin24 <= zout23;
        end
      end
    end

  assign lut_value24 = 32'b00000000000000000000000101000110;

  assign shift24 = 6'b011000;

  Receiver_ip_src_CordicKernelMag u_Iteration_23 (.xin(xin24),  // sfix33_En24
                                                  .yin(yin24),  // sfix33_En24
                                                  .zin(zin24),  // sfix35_En34
                                                  .lut_value(lut_value24),  // ufix32_En34
                                                  .idx(shift24),  // ufix6
                                                  .xout(xout24),  // sfix33_En24
                                                  .yout(yout24),  // sfix33_En24
                                                  .zout(zout24)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline24_process
      if (reset == 1'b1) begin
        xin25 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin25 <= xout24;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline24_1_process
      if (reset == 1'b1) begin
        yin25 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin25 <= yout24;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline24_2_process
      if (reset == 1'b1) begin
        zin25 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin25 <= zout24;
        end
      end
    end

  assign lut_value25 = 32'b00000000000000000000000010100011;

  assign shift25 = 6'b011001;

  Receiver_ip_src_CordicKernelMag u_Iteration_24 (.xin(xin25),  // sfix33_En24
                                                  .yin(yin25),  // sfix33_En24
                                                  .zin(zin25),  // sfix35_En34
                                                  .lut_value(lut_value25),  // ufix32_En34
                                                  .idx(shift25),  // ufix6
                                                  .xout(xout25),  // sfix33_En24
                                                  .yout(yout25),  // sfix33_En24
                                                  .zout(zout25)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline25_process
      if (reset == 1'b1) begin
        xin26 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin26 <= xout25;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline25_1_process
      if (reset == 1'b1) begin
        yin26 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin26 <= yout25;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline25_2_process
      if (reset == 1'b1) begin
        zin26 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin26 <= zout25;
        end
      end
    end

  assign lut_value26 = 32'b00000000000000000000000001010001;

  assign shift26 = 6'b011010;

  Receiver_ip_src_CordicKernelMag u_Iteration_25 (.xin(xin26),  // sfix33_En24
                                                  .yin(yin26),  // sfix33_En24
                                                  .zin(zin26),  // sfix35_En34
                                                  .lut_value(lut_value26),  // ufix32_En34
                                                  .idx(shift26),  // ufix6
                                                  .xout(xout26),  // sfix33_En24
                                                  .yout(yout26),  // sfix33_En24
                                                  .zout(zout26)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline26_process
      if (reset == 1'b1) begin
        xin27 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin27 <= xout26;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline26_1_process
      if (reset == 1'b1) begin
        yin27 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin27 <= yout26;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline26_2_process
      if (reset == 1'b1) begin
        zin27 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin27 <= zout26;
        end
      end
    end

  assign lut_value27 = 32'b00000000000000000000000000101001;

  assign shift27 = 6'b011011;

  Receiver_ip_src_CordicKernelMag u_Iteration_26 (.xin(xin27),  // sfix33_En24
                                                  .yin(yin27),  // sfix33_En24
                                                  .zin(zin27),  // sfix35_En34
                                                  .lut_value(lut_value27),  // ufix32_En34
                                                  .idx(shift27),  // ufix6
                                                  .xout(xout27),  // sfix33_En24
                                                  .yout(yout27),  // sfix33_En24
                                                  .zout(zout27)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline27_process
      if (reset == 1'b1) begin
        xin28 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin28 <= xout27;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline27_1_process
      if (reset == 1'b1) begin
        yin28 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin28 <= yout27;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline27_2_process
      if (reset == 1'b1) begin
        zin28 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin28 <= zout27;
        end
      end
    end

  assign lut_value28 = 32'b00000000000000000000000000010100;

  assign shift28 = 6'b011100;

  Receiver_ip_src_CordicKernelMag u_Iteration_27 (.xin(xin28),  // sfix33_En24
                                                  .yin(yin28),  // sfix33_En24
                                                  .zin(zin28),  // sfix35_En34
                                                  .lut_value(lut_value28),  // ufix32_En34
                                                  .idx(shift28),  // ufix6
                                                  .xout(xout28),  // sfix33_En24
                                                  .yout(yout28),  // sfix33_En24
                                                  .zout(zout28)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline28_process
      if (reset == 1'b1) begin
        xin29 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin29 <= xout28;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline28_1_process
      if (reset == 1'b1) begin
        yin29 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin29 <= yout28;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline28_2_process
      if (reset == 1'b1) begin
        zin29 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin29 <= zout28;
        end
      end
    end

  assign lut_value29 = 32'b00000000000000000000000000001010;

  assign shift29 = 6'b011101;

  Receiver_ip_src_CordicKernelMag u_Iteration_28 (.xin(xin29),  // sfix33_En24
                                                  .yin(yin29),  // sfix33_En24
                                                  .zin(zin29),  // sfix35_En34
                                                  .lut_value(lut_value29),  // ufix32_En34
                                                  .idx(shift29),  // ufix6
                                                  .xout(xout29),  // sfix33_En24
                                                  .yout(yout29),  // sfix33_En24
                                                  .zout(zout29)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline29_process
      if (reset == 1'b1) begin
        xin30 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          xin30 <= xout29;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline29_1_process
      if (reset == 1'b1) begin
        yin30 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin30 <= yout29;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline29_2_process
      if (reset == 1'b1) begin
        zin30 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin30 <= zout29;
        end
      end
    end

  assign lut_value30 = 32'b00000000000000000000000000000101;

  assign shift30 = 6'b011110;

  Receiver_ip_src_CordicKernelMag u_Iteration_29 (.xin(xin30),  // sfix33_En24
                                                  .yin(yin30),  // sfix33_En24
                                                  .zin(zin30),  // sfix35_En34
                                                  .lut_value(lut_value30),  // ufix32_En34
                                                  .idx(shift30),  // ufix6
                                                  .xout(xout30deadOut),  // sfix33_En24
                                                  .yout(yout30),  // sfix33_En24
                                                  .zout(zout30)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline30_process
      if (reset == 1'b1) begin
        yin31 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          yin31 <= yout30;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Pipeline30_1_process
      if (reset == 1'b1) begin
        zin31 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin31 <= zout30;
        end
      end
    end

  assign lut_value31 = 32'b00000000000000000000000000000011;

  assign shift31deadIn = 6'b000000;

  Receiver_ip_src_CordicKernelMag u_Iteration_30 (.xin(xin31deadIn),  // sfix33_En24
                                                  .yin(yin31),  // sfix33_En24
                                                  .zin(zin31),  // sfix35_En34
                                                  .lut_value(lut_value31),  // ufix32_En34
                                                  .idx(shift31deadIn),  // ufix6
                                                  .xout(xout31deadOut),  // sfix33_En24
                                                  .yout(yout31deadOut),  // sfix33_En24
                                                  .zout(zout31)  // sfix35_En34
                                                  );

  always @(posedge clk or posedge reset)
    begin : Pipeline31_process
      if (reset == 1'b1) begin
        zin32 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zin32 <= zout31;
        end
      end
    end

  assign reset_outval =  ~ ValidOutDelayed;

  always @(posedge clk or posedge reset)
    begin : DelayQC_Control_process
      if (reset == 1'b1) begin
        for(DelayQC_Control_t_1 = 32'sd0; DelayQC_Control_t_1 <= 32'sd31; DelayQC_Control_t_1 = DelayQC_Control_t_1 + 32'sd1) begin
          DelayQC_Control_reg[DelayQC_Control_t_1] <= 5'b00000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(DelayQC_Control_t_0_1 = 32'sd0; DelayQC_Control_t_0_1 <= 32'sd31; DelayQC_Control_t_0_1 = DelayQC_Control_t_0_1 + 32'sd1) begin
            DelayQC_Control_reg[DelayQC_Control_t_0_1] <= DelayQC_Control_reg_next[DelayQC_Control_t_0_1];
          end
        end
      end
    end

  always @* begin
    ControlQCDelay = DelayQC_Control_reg[31];
    DelayQC_Control_reg_next[0] = ControlQC;

    for(DelayQC_Control_t_0_0 = 32'sd0; DelayQC_Control_t_0_0 <= 32'sd30; DelayQC_Control_t_0_0 = DelayQC_Control_t_0_0 + 32'sd1) begin
      DelayQC_Control_reg_next[DelayQC_Control_t_0_0 + 32'sd1] = DelayQC_Control_reg[DelayQC_Control_t_0_0];
    end

  end

  Receiver_ip_src_Quadrant_Correction u_QuadrantCorrection (.zin(zin32),  // sfix35_En34
                                                            .QA_Control(ControlQCDelay),  // ufix5
                                                            .zout(zout_corrected)  // sfix35_En34
                                                            );

  assign zeroCA = 35'sh000000000;

  assign outSwitchAng = (reset_outval == 1'b0 ? zout_corrected :
              zeroCA);

  always @(posedge clk or posedge reset)
    begin : Output_Register_process
      if (reset == 1'b1) begin
        zout_corrected_1 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          zout_corrected_1 <= outSwitchAng;
        end
      end
    end

  assign angle = zout_corrected_1;

  always @(posedge clk or posedge reset)
    begin : DelayValidOut_process
      if (reset == 1'b1) begin
        validOut_1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          validOut_1 <= ValidOutDelayed;
        end
      end
    end

  assign validOut = validOut_1;

endmodule  // Receiver_ip_src_HDL_CMA_core

