// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Frequency_and_Time_Synchronizer.v
// Created: 2026-05-26 18:50:49
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Frequency_and_Time_Synchronizer
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer
// Hierarchy Level: 2
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Frequency_and_Time_Synchronizer
          (clk,
           reset,
           enb_1_2_0,
           dataIn_re,
           dataIn_im,
           validIn,
           rstCS,
           dataOut_re,
           dataOut_im,
           startOut,
           endOut,
           validOut,
           postSymbolSync_re,
           postSymbolSync_im,
           postCarrierSync_re,
           postCarrierSync_im,
           nSynced,
           normCoarseFreqEst);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [15:0] dataIn_re;  // sfix16_En12
  input   signed [15:0] dataIn_im;  // sfix16_En12
  input   validIn;
  input   rstCS;
  output  signed [15:0] dataOut_re;  // sfix16_En14
  output  signed [15:0] dataOut_im;  // sfix16_En14
  output  startOut;
  output  endOut;
  output  validOut;
  output  signed [15:0] postSymbolSync_re;  // sfix16_En14
  output  signed [15:0] postSymbolSync_im;  // sfix16_En14
  output  signed [15:0] postCarrierSync_re;  // sfix16_En14
  output  signed [15:0] postCarrierSync_im;  // sfix16_En14
  output  nSynced;
  output  signed [20:0] normCoarseFreqEst;  // sfix21_En21


  wire signed [15:0] Symbol_Synchronizer_dataOut_re;  // sfix16_En14
  wire signed [15:0] Symbol_Synchronizer_dataOut_im;  // sfix16_En14
  wire Symbol_Synchronizer_validOut;
  wire signed [15:0] Coarse_Frequency_Compensator_dataOut_re;  // sfix16_En14
  wire signed [15:0] Coarse_Frequency_Compensator_dataOut_im;  // sfix16_En14
  wire Coarse_Frequency_Compensator_rstCS;
  wire Coarse_Frequency_Compensator_validOut;
  wire signed [20:0] Coarse_Frequency_Compensator_normalizedFreqEst;  // sfix21_En21
  wire signed [15:0] Carrier_Synchronizer_dataOut_re;  // sfix16_En14
  wire signed [15:0] Carrier_Synchronizer_dataOut_im;  // sfix16_En14
  wire Carrier_Synchronizer_validOut;
  wire signed [15:0] Preamble_Detector_dataOut_re;  // sfix16_En14
  wire signed [15:0] Preamble_Detector_dataOut_im;  // sfix16_En14
  wire Preamble_Detector_syncPulse;
  wire Preamble_Detector_validOut;
  wire signed [15:0] Phase_Ambiguity_Estimation_and_Correction_dataOut_re;  // sfix16_En14
  wire signed [15:0] Phase_Ambiguity_Estimation_and_Correction_dataOut_im;  // sfix16_En14
  wire Phase_Ambiguity_Estimation_and_Correction_syncPulseOut;
  wire Phase_Ambiguity_Estimation_and_Correction_validOut;
  wire signed [15:0] Packet_Controller_dataOut_re;  // sfix16_En14
  wire signed [15:0] Packet_Controller_dataOut_im;  // sfix16_En14
  wire Packet_Controller_startOut;
  wire Packet_Controller_endOut;
  wire Packet_Controller_validOut;


  Receiver_ip_src_Symbol_Synchronizer u_Symbol_Synchronizer (.clk(clk),
                                                             .reset(reset),
                                                             .enb_1_2_0(enb_1_2_0),
                                                             .dataIn_re(dataIn_re),  // sfix16_En12
                                                             .dataIn_im(dataIn_im),  // sfix16_En12
                                                             .validIn(validIn),
                                                             .dataOut_re(Symbol_Synchronizer_dataOut_re),  // sfix16_En14
                                                             .dataOut_im(Symbol_Synchronizer_dataOut_im),  // sfix16_En14
                                                             .validOut(Symbol_Synchronizer_validOut)
                                                             );

  Receiver_ip_src_Coarse_Frequency_Compensator u_Coarse_Frequency_Compensator (.clk(clk),
                                                                               .reset(reset),
                                                                               .enb_1_2_0(enb_1_2_0),
                                                                               .dataIn_re(Symbol_Synchronizer_dataOut_re),  // sfix16_En14
                                                                               .dataIn_im(Symbol_Synchronizer_dataOut_im),  // sfix16_En14
                                                                               .validIn(Symbol_Synchronizer_validOut),
                                                                               .dataOut_re(Coarse_Frequency_Compensator_dataOut_re),  // sfix16_En14
                                                                               .dataOut_im(Coarse_Frequency_Compensator_dataOut_im),  // sfix16_En14
                                                                               .rstCS(Coarse_Frequency_Compensator_rstCS),
                                                                               .validOut(Coarse_Frequency_Compensator_validOut),
                                                                               .normalizedFreqEst(Coarse_Frequency_Compensator_normalizedFreqEst)  // sfix21_En21
                                                                               );

  Receiver_ip_src_Carrier_Synchronizer u_Carrier_Synchronizer (.clk(clk),
                                                               .reset(reset),
                                                               .enb_1_2_0(enb_1_2_0),
                                                               .dataIn_re(Coarse_Frequency_Compensator_dataOut_re),  // sfix16_En14
                                                               .dataIn_im(Coarse_Frequency_Compensator_dataOut_im),  // sfix16_En14
                                                               .internalRst(Coarse_Frequency_Compensator_rstCS),
                                                               .validIn(Coarse_Frequency_Compensator_validOut),
                                                               .manualRst(rstCS),
                                                               .dataOut_re(Carrier_Synchronizer_dataOut_re),  // sfix16_En14
                                                               .dataOut_im(Carrier_Synchronizer_dataOut_im),  // sfix16_En14
                                                               .validOut(Carrier_Synchronizer_validOut)
                                                               );

  Receiver_ip_src_Preamble_Detector u_Preamble_Detector (.clk(clk),
                                                         .reset(reset),
                                                         .enb_1_2_0(enb_1_2_0),
                                                         .dataIn_re(Carrier_Synchronizer_dataOut_re),  // sfix16_En14
                                                         .dataIn_im(Carrier_Synchronizer_dataOut_im),  // sfix16_En14
                                                         .validIn(Carrier_Synchronizer_validOut),
                                                         .dataOut_re(Preamble_Detector_dataOut_re),  // sfix16_En14
                                                         .dataOut_im(Preamble_Detector_dataOut_im),  // sfix16_En14
                                                         .syncPulse(Preamble_Detector_syncPulse),
                                                         .validOut(Preamble_Detector_validOut)
                                                         );

  Receiver_ip_src_Phase_Ambiguity_Estimation_and_Correction u_Phase_Ambiguity_Estimation_and_Correction (.clk(clk),
                                                                                                         .reset(reset),
                                                                                                         .enb_1_2_0(enb_1_2_0),
                                                                                                         .dataIn_re(Preamble_Detector_dataOut_re),  // sfix16_En14
                                                                                                         .dataIn_im(Preamble_Detector_dataOut_im),  // sfix16_En14
                                                                                                         .syncPulseIn(Preamble_Detector_syncPulse),
                                                                                                         .validIn(Preamble_Detector_validOut),
                                                                                                         .dataOut_re(Phase_Ambiguity_Estimation_and_Correction_dataOut_re),  // sfix16_En14
                                                                                                         .dataOut_im(Phase_Ambiguity_Estimation_and_Correction_dataOut_im),  // sfix16_En14
                                                                                                         .syncPulseOut(Phase_Ambiguity_Estimation_and_Correction_syncPulseOut),
                                                                                                         .validOut(Phase_Ambiguity_Estimation_and_Correction_validOut)
                                                                                                         );

  Receiver_ip_src_Packet_Controller u_Packet_Controller (.clk(clk),
                                                         .reset(reset),
                                                         .enb_1_2_0(enb_1_2_0),
                                                         .dataIn_re(Phase_Ambiguity_Estimation_and_Correction_dataOut_re),  // sfix16_En14
                                                         .dataIn_im(Phase_Ambiguity_Estimation_and_Correction_dataOut_im),  // sfix16_En14
                                                         .syncPulse(Phase_Ambiguity_Estimation_and_Correction_syncPulseOut),
                                                         .validIn(Phase_Ambiguity_Estimation_and_Correction_validOut),
                                                         .dataOut_re(Packet_Controller_dataOut_re),  // sfix16_En14
                                                         .dataOut_im(Packet_Controller_dataOut_im),  // sfix16_En14
                                                         .startOut(Packet_Controller_startOut),
                                                         .endOut(Packet_Controller_endOut),
                                                         .validOut(Packet_Controller_validOut)
                                                         );

  assign dataOut_re = Packet_Controller_dataOut_re;

  assign dataOut_im = Packet_Controller_dataOut_im;

  assign startOut = Packet_Controller_startOut;

  assign endOut = Packet_Controller_endOut;

  assign validOut = Packet_Controller_validOut;

  assign postSymbolSync_re = Symbol_Synchronizer_dataOut_re;

  assign postSymbolSync_im = Symbol_Synchronizer_dataOut_im;

  assign postCarrierSync_re = Carrier_Synchronizer_dataOut_re;

  assign postCarrierSync_im = Carrier_Synchronizer_dataOut_im;

  assign nSynced = Preamble_Detector_syncPulse;

  assign normCoarseFreqEst = Coarse_Frequency_Compensator_normalizedFreqEst;

endmodule  // Receiver_ip_src_Frequency_and_Time_Synchronizer

