// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Direct_Digital_Synthesis.v
// Created: 2026-05-26 18:50:47
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Direct_Digital_Synthesis
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Carrier Synchronizer/Direct Digital 
// Synthesi
// Hierarchy Level: 4
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Direct_Digital_Synthesis
          (clk,
           reset,
           enb_1_2_0,
           rst,
           validIn,
           phaseInc,
           expOut_re,
           expOut_im);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   rst;
  input   validIn;
  input   signed [39:0] phaseInc;  // sfix40_En39
  output  signed [15:0] expOut_re;  // sfix16_En14
  output  signed [15:0] expOut_im;  // sfix16_En14


  reg signed [39:0] Delay_out1;  // sfix40_En39
  wire signed [20:0] Data_Type_Conversion_out1;  // sfix21_En21
  wire signed [20:0] Data_Type_Conversion1_out1;  // sfix21
  wire signed [15:0] NCO_out1_re;  // sfix16_En14
  wire signed [15:0] NCO_out1_im;  // sfix16_En14


  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay_out1 <= phaseInc;
        end
      end
    end

  assign Data_Type_Conversion_out1 = Delay_out1[38:18];

  assign Data_Type_Conversion1_out1 = Data_Type_Conversion_out1;

  Receiver_ip_src_NCO u_NCO (.clk(clk),
                             .reset(reset),
                             .enb_1_2_0(enb_1_2_0),
                             .inc(Data_Type_Conversion1_out1),  // sfix21
                             .resetPhase(rst),
                             .validIn(validIn),
                             .complexexp_re(NCO_out1_re),  // sfix16_En14
                             .complexexp_im(NCO_out1_im)  // sfix16_En14
                             );

  assign expOut_re = NCO_out1_re;

  assign expOut_im = NCO_out1_im;

endmodule  // Receiver_ip_src_Direct_Digital_Synthesis

