// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_GTED.v
// Created: 2026-05-26 18:50:49
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_GTED
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Symbol Synchronizer/Gardner TED/GTED
// Hierarchy Level: 5
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_GTED
          (clk,
           reset,
           enb_1_2_0,
           In1_re,
           In1_im,
           Out1);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [18:0] In1_re;  // sfix19_En12
  input   signed [18:0] In1_im;  // sfix19_En12
  output  signed [39:0] Out1;  // sfix40_En24


  reg signed [18:0] Delay_out1;  // sfix19_En12
  reg signed [18:0] Delay1_out1;  // sfix19_En12
  reg signed [18:0] Delay8_reg [0:1];  // sfix19 [2]
  wire signed [18:0] Delay8_reg_next [0:1];  // sfix19_En12 [2]
  wire signed [18:0] Delay8_out1;  // sfix19_En12
  reg signed [18:0] Delay2_out1;  // sfix19_En12
  reg signed [18:0] Delay3_out1;  // sfix19_En12
  wire signed [19:0] Add1_sub_cast;  // sfix20_En12
  wire signed [19:0] Add1_sub_cast_1;  // sfix20_En12
  wire signed [19:0] Add1_out1;  // sfix20_En12
  reg signed [19:0] Delay9_reg [0:1];  // sfix20 [2]
  wire signed [19:0] Delay9_reg_next [0:1];  // sfix20_En12 [2]
  wire signed [19:0] Delay9_out1;  // sfix20_En12
  wire signed [38:0] Product_out1;  // sfix39_En24
  reg signed [38:0] Delay10_reg [0:1];  // sfix39 [2]
  wire signed [38:0] Delay10_reg_next [0:1];  // sfix39_En24 [2]
  wire signed [38:0] Delay10_out1;  // sfix39_En24
  reg signed [18:0] Delay4_out1;  // sfix19_En12
  reg signed [18:0] Delay5_out1;  // sfix19_En12
  reg signed [18:0] Delay11_reg [0:1];  // sfix19 [2]
  wire signed [18:0] Delay11_reg_next [0:1];  // sfix19_En12 [2]
  wire signed [18:0] Delay11_out1;  // sfix19_En12
  reg signed [18:0] Delay6_out1;  // sfix19_En12
  reg signed [18:0] Delay7_out1;  // sfix19_En12
  wire signed [19:0] Add2_sub_cast;  // sfix20_En12
  wire signed [19:0] Add2_sub_cast_1;  // sfix20_En12
  wire signed [19:0] Add2_out1;  // sfix20_En12
  reg signed [19:0] Delay12_reg [0:1];  // sfix20 [2]
  wire signed [19:0] Delay12_reg_next [0:1];  // sfix20_En12 [2]
  wire signed [19:0] Delay12_out1;  // sfix20_En12
  wire signed [38:0] Product1_out1;  // sfix39_En24
  reg signed [38:0] Delay13_reg [0:1];  // sfix39 [2]
  wire signed [38:0] Delay13_reg_next [0:1];  // sfix39_En24 [2]
  wire signed [38:0] Delay13_out1;  // sfix39_En24
  wire signed [39:0] Add_add_cast;  // sfix40_En24
  wire signed [39:0] Add_add_cast_1;  // sfix40_En24
  wire signed [39:0] Add_out1;  // sfix40_En24
  reg signed [31:0] Delay8_t_0_0;  // int32
  reg signed [31:0] Delay8_t_1;  // int32
  reg signed [31:0] Delay9_t_0_0;  // int32
  reg signed [31:0] Delay9_t_1;  // int32
  reg signed [31:0] Delay10_t_0_0;  // int32
  reg signed [31:0] Delay10_t_1;  // int32
  reg signed [31:0] Delay11_t_0_0;  // int32
  reg signed [31:0] Delay11_t_1;  // int32
  reg signed [31:0] Delay12_t_0_0;  // int32
  reg signed [31:0] Delay12_t_1;  // int32
  reg signed [31:0] Delay13_t_0_0;  // int32
  reg signed [31:0] Delay13_t_1;  // int32


  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay_out1 <= In1_re;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay1_out1 <= Delay_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay8_process
      if (reset == 1'b1) begin
        for(Delay8_t_1 = 32'sd0; Delay8_t_1 <= 32'sd1; Delay8_t_1 = Delay8_t_1 + 32'sd1) begin
          Delay8_reg[Delay8_t_1] <= 19'sb0000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay8_t_0_0 = 32'sd0; Delay8_t_0_0 <= 32'sd1; Delay8_t_0_0 = Delay8_t_0_0 + 32'sd1) begin
            Delay8_reg[Delay8_t_0_0] <= Delay8_reg_next[Delay8_t_0_0];
          end
        end
      end
    end

  assign Delay8_out1 = Delay8_reg[1];
  assign Delay8_reg_next[0] = Delay1_out1;
  assign Delay8_reg_next[1] = Delay8_reg[0];

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay2_out1 <= Delay1_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay3_out1 <= Delay2_out1;
        end
      end
    end

  assign Add1_sub_cast = {Delay3_out1[18], Delay3_out1};
  assign Add1_sub_cast_1 = {In1_re[18], In1_re};
  assign Add1_out1 = Add1_sub_cast - Add1_sub_cast_1;

  always @(posedge clk or posedge reset)
    begin : Delay9_process
      if (reset == 1'b1) begin
        for(Delay9_t_1 = 32'sd0; Delay9_t_1 <= 32'sd1; Delay9_t_1 = Delay9_t_1 + 32'sd1) begin
          Delay9_reg[Delay9_t_1] <= 20'sb00000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay9_t_0_0 = 32'sd0; Delay9_t_0_0 <= 32'sd1; Delay9_t_0_0 = Delay9_t_0_0 + 32'sd1) begin
            Delay9_reg[Delay9_t_0_0] <= Delay9_reg_next[Delay9_t_0_0];
          end
        end
      end
    end

  assign Delay9_out1 = Delay9_reg[1];
  assign Delay9_reg_next[0] = Add1_out1;
  assign Delay9_reg_next[1] = Delay9_reg[0];

  assign Product_out1 = Delay8_out1 * Delay9_out1;

  always @(posedge clk or posedge reset)
    begin : Delay10_process
      if (reset == 1'b1) begin
        for(Delay10_t_1 = 32'sd0; Delay10_t_1 <= 32'sd1; Delay10_t_1 = Delay10_t_1 + 32'sd1) begin
          Delay10_reg[Delay10_t_1] <= 39'sh0000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay10_t_0_0 = 32'sd0; Delay10_t_0_0 <= 32'sd1; Delay10_t_0_0 = Delay10_t_0_0 + 32'sd1) begin
            Delay10_reg[Delay10_t_0_0] <= Delay10_reg_next[Delay10_t_0_0];
          end
        end
      end
    end

  assign Delay10_out1 = Delay10_reg[1];
  assign Delay10_reg_next[0] = Product_out1;
  assign Delay10_reg_next[1] = Delay10_reg[0];

  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay4_out1 <= In1_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1 <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay5_out1 <= Delay4_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay11_process
      if (reset == 1'b1) begin
        for(Delay11_t_1 = 32'sd0; Delay11_t_1 <= 32'sd1; Delay11_t_1 = Delay11_t_1 + 32'sd1) begin
          Delay11_reg[Delay11_t_1] <= 19'sb0000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay11_t_0_0 = 32'sd0; Delay11_t_0_0 <= 32'sd1; Delay11_t_0_0 = Delay11_t_0_0 + 32'sd1) begin
            Delay11_reg[Delay11_t_0_0] <= Delay11_reg_next[Delay11_t_0_0];
          end
        end
      end
    end

  assign Delay11_out1 = Delay11_reg[1];
  assign Delay11_reg_next[0] = Delay5_out1;
  assign Delay11_reg_next[1] = Delay11_reg[0];

  always @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_out1 <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay6_out1 <= Delay5_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 19'sb0000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay7_out1 <= Delay6_out1;
        end
      end
    end

  assign Add2_sub_cast = {Delay7_out1[18], Delay7_out1};
  assign Add2_sub_cast_1 = {In1_im[18], In1_im};
  assign Add2_out1 = Add2_sub_cast - Add2_sub_cast_1;

  always @(posedge clk or posedge reset)
    begin : Delay12_process
      if (reset == 1'b1) begin
        for(Delay12_t_1 = 32'sd0; Delay12_t_1 <= 32'sd1; Delay12_t_1 = Delay12_t_1 + 32'sd1) begin
          Delay12_reg[Delay12_t_1] <= 20'sb00000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay12_t_0_0 = 32'sd0; Delay12_t_0_0 <= 32'sd1; Delay12_t_0_0 = Delay12_t_0_0 + 32'sd1) begin
            Delay12_reg[Delay12_t_0_0] <= Delay12_reg_next[Delay12_t_0_0];
          end
        end
      end
    end

  assign Delay12_out1 = Delay12_reg[1];
  assign Delay12_reg_next[0] = Add2_out1;
  assign Delay12_reg_next[1] = Delay12_reg[0];

  assign Product1_out1 = Delay11_out1 * Delay12_out1;

  always @(posedge clk or posedge reset)
    begin : Delay13_process
      if (reset == 1'b1) begin
        for(Delay13_t_1 = 32'sd0; Delay13_t_1 <= 32'sd1; Delay13_t_1 = Delay13_t_1 + 32'sd1) begin
          Delay13_reg[Delay13_t_1] <= 39'sh0000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay13_t_0_0 = 32'sd0; Delay13_t_0_0 <= 32'sd1; Delay13_t_0_0 = Delay13_t_0_0 + 32'sd1) begin
            Delay13_reg[Delay13_t_0_0] <= Delay13_reg_next[Delay13_t_0_0];
          end
        end
      end
    end

  assign Delay13_out1 = Delay13_reg[1];
  assign Delay13_reg_next[0] = Product1_out1;
  assign Delay13_reg_next[1] = Delay13_reg[0];

  assign Add_add_cast = {Delay10_out1[38], Delay10_out1};
  assign Add_add_cast_1 = {Delay13_out1[38], Delay13_out1};
  assign Add_out1 = Add_add_cast + Add_add_cast_1;

  assign Out1 = Add_out1;

endmodule  // Receiver_ip_src_GTED

