// -------------------------------------------------------------
// 
// File Name: hdl_prj_jupiter_txrx/hdlsrc/commhdlQPSKTxRx/Receiver_ip_src_Extract_Frequency.v
// Created: 2026-05-26 18:50:47
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Receiver_ip_src_Extract_Frequency
// Source Path: commhdlQPSKTxRx/Receiver/QPSK Rx/Frequency and Time Synchronizer/Coarse Frequency Compensator/Coarse 
// Frequency Estimator/Extract Frequenc
// Hierarchy Level: 5
// Model version: 11.305
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Receiver_ip_src_Extract_Frequency
          (clk,
           reset,
           enb_1_2_0,
           datain_re,
           datain_im,
           validIn,
           normFreqOut);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [31:0] datain_re;  // sfix32_En24
  input   signed [31:0] datain_im;  // sfix32_En24
  input   validIn;
  output  signed [34:0] normFreqOut;  // sfix35_En34


  reg signed [31:0] Delay1_out1_re;  // sfix32_En24
  reg signed [31:0] Delay1_out1_im;  // sfix32_En24
  reg  Delay4_out1;
  wire signed [34:0] Complex_to_Magnitude_Angle_HDL_Optimized_out1;  // sfix35_En34
  wire Complex_to_Magnitude_Angle_HDL_Optimized_out2;
  reg signed [34:0] Unit_Delay_Enabled_Synchronous_out1;  // sfix35_En34
  reg signed [34:0] Delay2_out1;  // sfix35_En34
  wire signed [35:0] Gain_cast;  // sfix36_En35
  wire signed [34:0] Gain_out1;  // sfix35_En34
  reg signed [34:0] Delay3_out1;  // sfix35_En34


  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1_re <= 32'sb00000000000000000000000000000000;
        Delay1_out1_im <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay1_out1_re <= datain_re;
          Delay1_out1_im <= datain_im;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay4_out1 <= validIn;
        end
      end
    end

  Receiver_ip_src_HDL_CMA_core u_Complex_to_Magnitude_Angle_HDL_Optimized (.clk(clk),
                                                                           .reset(reset),
                                                                           .enb_1_2_0(enb_1_2_0),
                                                                           .In_re(Delay1_out1_re),  // sfix32_En24
                                                                           .In_im(Delay1_out1_im),  // sfix32_En24
                                                                           .validIn(Delay4_out1),
                                                                           .angle(Complex_to_Magnitude_Angle_HDL_Optimized_out1),  // sfix35_En34
                                                                           .validOut(Complex_to_Magnitude_Angle_HDL_Optimized_out2)
                                                                           );

  always @(posedge clk or posedge reset)
    begin : Unit_Delay_Enabled_Synchronous_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Synchronous_out1 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0 && Complex_to_Magnitude_Angle_HDL_Optimized_out2) begin
          Unit_Delay_Enabled_Synchronous_out1 <= Complex_to_Magnitude_Angle_HDL_Optimized_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay2_out1 <= Unit_Delay_Enabled_Synchronous_out1;
        end
      end
    end

  assign Gain_cast = {Delay2_out1[34], Delay2_out1};
  assign Gain_out1 = Gain_cast[35:1];

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 35'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay3_out1 <= Gain_out1;
        end
      end
    end

  assign normFreqOut = Delay3_out1;

endmodule  // Receiver_ip_src_Extract_Frequency

