# Define the Python interpreter
PYTHON = python

# Define the targets and their dependencies
all: gen_sysobj_pages gen_rd_svg gen_hdl_refdesigns

gen_sysobj_pages:
	$(PYTHON) gen_sysobj_pages.py

gen_rd_svg:
	$(PYTHON) gen_rd_svg.py

gen_hdl_refdesigns:
	$(PYTHON) gen_hdl_refdesigns.py